// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1alpha1

// NodeFeatureListerExpansion allows custom methods to be added to
// NodeFeatureLister.
type NodeFeatureListerExpansion interface{}

// NodeFeatureNamespaceListerExpansion allows custom methods to be added to
// NodeFeatureNamespaceLister.
type NodeFeatureNamespaceListerExpansion interface{}

// NodeFeatureGroupListerExpansion allows custom methods to be added to
// NodeFeatureGroupLister.
type NodeFeatureGroupListerExpansion interface{}

// NodeFeatureGroupNamespaceListerExpansion allows custom methods to be added to
// NodeFeatureGroupNamespaceLister.
type NodeFeatureGroupNamespaceListerExpansion interface{}

// NodeFeatureRuleListerExpansion allows custom methods to be added to
// NodeFeatureRuleLister.
type NodeFeatureRuleListerExpansion interface{}
