// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	serverv1alpha1 "gpustack.ai/gpustack/api/server/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterBindingLister helps list ClusterBindings.
// All objects returned here must be treated as read-only.
type ClusterBindingLister interface {
	// List lists all ClusterBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*serverv1alpha1.ClusterBinding, err error)
	// ClusterBindings returns an object that can list and get ClusterBindings.
	ClusterBindings(namespace string) ClusterBindingNamespaceLister
	ClusterBindingListerExpansion
}

// clusterBindingLister implements the ClusterBindingLister interface.
type clusterBindingLister struct {
	listers.ResourceIndexer[*serverv1alpha1.ClusterBinding]
}

// NewClusterBindingLister returns a new ClusterBindingLister.
func NewClusterBindingLister(indexer cache.Indexer) ClusterBindingLister {
	return &clusterBindingLister{listers.New[*serverv1alpha1.ClusterBinding](indexer, serverv1alpha1.Resource("clusterbinding"))}
}

// ClusterBindings returns an object that can list and get ClusterBindings.
func (s *clusterBindingLister) ClusterBindings(namespace string) ClusterBindingNamespaceLister {
	return clusterBindingNamespaceLister{listers.NewNamespaced[*serverv1alpha1.ClusterBinding](s.ResourceIndexer, namespace)}
}

// ClusterBindingNamespaceLister helps list and get ClusterBindings.
// All objects returned here must be treated as read-only.
type ClusterBindingNamespaceLister interface {
	// List lists all ClusterBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*serverv1alpha1.ClusterBinding, err error)
	// Get retrieves the ClusterBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*serverv1alpha1.ClusterBinding, error)
	ClusterBindingNamespaceListerExpansion
}

// clusterBindingNamespaceLister implements the ClusterBindingNamespaceLister
// interface.
type clusterBindingNamespaceLister struct {
	listers.ResourceIndexer[*serverv1alpha1.ClusterBinding]
}
