// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	storagev1beta1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/storage/v1beta1"
	typedstoragev1beta1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/storage/v1beta1"
	v1beta1 "k8s.io/api/storage/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCSINodes implements CSINodeInterface
type fakeCSINodes struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.CSINode, *v1beta1.CSINodeList, *storagev1beta1.CSINodeApplyConfiguration]
	Fake *FakeStorageV1beta1
}

func newFakeCSINodes(fake *FakeStorageV1beta1) typedstoragev1beta1.CSINodeInterface {
	return &fakeCSINodes{
		gentype.NewFakeClientWithListAndApply[*v1beta1.CSINode, *v1beta1.CSINodeList, *storagev1beta1.CSINodeApplyConfiguration](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("csinodes"),
			v1beta1.SchemeGroupVersion.WithKind("CSINode"),
			func() *v1beta1.CSINode { return &v1beta1.CSINode{} },
			func() *v1beta1.CSINodeList { return &v1beta1.CSINodeList{} },
			func(dst, src *v1beta1.CSINodeList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.CSINodeList) []*v1beta1.CSINode { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.CSINodeList, items []*v1beta1.CSINode) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
