//go:build kubernetes_protomessage_one_more_release
// +build kubernetes_protomessage_one_more_release

// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by go-to-protobuf. DO NOT EDIT.

package v1

func (*Cluster) ProtoMessage() {}

func (*ClusterConfig) ProtoMessage() {}

func (*ClusterConfigSpec) ProtoMessage() {}

func (*ClusterConfigStatus) ProtoMessage() {}

func (*ClusterImportConfig) ProtoMessage() {}

func (*ClusterImportConfigStatus) ProtoMessage() {}

func (*ClusterList) ProtoMessage() {}

func (*Project) ProtoMessage() {}

func (*ProjectCluster) ProtoMessage() {}

func (*ProjectClusters) ProtoMessage() {}

func (*ProjectList) ProtoMessage() {}

func (*ProjectSpec) ProtoMessage() {}

func (*ProjectStatus) ProtoMessage() {}

func (*Subject) ProtoMessage() {}

func (*SubjectList) ProtoMessage() {}

func (*SubjectLogin) ProtoMessage() {}

func (*SubjectLoginSpec) ProtoMessage() {}

func (*SubjectLoginStatus) ProtoMessage() {}

func (*SubjectProvider) ProtoMessage() {}

func (*SubjectProviderBitbucketConfig) ProtoMessage() {}

func (*SubjectProviderExternalConfig) ProtoMessage() {}

func (*SubjectProviderGitHubConfig) ProtoMessage() {}

func (*SubjectProviderGitLabConfig) ProtoMessage() {}

func (*SubjectProviderGiteaConfig) ProtoMessage() {}

func (*SubjectProviderGoogleConfig) ProtoMessage() {}

func (*SubjectProviderLDAPConfig) ProtoMessage() {}

func (*SubjectProviderLDAPGroupSearch) ProtoMessage() {}

func (*SubjectProviderLDAPUserSearch) ProtoMessage() {}

func (*SubjectProviderLdapGroupSearchUserMatcher) ProtoMessage() {}

func (*SubjectProviderList) ProtoMessage() {}

func (*SubjectProviderMicrosoftConfig) ProtoMessage() {}

func (*SubjectProviderOAuthClaimMapping) ProtoMessage() {}

func (*SubjectProviderOAuthConfig) ProtoMessage() {}

func (*SubjectProviderOIDCConfig) ProtoMessage() {}

func (*SubjectProviderSpec) ProtoMessage() {}

func (*SubjectProviderStatus) ProtoMessage() {}

func (*SubjectReference) ProtoMessage() {}

func (*SubjectSpec) ProtoMessage() {}

func (*SubjectToken) ProtoMessage() {}

func (*SubjectTokenSpec) ProtoMessage() {}

func (*SubjectTokenStatus) ProtoMessage() {}

func (*Team) ProtoMessage() {}

func (*TeamList) ProtoMessage() {}

func (*TeamSpec) ProtoMessage() {}

func (*TeamStatus) ProtoMessage() {}

func (*TeamSubject) ProtoMessage() {}

func (*TeamSubjects) ProtoMessage() {}
