// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	apiregistrationv1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/apiregistration/v1"
	typedapiregistrationv1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/apiregistration/v1"
	gentype "k8s.io/client-go/gentype"
	v1 "k8s.io/kube-aggregator/pkg/apis/apiregistration/v1"
)

// fakeAPIServices implements APIServiceInterface
type fakeAPIServices struct {
	*gentype.FakeClientWithListAndApply[*v1.APIService, *v1.APIServiceList, *apiregistrationv1.APIServiceApplyConfiguration]
	Fake *FakeApiregistrationV1
}

func newFakeAPIServices(fake *FakeApiregistrationV1) typedapiregistrationv1.APIServiceInterface {
	return &fakeAPIServices{
		gentype.NewFakeClientWithListAndApply[*v1.APIService, *v1.APIServiceList, *apiregistrationv1.APIServiceApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("apiservices"),
			v1.SchemeGroupVersion.WithKind("APIService"),
			func() *v1.APIService { return &v1.APIService{} },
			func() *v1.APIServiceList { return &v1.APIServiceList{} },
			func(dst, src *v1.APIServiceList) { dst.ListMeta = src.ListMeta },
			func(list *v1.APIServiceList) []*v1.APIService { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.APIServiceList, items []*v1.APIService) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
