---
GENERATOR:
  PackageName: acl
  PackageDescription: "Package ACL bindings"
  PackageLicense: |-
    SPDX-FileCopyrightText: 2026 GPUStack, Inc.
    SPDX-License-Identifier: Apache-2.0
    
    Copyright (c) 2025 Huawei Technologies Co., Ltd.
    This program is free software, you can redistribute it and/or modify it under the terms and conditions of
    CANN Open Software License Agreement Version 2.0 (the "License").
    Please refer to the License for details. You may not use this file except in compliance with the License.
    THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
    INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
    See LICENSE in the root of the software repository for the full text of the License.
  Includes:
    - "acl_base_rt.h"
    - "acl_rt.h"
  FlagGroups:
    - { name: "LDFLAGS", traits: [ "linux" ], flags: [ "-Wl,--export-dynamic", "-Wl,--unresolved-symbols=ignore-in-object-files" ] }
    - { name: "LDFLAGS", traits: [ "darwin" ], flags: [ "-Wl,-undefined,dynamic_lookup" ] }
    - { name: "CFLAGS", flags: [ "-w" ] }
PARSER:
  SourcesPaths:
    - "acl_base_rt.h"
    - "acl_rt.h"
TRANSLATOR:
  ConstRules:
    defines: eval
    enum: eval
  PtrTips:
    function:
      - { target: "^acl", default: "sref" }
  MemTips:
    - { target: "^acl", default: "raw" }
  Rules:
    const:
      - { action: accept }
      - { action: ignore, from: "^__" }
      - { action: ignore, from: "^_" }
      - { action: ignore, from: "^TARGET_" }
      - { action: replace, from: "^ACL_" }
      - { action: replace, from: "^acl" }
      - { transform: export }
    type:
      - { action: accept, from: "^acl" }
      - { action: replace, from: "^aclError$", to: "aclReturn" }
      - { action: replace, from: "^acl" }
      - { action: replace, from: "_t$" }
      - { transform: export }
    function:
      - { action: accept, from: "^acl" }
      - { transform: unexport }
