// Code generated by api. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// InstanceServicePortApplyConfiguration represents a declarative configuration of the InstanceServicePort type for use
// with apply.
//
// InstanceServicePort defines the port to expose from the container and the port to expose on the node.
type InstanceServicePortApplyConfiguration struct {
	InstancePortApplyConfiguration `json:",inline"`
	// NodePort is the port number to expose on the Kubernetes Node.
	NodePort *int32 `json:"nodePort,omitempty"`
}

// InstanceServicePortApplyConfiguration constructs a declarative configuration of the InstanceServicePort type for use with
// apply.
func InstanceServicePort() *InstanceServicePortApplyConfiguration {
	return &InstanceServicePortApplyConfiguration{}
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *InstanceServicePortApplyConfiguration) WithPort(value int32) *InstanceServicePortApplyConfiguration {
	b.InstancePortApplyConfiguration.Port = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *InstanceServicePortApplyConfiguration) WithProtocol(value corev1.Protocol) *InstanceServicePortApplyConfiguration {
	b.InstancePortApplyConfiguration.Protocol = &value
	return b
}

// WithNodePort sets the NodePort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodePort field is set to the value of the last call.
func (b *InstanceServicePortApplyConfiguration) WithNodePort(value int32) *InstanceServicePortApplyConfiguration {
	b.NodePort = &value
	return b
}
