baseURL = "/"
title = "GPUStack Operator"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.highlight]
    style = "github"
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.renderHooks.link]
      useEmbedded = "auto"

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "../docs"
    target = "content/docs"
    excludeFiles = ["README.md"]
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "data"
    target = "data"
