package settings

import (
	"gpustack.ai/gpustack/pkg/setting"
)

var settings = setting.Settings{}

// Indexer returns the index function of the settings,
// which can be used to index the settings in other packages.
func Indexer() setting.IndexFunc {
	return settings.Index
}

// the built-in settings for worker.
var (
	// Global.

	// ContainerRegistry is the registry to pull images, which is used in all built-in applications' deployment.
	ContainerRegistry = settings.NewEditable(
		"container-registry",
		"Indicates the registry to pull images.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
		setting.AllowContainerRegistry(),
	)
	// ContainerNamespace is the namespace to pull images, which is used in all built-in applications' deployment.
	ContainerNamespace = settings.NewEditable(
		"container-namespace",
		"Indicates the namespace to pull images.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
	)

	// Instance.

	// InstanceSSHServerImage is the image of the SSH server,
	// which is used when deploying Instances.
	InstanceSSHServerImage = settings.NewEditable(
		"instance-ssh-server-image",
		"Indicates the image of the SSH server, when deploying Instances.",
		setting.InitializeFromEnv("gpustack/ssh-server:v1.1.0"),
		setting.AllowContainerImageReference(),
	)

	// InstanceAccessStaticAddress is the access static address for all Instances,
	// which is used to access Instances.
	InstanceAccessStaticAddress = settings.NewEditable(
		"instance-access-static-address",
		"Indicates the access static address for all Instances. "+
			"If not set, the access address will be generated by host IPs.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
	)

	// InstanceAccessWildcardDNS is the wildcard DNS for all Instances,
	// which is used to generate the domain name for each Instance, like <instance-host-ip>.<wildcard-dns>.
	InstanceAccessWildcardDNS = settings.NewEditable(
		"instance-access-wildcard-dns",
		"Indicates the wildcard DNS for all Instances, like traefik.me. "+
			"Only effective if `instance-access-static-address` is not set.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
	)
)
