package settings

import (
	"gpustack.ai/gpustack/pkg/setting"
)

var settings = setting.Settings{}

// Indexer returns the index function of the settings,
// which can be used to index the settings in other packages.
func Indexer() setting.IndexFunc {
	return settings.Index
}

// the built-in settings for worker.
var (
	// Global.

	// ContainerRegistry is the registry to pull images, which is used in all built-in applications' deployment.
	ContainerRegistry = settings.NewEditable(
		"container-registry",
		"Indicates the registry to pull images.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
		setting.AllowContainerRegistry(),
	)

	// ContainerNamespace is the namespace to pull images, which is used in all built-in applications' deployment.
	ContainerNamespace = settings.NewEditable(
		"container-namespace",
		"Indicates the namespace to pull images.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
	)

	// ImagePullSecrets is the image pull secret for pulling images, which is used in all built-in applications' deployment.
	ImagePullSecrets = settings.NewEditable(
		"image-pull-secrets",
		"Indicates the image pull secret for pulling images.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
	)

	// ImagePullPolicy is the image pull policy for pulling images, which is used in all built-in applications' deployment.
	ImagePullPolicy = settings.NewEditable(
		"image-pull-policy",
		"Indicates the image pull policy for pulling images.",
		setting.InitializeFromEnv("IfNotPresent"),
		setting.AllowBlank(),
	)

	// Instance.

	// InstanceGeneralResourcesOvercommit indicates to overcommit instance general resources or not,
	// which is used when deploying Instances.
	InstanceGeneralResourcesOvercommit = settings.NewEditable(
		"instance-general-resources-overcommit",
		"Indicates to overcommit instance general resources or not. "+
			"With this enabled, normal instance types will request 800m(CPU)/128Mi(RAM) per unit and one-eight local storage, "+
			"acceleratable instances type will request 100m(CPU)/128Mi(RAM) per unit and one-eight local storage. "+
			"For example, an acceleratable instance type defines 1C/4Gi unit resources and 128Gi local storage,"+
			"when requesting 2 accelerators and 64Gi local storage of this type, "+
			"then resulting resource request will be 200m(CPU)/256Mi(RAM) and 8Gi local storage.",
		setting.InitializeFromEnv("true"),
		setting.AllowBool(),
	)

	// InstanceSSHServerImage is the image of the SSH server,
	// which is used when deploying Instances.
	InstanceSSHServerImage = settings.NewEditable(
		"instance-ssh-server-image",
		"Indicates the image of the SSH server, when deploying Instances.",
		setting.InitializeFromEnv("gpustack/ssh-server:v1.3.0"),
		setting.AllowContainerImageReference(),
	)

	// InstanceAccessStaticAddress is the access static address for all Instances,
	// which is used to access Instances.
	InstanceAccessStaticAddress = settings.NewEditable(
		"instance-access-static-address",
		"Indicates the access static address for all Instances. "+
			"If not set, the access address will be generated by host IPs.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
	)

	// InstanceAccessWildcardDNS is the wildcard DNS for all Instances,
	// which is used to generate the domain name for each Instance, like <instance-host-ip>.<wildcard-dns>.
	InstanceAccessWildcardDNS = settings.NewEditable(
		"instance-access-wildcard-dns",
		"Indicates the wildcard DNS for all Instances, like traefik.me. "+
			"Only effective if `instance-access-static-address` is not set.",
		setting.InitializeFromEnv(),
		setting.AllowBlank(),
	)

	// InstancePrivilegedAllowed indicates to allow Instances to request privileged mode,
	// which escapes the container boundary and exposes the node's devices and kernel surface.
	// Enforced when creating an Instance only: turning it off never blocks an existing
	// Instance from being updated, edited while stopped, or restarted.
	InstancePrivilegedAllowed = settings.NewEditable(
		"instance-privileged-allowed",
		"Indicates to allow Instances to request privileged mode. "+
			"Enforced when creating an Instance only, "+
			"so disabling it never blocks an existing Instance from being updated or restarted.",
		setting.InitializeFromEnv("false"),
		setting.AllowBool(),
	)

	// InstanceHostPathVolumeAllowed indicates to allow Instances to mount hostPath volumes,
	// which reaches the node's filesystem. It is separate from InstancePrivilegedAllowed
	// because it grants strictly less: the filesystem, but not the node's devices or kernel.
	// Enforced when creating an Instance only, like InstancePrivilegedAllowed.
	InstanceHostPathVolumeAllowed = settings.NewEditable(
		"instance-host-path-volume-allowed",
		"Indicates to allow Instances to mount hostPath volumes. "+
			"Enforced when creating an Instance only, "+
			"so disabling it never blocks an existing Instance from being updated or restarted.",
		setting.InitializeFromEnv("false"),
		setting.AllowBool(),
	)

	// InstanceType.

	// NodeManagementManual indicates to skip auto-managing nodes.
	// When false (default) the operator auto-injects `gpustack.ai/managed=true` to
	// onboard discovered nodes; when true an administrator must label nodes manually.
	NodeManagementManual = settings.NewEditable(
		"node-management-manual",
		"Indicates to skip auto-managing nodes. "+
			"When false (default), the operator auto-onboards discovered nodes by injecting the managed label; "+
			"when true, an administrator must opt nodes in manually.",
		setting.InitializeFromEnv("false"),
		setting.AllowBool(),
	)

	// InstanceTypeMixedOnNode indicates whether one node may surface both an
	// accelerator (GPU) and a general (CPU-only) InstanceType.
	// When true (default, current behavior) a node is summarized into every type it
	// can serve; when false a node with accelerators is summarized only as a GPU
	// InstanceType and a CPU-only node only as a general one.
	InstanceTypeMixedOnNode = settings.NewEditable(
		"instance-type-mixed-on-node",
		"Indicates whether one node may surface both a GPU and a CPU-only InstanceType. "+
			"When true (default), a node is summarized into every type it can serve; "+
			"when false, a node with accelerators yields only a GPU InstanceType and a CPU-only node only a general one.",
		setting.InitializeFromEnv("true"),
		setting.AllowBool(),
	)

	// InstanceTypeDerivedFromNode indicates whether the operator auto-derives the
	// InstanceType (and its backing ClusterQueue) from node hardware.
	// When true (default, current behavior) the operator derives both; when false it
	// only aligns the ResourceFlavor and the administrator defines the ClusterQueue
	// via the InstanceType API.
	InstanceTypeDerivedFromNode = settings.NewEditable(
		"instance-type-derived-from-node",
		"Indicates whether the operator auto-derives the InstanceType and its backing ClusterQueue from node hardware. "+
			"When true (default), the operator derives both; "+
			"when false, it only aligns the ResourceFlavor and the administrator defines the ClusterQueue via the InstanceType API.",
		setting.InitializeFromEnv("true"),
		setting.AllowBool(),
	)

	// InstanceTypeDrainWhenNoFlavors indicates whether a ClusterQueue whose pool has lost
	// all its ResourceFlavors is drained (HoldAndDrain) before its resource groups are
	// emptied. When true (default) the queue is drained first so admitted workloads are
	// evicted; when false the operator waits for the reservations to clear on their own,
	// then empties without draining. Either way the resource groups are emptied only once
	// all reservations are zero, so Kueue's counters never go negative.
	InstanceTypeDrainWhenNoFlavors = settings.NewEditable(
		"instance-type-drain-when-no-flavors",
		"Indicates whether a ClusterQueue whose pool lost all ResourceFlavors is drained "+
			"(HoldAndDrain) before its resource groups are emptied. When true (default), it is "+
			"drained first; when false, the operator waits for reservations to clear, then empties.",
		setting.InitializeFromEnv("true"),
		setting.AllowBool(),
	)

	// InstanceTypeAwareCPUManufacturer governs whether the derived ClusterQueue/InstanceType/
	// InstanceTypeFlavor aggregation layer treats the CPU manufacturer as a discriminator. When
	// false (default) non-accelerated flavors collapse into one generic pool per os/arch and
	// accelerated flavors pool per accelerator (CPU ignored); when true every pool splits by the
	// CPU key. It never changes a ResourceFlavor's name or labels — flavors are always the finest
	// grain — and additionally gates the cpuDetail note on an accelerated flavor.
	InstanceTypeAwareCPUManufacturer = settings.NewEditable(
		"instance-type-aware-cpu-manufacturer",
		"Indicates whether the derived ClusterQueue/InstanceType/InstanceTypeFlavor split by CPU "+
			"manufacturer. When false (default), non-accelerated flavors collapse into one generic pool "+
			"per os/arch and accelerated flavors pool per accelerator; when true, every pool splits by "+
			"the CPU manufacturer.",
		setting.InitializeFromEnv("false"),
		setting.AllowBool(),
	)
)
