// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1beta2

import (
	context "context"
	time "time"

	internalinterfaces "gpustack.ai/gpustack/pkg/kubeclients/informers/internalinterfaces"
	kubernetes "gpustack.ai/gpustack/pkg/kubeclients/kubernetes"
	kueuev1beta2 "gpustack.ai/gpustack/pkg/kubeclients/listers/kueue/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apiskueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// LocalQueueInformer provides access to a shared informer and lister for
// LocalQueues.
type LocalQueueInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kueuev1beta2.LocalQueueLister
}

type localQueueInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLocalQueueInformer constructs a new informer for LocalQueue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLocalQueueInformer(client kubernetes.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLocalQueueInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredLocalQueueInformer constructs a new informer for LocalQueue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLocalQueueInformer(client kubernetes.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KueueV1beta2().LocalQueues(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KueueV1beta2().LocalQueues(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KueueV1beta2().LocalQueues(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KueueV1beta2().LocalQueues(namespace).Watch(ctx, options)
			},
		}, client),
		&apiskueuev1beta2.LocalQueue{},
		resyncPeriod,
		indexers,
	)
}

func (f *localQueueInformer) defaultInformer(client kubernetes.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLocalQueueInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *localQueueInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiskueuev1beta2.LocalQueue{}, f.defaultInformer)
}

func (f *localQueueInformer) Lister() kueuev1beta2.LocalQueueLister {
	return kueuev1beta2.NewLocalQueueLister(f.Informer().GetIndexer())
}
