// Code generated by api. DO NOT EDIT.

package v1

import (
	serverv1 "gpustack.ai/gpustack/api/server/v1"
)

// SubjectSpecApplyConfiguration represents a declarative configuration of the SubjectSpec type for use
// with apply.
//
// SubjectSpec defines the desired state of Subject.
type SubjectSpecApplyConfiguration struct {
	// Provider is the name of subject provider who provides this subject,
	// which is immutable.
	Provider *string `json:"provider,omitempty"`
	// Role is the role of the subject.
	Role *serverv1.SubjectRole `json:"role,omitempty"`
	// Email is the email of the subject.
	Email *string `json:"email,omitempty"`
	// DisplayName is the display name of the subject.
	DisplayName *string `json:"displayName,omitempty"`
	// Description is the description of the subject.
	Description *string `json:"description,omitempty"`
	// Groups is the groups that the subject belongs to.
	Groups []string `json:"groups,omitempty"`
	// Credential is the credential of the subject,
	// it is provided as a write-only input field.
	Credential *string `json:"credential,omitempty"`
}

// SubjectSpecApplyConfiguration constructs a declarative configuration of the SubjectSpec type for use with
// apply.
func SubjectSpec() *SubjectSpecApplyConfiguration {
	return &SubjectSpecApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *SubjectSpecApplyConfiguration) WithProvider(value string) *SubjectSpecApplyConfiguration {
	b.Provider = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *SubjectSpecApplyConfiguration) WithRole(value serverv1.SubjectRole) *SubjectSpecApplyConfiguration {
	b.Role = &value
	return b
}

// WithEmail sets the Email field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Email field is set to the value of the last call.
func (b *SubjectSpecApplyConfiguration) WithEmail(value string) *SubjectSpecApplyConfiguration {
	b.Email = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *SubjectSpecApplyConfiguration) WithDisplayName(value string) *SubjectSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *SubjectSpecApplyConfiguration) WithDescription(value string) *SubjectSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *SubjectSpecApplyConfiguration) WithGroups(values ...string) *SubjectSpecApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithCredential sets the Credential field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Credential field is set to the value of the last call.
func (b *SubjectSpecApplyConfiguration) WithCredential(value string) *SubjectSpecApplyConfiguration {
	b.Credential = &value
	return b
}
