// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	kueuev1beta2 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/kueue/v1beta2"
	typedkueuev1beta2 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/kueue/v1beta2"
	gentype "k8s.io/client-go/gentype"
	v1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// fakeProvisioningRequestConfigs implements ProvisioningRequestConfigInterface
type fakeProvisioningRequestConfigs struct {
	*gentype.FakeClientWithListAndApply[*v1beta2.ProvisioningRequestConfig, *v1beta2.ProvisioningRequestConfigList, *kueuev1beta2.ProvisioningRequestConfigApplyConfiguration]
	Fake *FakeKueueV1beta2
}

func newFakeProvisioningRequestConfigs(fake *FakeKueueV1beta2) typedkueuev1beta2.ProvisioningRequestConfigInterface {
	return &fakeProvisioningRequestConfigs{
		gentype.NewFakeClientWithListAndApply[*v1beta2.ProvisioningRequestConfig, *v1beta2.ProvisioningRequestConfigList, *kueuev1beta2.ProvisioningRequestConfigApplyConfiguration](
			fake.Fake,
			"",
			v1beta2.SchemeGroupVersion.WithResource("provisioningrequestconfigs"),
			v1beta2.SchemeGroupVersion.WithKind("ProvisioningRequestConfig"),
			func() *v1beta2.ProvisioningRequestConfig { return &v1beta2.ProvisioningRequestConfig{} },
			func() *v1beta2.ProvisioningRequestConfigList { return &v1beta2.ProvisioningRequestConfigList{} },
			func(dst, src *v1beta2.ProvisioningRequestConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta2.ProvisioningRequestConfigList) []*v1beta2.ProvisioningRequestConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta2.ProvisioningRequestConfigList, items []*v1beta2.ProvisioningRequestConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
