// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	kueuev1beta2 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/kueue/v1beta2"
	typedkueuev1beta2 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/kueue/v1beta2"
	gentype "k8s.io/client-go/gentype"
	v1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// fakeTopologies implements TopologyInterface
type fakeTopologies struct {
	*gentype.FakeClientWithListAndApply[*v1beta2.Topology, *v1beta2.TopologyList, *kueuev1beta2.TopologyApplyConfiguration]
	Fake *FakeKueueV1beta2
}

func newFakeTopologies(fake *FakeKueueV1beta2) typedkueuev1beta2.TopologyInterface {
	return &fakeTopologies{
		gentype.NewFakeClientWithListAndApply[*v1beta2.Topology, *v1beta2.TopologyList, *kueuev1beta2.TopologyApplyConfiguration](
			fake.Fake,
			"",
			v1beta2.SchemeGroupVersion.WithResource("topologies"),
			v1beta2.SchemeGroupVersion.WithKind("Topology"),
			func() *v1beta2.Topology { return &v1beta2.Topology{} },
			func() *v1beta2.TopologyList { return &v1beta2.TopologyList{} },
			func(dst, src *v1beta2.TopologyList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta2.TopologyList) []*v1beta2.Topology { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta2.TopologyList, items []*v1beta2.Topology) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
