provider:
  name: test
  params:
    modelFileName: medium.yaml
    generateResponseCode: 202
    topologyResponseCode: 200
engine:
  name: k8s

nodeSelector:
  node-role.kubernetes.io/control-plane: ""

nodeObserver:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  topograph:
    trigger:
      nodeSelector:
        kwok.x-k8s.io/node: "fake"

nodeDataBroker:
  enabled: false
