// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	resourcev1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/resource/v1"
	typedresourcev1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/resource/v1"
	v1 "k8s.io/api/resource/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDeviceClasses implements DeviceClassInterface
type fakeDeviceClasses struct {
	*gentype.FakeClientWithListAndApply[*v1.DeviceClass, *v1.DeviceClassList, *resourcev1.DeviceClassApplyConfiguration]
	Fake *FakeResourceV1
}

func newFakeDeviceClasses(fake *FakeResourceV1) typedresourcev1.DeviceClassInterface {
	return &fakeDeviceClasses{
		gentype.NewFakeClientWithListAndApply[*v1.DeviceClass, *v1.DeviceClassList, *resourcev1.DeviceClassApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("deviceclasses"),
			v1.SchemeGroupVersion.WithKind("DeviceClass"),
			func() *v1.DeviceClass { return &v1.DeviceClass{} },
			func() *v1.DeviceClassList { return &v1.DeviceClassList{} },
			func(dst, src *v1.DeviceClassList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DeviceClassList) []*v1.DeviceClass { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.DeviceClassList, items []*v1.DeviceClass) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
