// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	resourcev1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/resource/v1"
	typedresourcev1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/resource/v1"
	v1 "k8s.io/api/resource/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeResourceClaims implements ResourceClaimInterface
type fakeResourceClaims struct {
	*gentype.FakeClientWithListAndApply[*v1.ResourceClaim, *v1.ResourceClaimList, *resourcev1.ResourceClaimApplyConfiguration]
	Fake *FakeResourceV1
}

func newFakeResourceClaims(fake *FakeResourceV1, namespace string) typedresourcev1.ResourceClaimInterface {
	return &fakeResourceClaims{
		gentype.NewFakeClientWithListAndApply[*v1.ResourceClaim, *v1.ResourceClaimList, *resourcev1.ResourceClaimApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("resourceclaims"),
			v1.SchemeGroupVersion.WithKind("ResourceClaim"),
			func() *v1.ResourceClaim { return &v1.ResourceClaim{} },
			func() *v1.ResourceClaimList { return &v1.ResourceClaimList{} },
			func(dst, src *v1.ResourceClaimList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ResourceClaimList) []*v1.ResourceClaim { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ResourceClaimList, items []*v1.ResourceClaim) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
