apiVersion: v1
entries:
  gpustack-operator:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.7.1
    created: "2026-07-23T15:54:57.302525732Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 98c7128bce159aac8bb6be0e07bac5ac34784871553071a93f504bb71718c4d5
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.7.1.tgz
    version: 0.7.1
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.7.0
    created: "2026-07-21T12:45:37.041581772Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 9543d2900c8f30528660c6b3ce59cecb92f30cd941befd8b7f1a19f3b50c218b
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.7.0.tgz
    version: 0.7.0
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.6.6
    created: "2026-07-13T08:26:35.376591261Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 5eca20fe3194dc20709cbd85eeb8be706c7a9b5120ac38acb27a94c5855cf133
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.6.6.tgz
    version: 0.6.6
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.6.5
    created: "2026-07-10T11:45:14.382665994Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: e318d782e1a35550a6d0912daa556e18217348612419986f25ccca11928443cc
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.6.5.tgz
    version: 0.6.5
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.6.4
    created: "2026-07-09T14:24:04.75197032Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: fbb7dc8b086c2f22fd23ce6446e10247b779ed4d4affd18bb3c4d9a7d8dfadba
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.6.4.tgz
    version: 0.6.4
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.6.3
    created: "2026-07-09T03:02:12.926541182Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: fd9ad8b10030aef4ee6fdb06cd6870684ab2718f41259f8cc2048242e818dd04
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.29.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.6.3.tgz
    version: 0.6.3
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.6.2
    created: "2026-07-05T13:12:30.239019162Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 596be157d88e49c5c97a09300a59c002a693db61e5c7d17c1d93e2fee0a650ea
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.27.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.6.2.tgz
    version: 0.6.2
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.6.1
    created: "2026-07-03T08:14:25.059113979Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 1e034002c15fe9335ddf70011200c7f7b0cd16634ef95bd5e3313aabb89dcfa3
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.27.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.6.1.tgz
    version: 0.6.1
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.6.1-rc1
    created: "2026-07-03T07:09:02.877243965Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 5b6c7b39a03233717c50863b05829bb5726c1455c0fe6211a176373655718f36
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.27.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.6.1-rc1.tgz
    version: 0.6.1-rc1
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.6.0
    created: "2026-07-03T00:22:49.860115821Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 0825098c2601a88d900bcc0422cca518f3beb6bb8d1a11b261cf865c991b0df8
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.27.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.6.0.tgz
    version: 0.6.0
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.5.4
    created: "2026-07-09T08:34:53.106067836Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 06db41e9c9c42e168d539bc9a961c98cb97320eda401dbdde936fdfdec82f277
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.5.4.tgz
    version: 0.5.4
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.5.3
    created: "2026-06-21T05:49:55.394233515Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 914ac5533ca6b2a8d38dd651359c797141323126400592ddefdca1ce06ec2d46
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.27.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.5.3.tgz
    version: 0.5.3
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.5.2
    created: "2026-06-18T01:21:59.31238158Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: 2250a96dfd10b9d349e68535955567fad7f39dffdccb19a5321234b8998958ac
    home: https://github.com/gpustack/gpustack-operator
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack-operator
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.27.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    - https://github.com/gpustack/gpustack-operator
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.5.2.tgz
    version: 0.5.2
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.5.1
    created: "2026-06-17T00:29:33.790074052Z"
    description: A Kubernetes operator that turns raw node hardware into a Kueue-based
      scheduling chain for accelerators (GPU/NPU/TPU), built on Node Feature Discovery
      (NFD) and Kueue.
    digest: c5166c184dcf9dde7ec13010c07dd538e4a8fb79e51306eb3057f7a86c87286b
    home: https://github.com/gpustack/gpustack
    icon: https://raw.githubusercontent.com/gpustack/gpustack/main/docs/assets/logo.png
    keywords:
    - gpustack
    - operator
    - kueue
    - node-feature-discovery
    - gpu
    - npu
    - accelerator
    kubeVersion: '>=1.27.0-0'
    maintainers:
    - name: GPUStack Authors
      url: https://github.com/gpustack
    name: gpustack-operator
    sources:
    - https://github.com/gpustack/gpustack
    type: application
    urls:
    - https://gpustack.github.io/gpustack-operator/charts/gpustack-operator-0.5.1.tgz
    version: 0.5.1
generated: "2026-07-23T15:54:57.301501054Z"
