// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	flowcontrolv1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/flowcontrol/v1"
	typedflowcontrolv1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/flowcontrol/v1"
	v1 "k8s.io/api/flowcontrol/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakePriorityLevelConfigurations implements PriorityLevelConfigurationInterface
type fakePriorityLevelConfigurations struct {
	*gentype.FakeClientWithListAndApply[*v1.PriorityLevelConfiguration, *v1.PriorityLevelConfigurationList, *flowcontrolv1.PriorityLevelConfigurationApplyConfiguration]
	Fake *FakeFlowcontrolV1
}

func newFakePriorityLevelConfigurations(fake *FakeFlowcontrolV1) typedflowcontrolv1.PriorityLevelConfigurationInterface {
	return &fakePriorityLevelConfigurations{
		gentype.NewFakeClientWithListAndApply[*v1.PriorityLevelConfiguration, *v1.PriorityLevelConfigurationList, *flowcontrolv1.PriorityLevelConfigurationApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("prioritylevelconfigurations"),
			v1.SchemeGroupVersion.WithKind("PriorityLevelConfiguration"),
			func() *v1.PriorityLevelConfiguration { return &v1.PriorityLevelConfiguration{} },
			func() *v1.PriorityLevelConfigurationList { return &v1.PriorityLevelConfigurationList{} },
			func(dst, src *v1.PriorityLevelConfigurationList) { dst.ListMeta = src.ListMeta },
			func(list *v1.PriorityLevelConfigurationList) []*v1.PriorityLevelConfiguration {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.PriorityLevelConfigurationList, items []*v1.PriorityLevelConfiguration) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
