// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	resourcev1beta1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/resource/v1beta1"
	typedresourcev1beta1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/resource/v1beta1"
	v1beta1 "k8s.io/api/resource/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeResourceClaimTemplates implements ResourceClaimTemplateInterface
type fakeResourceClaimTemplates struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.ResourceClaimTemplate, *v1beta1.ResourceClaimTemplateList, *resourcev1beta1.ResourceClaimTemplateApplyConfiguration]
	Fake *FakeResourceV1beta1
}

func newFakeResourceClaimTemplates(fake *FakeResourceV1beta1, namespace string) typedresourcev1beta1.ResourceClaimTemplateInterface {
	return &fakeResourceClaimTemplates{
		gentype.NewFakeClientWithListAndApply[*v1beta1.ResourceClaimTemplate, *v1beta1.ResourceClaimTemplateList, *resourcev1beta1.ResourceClaimTemplateApplyConfiguration](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("resourceclaimtemplates"),
			v1beta1.SchemeGroupVersion.WithKind("ResourceClaimTemplate"),
			func() *v1beta1.ResourceClaimTemplate { return &v1beta1.ResourceClaimTemplate{} },
			func() *v1beta1.ResourceClaimTemplateList { return &v1beta1.ResourceClaimTemplateList{} },
			func(dst, src *v1beta1.ResourceClaimTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ResourceClaimTemplateList) []*v1beta1.ResourceClaimTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.ResourceClaimTemplateList, items []*v1beta1.ResourceClaimTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
