// Code generated by api. DO NOT EDIT.

package v1beta2

// MultiKueueClusterSpecApplyConfiguration represents a declarative configuration of the MultiKueueClusterSpec type for use
// with apply.
type MultiKueueClusterSpecApplyConfiguration struct {
	// clusterSource is the source to connect to the cluster.
	ClusterSource *ClusterSourceApplyConfiguration `json:"clusterSource,omitempty"`
}

// MultiKueueClusterSpecApplyConfiguration constructs a declarative configuration of the MultiKueueClusterSpec type for use with
// apply.
func MultiKueueClusterSpec() *MultiKueueClusterSpecApplyConfiguration {
	return &MultiKueueClusterSpecApplyConfiguration{}
}

// WithClusterSource sets the ClusterSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterSource field is set to the value of the last call.
func (b *MultiKueueClusterSpecApplyConfiguration) WithClusterSource(value *ClusterSourceApplyConfiguration) *MultiKueueClusterSpecApplyConfiguration {
	b.ClusterSource = value
	return b
}
