// Code generated by api. DO NOT EDIT.

package v1beta2

// TopologyAssignmentSliceApplyConfiguration represents a declarative configuration of the TopologyAssignmentSlice type for use
// with apply.
type TopologyAssignmentSliceApplyConfiguration struct {
	// domainCount is the number of domains covered by this slice.
	DomainCount *int32 `json:"domainCount,omitempty"`
	// valuesPerLevel has one entry for each of the Levels specified in the TopologyAssignment.
	// The entry corresponding to a particular level specifies the placement of pods at that level.
	ValuesPerLevel []TopologyAssignmentSliceLevelValuesApplyConfiguration `json:"valuesPerLevel,omitempty"`
	// podCounts specifies the number of pods allocated per each domain.
	PodCounts *TopologyAssignmentSlicePodCountsApplyConfiguration `json:"podCounts,omitempty"`
}

// TopologyAssignmentSliceApplyConfiguration constructs a declarative configuration of the TopologyAssignmentSlice type for use with
// apply.
func TopologyAssignmentSlice() *TopologyAssignmentSliceApplyConfiguration {
	return &TopologyAssignmentSliceApplyConfiguration{}
}

// WithDomainCount sets the DomainCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainCount field is set to the value of the last call.
func (b *TopologyAssignmentSliceApplyConfiguration) WithDomainCount(value int32) *TopologyAssignmentSliceApplyConfiguration {
	b.DomainCount = &value
	return b
}

// WithValuesPerLevel adds the given value to the ValuesPerLevel field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ValuesPerLevel field.
func (b *TopologyAssignmentSliceApplyConfiguration) WithValuesPerLevel(values ...*TopologyAssignmentSliceLevelValuesApplyConfiguration) *TopologyAssignmentSliceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithValuesPerLevel")
		}
		b.ValuesPerLevel = append(b.ValuesPerLevel, *values[i])
	}
	return b
}

// WithPodCounts sets the PodCounts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodCounts field is set to the value of the last call.
func (b *TopologyAssignmentSliceApplyConfiguration) WithPodCounts(value *TopologyAssignmentSlicePodCountsApplyConfiguration) *TopologyAssignmentSliceApplyConfiguration {
	b.PodCounts = value
	return b
}
