// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	autoscalingv1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/autoscaling/v1"
	typedautoscalingv1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/autoscaling/v1"
	v1 "k8s.io/api/autoscaling/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHorizontalPodAutoscalers implements HorizontalPodAutoscalerInterface
type fakeHorizontalPodAutoscalers struct {
	*gentype.FakeClientWithListAndApply[*v1.HorizontalPodAutoscaler, *v1.HorizontalPodAutoscalerList, *autoscalingv1.HorizontalPodAutoscalerApplyConfiguration]
	Fake *FakeAutoscalingV1
}

func newFakeHorizontalPodAutoscalers(fake *FakeAutoscalingV1, namespace string) typedautoscalingv1.HorizontalPodAutoscalerInterface {
	return &fakeHorizontalPodAutoscalers{
		gentype.NewFakeClientWithListAndApply[*v1.HorizontalPodAutoscaler, *v1.HorizontalPodAutoscalerList, *autoscalingv1.HorizontalPodAutoscalerApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("horizontalpodautoscalers"),
			v1.SchemeGroupVersion.WithKind("HorizontalPodAutoscaler"),
			func() *v1.HorizontalPodAutoscaler { return &v1.HorizontalPodAutoscaler{} },
			func() *v1.HorizontalPodAutoscalerList { return &v1.HorizontalPodAutoscalerList{} },
			func(dst, src *v1.HorizontalPodAutoscalerList) { dst.ListMeta = src.ListMeta },
			func(list *v1.HorizontalPodAutoscalerList) []*v1.HorizontalPodAutoscaler {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.HorizontalPodAutoscalerList, items []*v1.HorizontalPodAutoscaler) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
