// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1

// DevicesListerExpansion allows custom methods to be added to
// DevicesLister.
type DevicesListerExpansion interface{}

// InstanceListerExpansion allows custom methods to be added to
// InstanceLister.
type InstanceListerExpansion interface{}

// InstanceNamespaceListerExpansion allows custom methods to be added to
// InstanceNamespaceLister.
type InstanceNamespaceListerExpansion interface{}

// InstanceImagePullSecretListerExpansion allows custom methods to be added to
// InstanceImagePullSecretLister.
type InstanceImagePullSecretListerExpansion interface{}

// InstanceImagePullSecretNamespaceListerExpansion allows custom methods to be added to
// InstanceImagePullSecretNamespaceLister.
type InstanceImagePullSecretNamespaceListerExpansion interface{}

// InstancePersistentVolumeListerExpansion allows custom methods to be added to
// InstancePersistentVolumeLister.
type InstancePersistentVolumeListerExpansion interface{}

// InstancePersistentVolumeNamespaceListerExpansion allows custom methods to be added to
// InstancePersistentVolumeNamespaceLister.
type InstancePersistentVolumeNamespaceListerExpansion interface{}

// InstancePersistentVolumeTypeListerExpansion allows custom methods to be added to
// InstancePersistentVolumeTypeLister.
type InstancePersistentVolumeTypeListerExpansion interface{}

// InstancePersistentVolumeTypeNamespaceListerExpansion allows custom methods to be added to
// InstancePersistentVolumeTypeNamespaceLister.
type InstancePersistentVolumeTypeNamespaceListerExpansion interface{}

// InstanceSSHPublicKeyListerExpansion allows custom methods to be added to
// InstanceSSHPublicKeyLister.
type InstanceSSHPublicKeyListerExpansion interface{}

// InstanceSSHPublicKeyNamespaceListerExpansion allows custom methods to be added to
// InstanceSSHPublicKeyNamespaceLister.
type InstanceSSHPublicKeyNamespaceListerExpansion interface{}

// InstanceTypeListerExpansion allows custom methods to be added to
// InstanceTypeLister.
type InstanceTypeListerExpansion interface{}
