// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	v1 "gpustack.ai/gpustack/api/worker/v1"
	workerv1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/worker/v1"
	typedworkerv1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/worker/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeInstances implements InstanceInterface
type fakeInstances struct {
	*gentype.FakeClientWithListAndApply[*v1.Instance, *v1.InstanceList, *workerv1.InstanceApplyConfiguration]
	Fake *FakeWorkerV1
}

func newFakeInstances(fake *FakeWorkerV1, namespace string) typedworkerv1.InstanceInterface {
	return &fakeInstances{
		gentype.NewFakeClientWithListAndApply[*v1.Instance, *v1.InstanceList, *workerv1.InstanceApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("instances"),
			v1.SchemeGroupVersion.WithKind("Instance"),
			func() *v1.Instance { return &v1.Instance{} },
			func() *v1.InstanceList { return &v1.InstanceList{} },
			func(dst, src *v1.InstanceList) { dst.ListMeta = src.ListMeta },
			func(list *v1.InstanceList) []*v1.Instance { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.InstanceList, items []*v1.Instance) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
