// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	v1 "gpustack.ai/gpustack/api/worker/v1"
	workerv1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/worker/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNodeModelStores implements NodeModelStoreInterface
type fakeNodeModelStores struct {
	*gentype.FakeClientWithList[*v1.NodeModelStore, *v1.NodeModelStoreList]
	Fake *FakeWorkerV1
}

func newFakeNodeModelStores(fake *FakeWorkerV1) workerv1.NodeModelStoreInterface {
	return &fakeNodeModelStores{
		gentype.NewFakeClientWithList[*v1.NodeModelStore, *v1.NodeModelStoreList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("nodemodelstores"),
			v1.SchemeGroupVersion.WithKind("NodeModelStore"),
			func() *v1.NodeModelStore { return &v1.NodeModelStore{} },
			func() *v1.NodeModelStoreList { return &v1.NodeModelStoreList{} },
			func(dst, src *v1.NodeModelStoreList) { dst.ListMeta = src.ListMeta },
			func(list *v1.NodeModelStoreList) []*v1.NodeModelStore { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.NodeModelStoreList, items []*v1.NodeModelStore) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
