// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	v1beta2 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/resource/v1beta2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeResourceV1beta2 struct {
	*testing.Fake
}

func (c *FakeResourceV1beta2) DeviceClasses() v1beta2.DeviceClassInterface {
	return newFakeDeviceClasses(c)
}

func (c *FakeResourceV1beta2) ResourceClaims(namespace string) v1beta2.ResourceClaimInterface {
	return newFakeResourceClaims(c, namespace)
}

func (c *FakeResourceV1beta2) ResourceClaimTemplates(namespace string) v1beta2.ResourceClaimTemplateInterface {
	return newFakeResourceClaimTemplates(c, namespace)
}

func (c *FakeResourceV1beta2) ResourceSlices() v1beta2.ResourceSliceInterface {
	return newFakeResourceSlices(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeResourceV1beta2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
