// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	v1alpha1 "gpustack.ai/gpustack/api/worker/v1alpha1"
	workerv1alpha1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/worker/v1alpha1"
	typedworkerv1alpha1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/worker/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNodeModelStores implements NodeModelStoreInterface
type fakeNodeModelStores struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NodeModelStore, *v1alpha1.NodeModelStoreList, *workerv1alpha1.NodeModelStoreApplyConfiguration]
	Fake *FakeWorkerV1alpha1
}

func newFakeNodeModelStores(fake *FakeWorkerV1alpha1) typedworkerv1alpha1.NodeModelStoreInterface {
	return &fakeNodeModelStores{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NodeModelStore, *v1alpha1.NodeModelStoreList, *workerv1alpha1.NodeModelStoreApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("nodemodelstores"),
			v1alpha1.SchemeGroupVersion.WithKind("NodeModelStore"),
			func() *v1alpha1.NodeModelStore { return &v1alpha1.NodeModelStore{} },
			func() *v1alpha1.NodeModelStoreList { return &v1alpha1.NodeModelStoreList{} },
			func(dst, src *v1alpha1.NodeModelStoreList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NodeModelStoreList) []*v1alpha1.NodeModelStore {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.NodeModelStoreList, items []*v1alpha1.NodeModelStore) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
