// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	v1alpha1 "gpustack.ai/gpustack/api/worker/v1alpha1"
	workerv1alpha1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/worker/v1alpha1"
	typedworkerv1alpha1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/worker/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeInstances implements InstanceInterface
type fakeInstances struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Instance, *v1alpha1.InstanceList, *workerv1alpha1.InstanceApplyConfiguration]
	Fake *FakeWorkerV1alpha1
}

func newFakeInstances(fake *FakeWorkerV1alpha1, namespace string) typedworkerv1alpha1.InstanceInterface {
	return &fakeInstances{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Instance, *v1alpha1.InstanceList, *workerv1alpha1.InstanceApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("instances"),
			v1alpha1.SchemeGroupVersion.WithKind("Instance"),
			func() *v1alpha1.Instance { return &v1alpha1.Instance{} },
			func() *v1alpha1.InstanceList { return &v1alpha1.InstanceList{} },
			func(dst, src *v1alpha1.InstanceList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.InstanceList) []*v1alpha1.Instance { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.InstanceList, items []*v1alpha1.Instance) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
