// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1alpha1

// DevicesListerExpansion allows custom methods to be added to
// DevicesLister.
type DevicesListerExpansion interface{}

// InstanceListerExpansion allows custom methods to be added to
// InstanceLister.
type InstanceListerExpansion interface{}

// InstanceNamespaceListerExpansion allows custom methods to be added to
// InstanceNamespaceLister.
type InstanceNamespaceListerExpansion interface{}

// InstanceTypeListerExpansion allows custom methods to be added to
// InstanceTypeLister.
type InstanceTypeListerExpansion interface{}

// KVCacheBackendListerExpansion allows custom methods to be added to
// KVCacheBackendLister.
type KVCacheBackendListerExpansion interface{}
