// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	workerv1alpha1 "gpustack.ai/gpustack/api/worker/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KVCacheBackendLister helps list KVCacheBackends.
// All objects returned here must be treated as read-only.
type KVCacheBackendLister interface {
	// List lists all KVCacheBackends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workerv1alpha1.KVCacheBackend, err error)
	// Get retrieves the KVCacheBackend from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workerv1alpha1.KVCacheBackend, error)
	KVCacheBackendListerExpansion
}

// kVCacheBackendLister implements the KVCacheBackendLister interface.
type kVCacheBackendLister struct {
	listers.ResourceIndexer[*workerv1alpha1.KVCacheBackend]
}

// NewKVCacheBackendLister returns a new KVCacheBackendLister.
func NewKVCacheBackendLister(indexer cache.Indexer) KVCacheBackendLister {
	return &kVCacheBackendLister{listers.New[*workerv1alpha1.KVCacheBackend](indexer, workerv1alpha1.Resource("kvcachebackend"))}
}
