// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	workerv1alpha1 "gpustack.ai/gpustack/api/worker/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ModelArtifactLister helps list ModelArtifacts.
// All objects returned here must be treated as read-only.
type ModelArtifactLister interface {
	// List lists all ModelArtifacts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workerv1alpha1.ModelArtifact, err error)
	// ModelArtifacts returns an object that can list and get ModelArtifacts.
	ModelArtifacts(namespace string) ModelArtifactNamespaceLister
	ModelArtifactListerExpansion
}

// modelArtifactLister implements the ModelArtifactLister interface.
type modelArtifactLister struct {
	listers.ResourceIndexer[*workerv1alpha1.ModelArtifact]
}

// NewModelArtifactLister returns a new ModelArtifactLister.
func NewModelArtifactLister(indexer cache.Indexer) ModelArtifactLister {
	return &modelArtifactLister{listers.New[*workerv1alpha1.ModelArtifact](indexer, workerv1alpha1.Resource("modelartifact"))}
}

// ModelArtifacts returns an object that can list and get ModelArtifacts.
func (s *modelArtifactLister) ModelArtifacts(namespace string) ModelArtifactNamespaceLister {
	return modelArtifactNamespaceLister{listers.NewNamespaced[*workerv1alpha1.ModelArtifact](s.ResourceIndexer, namespace)}
}

// ModelArtifactNamespaceLister helps list and get ModelArtifacts.
// All objects returned here must be treated as read-only.
type ModelArtifactNamespaceLister interface {
	// List lists all ModelArtifacts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workerv1alpha1.ModelArtifact, err error)
	// Get retrieves the ModelArtifact from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workerv1alpha1.ModelArtifact, error)
	ModelArtifactNamespaceListerExpansion
}

// modelArtifactNamespaceLister implements the ModelArtifactNamespaceLister
// interface.
type modelArtifactNamespaceLister struct {
	listers.ResourceIndexer[*workerv1alpha1.ModelArtifact]
}
