// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1alpha2

import (
	internalinterfaces "gpustack.ai/gpustack/pkg/kubeclients/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// LeaseCandidates returns a LeaseCandidateInformer.
	LeaseCandidates() LeaseCandidateInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// LeaseCandidates returns a LeaseCandidateInformer.
func (v *version) LeaseCandidates() LeaseCandidateInformer {
	return &leaseCandidateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
