// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
//   The above copyright notice and this permission notice shall be included in
//   all copies or substantial portions of the Software.
//
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//   THE SOFTWARE.

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package rsmi

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#cgo darwin LDFLAGS: -Wl,-undefined,dynamic_lookup
#cgo CFLAGS: -w
#include "rocm_smi.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// rsmiInit function as declared in rsmi/rocm_smi.h:1611
func rsmiInit(InitFlags uint64) Return {
	cInitFlags, cInitFlagsAllocMap := (C.uint64_t)(InitFlags), cgoAllocsUnknown
	__ret := C.rsmi_init(cInitFlags)
	runtime.KeepAlive(cInitFlagsAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiShutDown function as declared in rsmi/rocm_smi.h:1618
func rsmiShutDown() Return {
	__ret := C.rsmi_shut_down()
	__v := (Return)(__ret)
	return __v
}

// rsmiDriverStatus function as declared in rsmi/rocm_smi.h:1625
func rsmiDriverStatus(State *DriverState) Return {
	cState, cStateAllocMap := (*C.rsmi_driver_state_t)(unsafe.Pointer(State)), cgoAllocsUnknown
	__ret := C.rsmi_driver_status(cState)
	runtime.KeepAlive(cStateAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiNumMonitorDevices function as declared in rsmi/rocm_smi.h:1646
func rsmiNumMonitorDevices(NumDevices *uint32) Return {
	cNumDevices, cNumDevicesAllocMap := (*C.uint32_t)(unsafe.Pointer(NumDevices)), cgoAllocsUnknown
	__ret := C.rsmi_num_monitor_devices(cNumDevices)
	runtime.KeepAlive(cNumDevicesAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiNumNicMonitorDevices function as declared in rsmi/rocm_smi.h:1660
func rsmiNumNicMonitorDevices(NumDevices *uint32) Return {
	cNumDevices, cNumDevicesAllocMap := (*C.uint32_t)(unsafe.Pointer(NumDevices)), cgoAllocsUnknown
	__ret := C.rsmi_num_nic_monitor_devices(cNumDevices)
	runtime.KeepAlive(cNumDevicesAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiNumSwitchMonitorDevices function as declared in rsmi/rocm_smi.h:1674
func rsmiNumSwitchMonitorDevices(NumDevices *uint32) Return {
	cNumDevices, cNumDevicesAllocMap := (*C.uint32_t)(unsafe.Pointer(NumDevices)), cgoAllocsUnknown
	__ret := C.rsmi_num_switch_monitor_devices(cNumDevices)
	runtime.KeepAlive(cNumDevicesAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevIdGet function as declared in rsmi/rocm_smi.h:1703
func rsmiDevIdGet(DvInd uint32, Id *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_id_get(cDvInd, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevRevisionGet function as declared in rsmi/rocm_smi.h:1719
func rsmiDevRevisionGet(DvInd uint32, Revision *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cRevision, cRevisionAllocMap := (*C.uint16_t)(unsafe.Pointer(Revision)), cgoAllocsUnknown
	__ret := C.rsmi_dev_revision_get(cDvInd, cRevision)
	runtime.KeepAlive(cRevisionAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSkuGet function as declared in rsmi/rocm_smi.h:1745
func rsmiDevSkuGet(DvInd uint32, Sku *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSku, cSkuAllocMap := (*C.uint16_t)(unsafe.Pointer(Sku)), cgoAllocsUnknown
	__ret := C.rsmi_dev_sku_get(cDvInd, cSku)
	runtime.KeepAlive(cSkuAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevVendorIdGet function as declared in rsmi/rocm_smi.h:1770
func rsmiDevVendorIdGet(DvInd uint32, Id *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_vendor_id_get(cDvInd, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPcieVendorNameGet function as declared in rsmi/rocm_smi.h:1806
func rsmiDevPcieVendorNameGet(DvInd uint32, Name *byte, Len uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cName, cNameAllocMap := (*C.char)(unsafe.Pointer(Name)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.size_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_pcie_vendor_name_get(cDvInd, cName, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevNameGet function as declared in rsmi/rocm_smi.h:1842
func rsmiDevNameGet(DvInd uint32, Name *byte, Len uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cName, cNameAllocMap := (*C.char)(unsafe.Pointer(Name)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.size_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_name_get(cDvInd, cName, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevBrandGet function as declared in rsmi/rocm_smi.h:1876
func rsmiDevBrandGet(DvInd uint32, Brand *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBrand, cBrandAllocMap := (*C.char)(unsafe.Pointer(Brand)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_brand_get(cDvInd, cBrand, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cBrandAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevVendorNameGet function as declared in rsmi/rocm_smi.h:1912
func rsmiDevVendorNameGet(DvInd uint32, Name *byte, Len uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cName, cNameAllocMap := (*C.char)(unsafe.Pointer(Name)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.size_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vendor_name_get(cDvInd, cName, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevVramVendorGet function as declared in rsmi/rocm_smi.h:1936
func rsmiDevVramVendorGet(DvInd uint32, Brand *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBrand, cBrandAllocMap := (*C.char)(unsafe.Pointer(Brand)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vram_vendor_get(cDvInd, cBrand, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cBrandAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPcieSlotTypeGet function as declared in rsmi/rocm_smi.h:1954
func rsmiDevPcieSlotTypeGet(DvInd uint32, Type *PcieSlotType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cType, cTypeAllocMap := (*C.rsmi_pcie_slot_type_t)(unsafe.Pointer(Type)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pcie_slot_type_get(cDvInd, cType)
	runtime.KeepAlive(cTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSerialNumberGet function as declared in rsmi/rocm_smi.h:1984
func rsmiDevSerialNumberGet(DvInd uint32, SerialNum *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSerialNum, cSerialNumAllocMap := (*C.char)(unsafe.Pointer(SerialNum)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_serial_number_get(cDvInd, cSerialNum, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cSerialNumAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSubsystemIdGet function as declared in rsmi/rocm_smi.h:2008
func rsmiDevSubsystemIdGet(DvInd uint32, Id *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_id_get(cDvInd, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSubsystemNameGet function as declared in rsmi/rocm_smi.h:2044
func rsmiDevSubsystemNameGet(DvInd uint32, Name *byte, Len uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cName, cNameAllocMap := (*C.char)(unsafe.Pointer(Name)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.size_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_name_get(cDvInd, cName, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevDrmRenderMinorGet function as declared in rsmi/rocm_smi.h:2063
func rsmiDevDrmRenderMinorGet(DvInd uint32, Minor *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cMinor, cMinorAllocMap := (*C.uint32_t)(unsafe.Pointer(Minor)), cgoAllocsUnknown
	__ret := C.rsmi_dev_drm_render_minor_get(cDvInd, cMinor)
	runtime.KeepAlive(cMinorAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSubsystemVendorIdGet function as declared in rsmi/rocm_smi.h:2087
func rsmiDevSubsystemVendorIdGet(DvInd uint32, Id *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_vendor_id_get(cDvInd, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevUniqueIdGet function as declared in rsmi/rocm_smi.h:2110
func rsmiDevUniqueIdGet(DvInd uint32, Id *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint64_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_unique_id_get(cDvInd, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevAsicSerialGet function as declared in rsmi/rocm_smi.h:2133
func rsmiDevAsicSerialGet(DvInd uint32, Id *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint64_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_asic_serial_get(cDvInd, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevXgmiPhysicalIdGet function as declared in rsmi/rocm_smi.h:2149
func rsmiDevXgmiPhysicalIdGet(DvInd uint32, Id *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_physical_id_get(cDvInd, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevXgmiPortNumGet function as declared in rsmi/rocm_smi.h:2169
func rsmiDevXgmiPortNumGet(DvInd uint32, Count *uint32, LinkToDstGpu *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cCount, cCountAllocMap := (*C.uint32_t)(unsafe.Pointer(Count)), cgoAllocsUnknown
	cLinkToDstGpu, cLinkToDstGpuAllocMap := (*C.uint16_t)(unsafe.Pointer(LinkToDstGpu)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_port_num_get(cDvInd, cCount, cLinkToDstGpu)
	runtime.KeepAlive(cLinkToDstGpuAllocMap)
	runtime.KeepAlive(cCountAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevGuidGet function as declared in rsmi/rocm_smi.h:2194
func rsmiDevGuidGet(DvInd uint32, Guid *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cGuid, cGuidAllocMap := (*C.uint64_t)(unsafe.Pointer(Guid)), cgoAllocsUnknown
	__ret := C.rsmi_dev_guid_get(cDvInd, cGuid)
	runtime.KeepAlive(cGuidAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevNodeIdGet function as declared in rsmi/rocm_smi.h:2218
func rsmiDevNodeIdGet(DvInd uint32, NodeId *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cNodeId, cNodeIdAllocMap := (*C.uint32_t)(unsafe.Pointer(NodeId)), cgoAllocsUnknown
	__ret := C.rsmi_dev_node_id_get(cDvInd, cNodeId)
	runtime.KeepAlive(cNodeIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevDeviceIdentifiersGet function as declared in rsmi/rocm_smi.h:2247
func rsmiDevDeviceIdentifiersGet(DvInd uint32, Identifiers *DeviceIdentifiers) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cIdentifiers, cIdentifiersAllocMap := (*C.rsmi_device_identifiers_t)(unsafe.Pointer(Identifiers)), cgoAllocsUnknown
	__ret := C.rsmi_dev_device_identifiers_get(cDvInd, cIdentifiers)
	runtime.KeepAlive(cIdentifiersAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPciBandwidthGet function as declared in rsmi/rocm_smi.h:2276
func rsmiDevPciBandwidthGet(DvInd uint32, Bandwidth *PcieBandwidth) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBandwidth, cBandwidthAllocMap := (*C.rsmi_pcie_bandwidth_t)(unsafe.Pointer(Bandwidth)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_bandwidth_get(cDvInd, cBandwidth)
	runtime.KeepAlive(cBandwidthAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPciIdGet function as declared in rsmi/rocm_smi.h:2315
func rsmiDevPciIdGet(DvInd uint32, Bdfid *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBdfid, cBdfidAllocMap := (*C.uint64_t)(unsafe.Pointer(Bdfid)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_id_get(cDvInd, cBdfid)
	runtime.KeepAlive(cBdfidAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiNicDevPciIdGet function as declared in rsmi/rocm_smi.h:2316
func rsmiNicDevPciIdGet(DvInd uint32, Bdfid *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBdfid, cBdfidAllocMap := (*C.uint64_t)(unsafe.Pointer(Bdfid)), cgoAllocsUnknown
	__ret := C.rsmi_nic_dev_pci_id_get(cDvInd, cBdfid)
	runtime.KeepAlive(cBdfidAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiSwitchDevPciIdGet function as declared in rsmi/rocm_smi.h:2317
func rsmiSwitchDevPciIdGet(DvInd uint32, Bdfid *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBdfid, cBdfidAllocMap := (*C.uint64_t)(unsafe.Pointer(Bdfid)), cgoAllocsUnknown
	__ret := C.rsmi_switch_dev_pci_id_get(cDvInd, cBdfid)
	runtime.KeepAlive(cBdfidAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiTopoNumaAffinityGet function as declared in rsmi/rocm_smi.h:2341
func rsmiTopoNumaAffinityGet(DvInd uint32, NumaNode *int32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cNumaNode, cNumaNodeAllocMap := (*C.int32_t)(unsafe.Pointer(NumaNode)), cgoAllocsUnknown
	__ret := C.rsmi_topo_numa_affinity_get(cDvInd, cNumaNode)
	runtime.KeepAlive(cNumaNodeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPciThroughputGet function as declared in rsmi/rocm_smi.h:2367
func rsmiDevPciThroughputGet(DvInd uint32, Sent *uint64, Received *uint64, MaxPktSz *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSent, cSentAllocMap := (*C.uint64_t)(unsafe.Pointer(Sent)), cgoAllocsUnknown
	cReceived, cReceivedAllocMap := (*C.uint64_t)(unsafe.Pointer(Received)), cgoAllocsUnknown
	cMaxPktSz, cMaxPktSzAllocMap := (*C.uint64_t)(unsafe.Pointer(MaxPktSz)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_throughput_get(cDvInd, cSent, cReceived, cMaxPktSz)
	runtime.KeepAlive(cMaxPktSzAllocMap)
	runtime.KeepAlive(cReceivedAllocMap)
	runtime.KeepAlive(cSentAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPciReplayCounterGet function as declared in rsmi/rocm_smi.h:2392
func rsmiDevPciReplayCounterGet(DvInd uint32, Counter *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cCounter, cCounterAllocMap := (*C.uint64_t)(unsafe.Pointer(Counter)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_replay_counter_get(cDvInd, cCounter)
	runtime.KeepAlive(cCounterAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPciBandwidthSet function as declared in rsmi/rocm_smi.h:2430
func rsmiDevPciBandwidthSet(DvInd uint32, BwBitmask uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBwBitmask, cBwBitmaskAllocMap := (C.uint64_t)(BwBitmask), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_bandwidth_set(cDvInd, cBwBitmask)
	runtime.KeepAlive(cBwBitmaskAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPowerAveGet function as declared in rsmi/rocm_smi.h:2469
func rsmiDevPowerAveGet(DvInd uint32, SensorInd uint32, Power *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cPower, cPowerAllocMap := (*C.uint64_t)(unsafe.Pointer(Power)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_ave_get(cDvInd, cSensorInd, cPower)
	runtime.KeepAlive(cPowerAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevCurrentSocketPowerGet function as declared in rsmi/rocm_smi.h:2492
func rsmiDevCurrentSocketPowerGet(DvInd uint32, SocketPower *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSocketPower, cSocketPowerAllocMap := (*C.uint64_t)(unsafe.Pointer(SocketPower)), cgoAllocsUnknown
	__ret := C.rsmi_dev_current_socket_power_get(cDvInd, cSocketPower)
	runtime.KeepAlive(cSocketPowerAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPowerGet function as declared in rsmi/rocm_smi.h:2528
func rsmiDevPowerGet(DvInd uint32, Power *uint64, Type *PowerType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPower, cPowerAllocMap := (*C.uint64_t)(unsafe.Pointer(Power)), cgoAllocsUnknown
	cType, cTypeAllocMap := (*C.RSMI_POWER_TYPE)(unsafe.Pointer(Type)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_get(cDvInd, cPower, cType)
	runtime.KeepAlive(cTypeAllocMap)
	runtime.KeepAlive(cPowerAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevEnergyCountGet function as declared in rsmi/rocm_smi.h:2560
func rsmiDevEnergyCountGet(DvInd uint32, Power *uint64, CounterResolution *float32, Timestamp *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPower, cPowerAllocMap := (*C.uint64_t)(unsafe.Pointer(Power)), cgoAllocsUnknown
	cCounterResolution, cCounterResolutionAllocMap := (*C.float)(unsafe.Pointer(CounterResolution)), cgoAllocsUnknown
	cTimestamp, cTimestampAllocMap := (*C.uint64_t)(unsafe.Pointer(Timestamp)), cgoAllocsUnknown
	__ret := C.rsmi_dev_energy_count_get(cDvInd, cPower, cCounterResolution, cTimestamp)
	runtime.KeepAlive(cTimestampAllocMap)
	runtime.KeepAlive(cCounterResolutionAllocMap)
	runtime.KeepAlive(cPowerAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPowerCapGet function as declared in rsmi/rocm_smi.h:2588
func rsmiDevPowerCapGet(DvInd uint32, SensorInd uint32, Cap *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cCap, cCapAllocMap := (*C.uint64_t)(unsafe.Pointer(Cap)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_get(cDvInd, cSensorInd, cCap)
	runtime.KeepAlive(cCapAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPowerCapDefaultGet function as declared in rsmi/rocm_smi.h:2614
func rsmiDevPowerCapDefaultGet(DvInd uint32, SensorInd uint32, DefaultCap *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cDefaultCap, cDefaultCapAllocMap := (*C.uint64_t)(unsafe.Pointer(DefaultCap)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_default_get(cDvInd, cSensorInd, cDefaultCap)
	runtime.KeepAlive(cDefaultCapAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPowerCapRangeGet function as declared in rsmi/rocm_smi.h:2648
func rsmiDevPowerCapRangeGet(DvInd uint32, SensorInd uint32, Max *uint64, Min *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cMax, cMaxAllocMap := (*C.uint64_t)(unsafe.Pointer(Max)), cgoAllocsUnknown
	cMin, cMinAllocMap := (*C.uint64_t)(unsafe.Pointer(Min)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_range_get(cDvInd, cSensorInd, cMax, cMin)
	runtime.KeepAlive(cMinAllocMap)
	runtime.KeepAlive(cMaxAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPowerCapSet function as declared in rsmi/rocm_smi.h:2678
func rsmiDevPowerCapSet(DvInd uint32, SensorInd uint32, Cap uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cCap, cCapAllocMap := (C.uint64_t)(Cap), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_set(cDvInd, cSensorInd, cCap)
	runtime.KeepAlive(cCapAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPowerProfileSet function as declared in rsmi/rocm_smi.h:2699
func rsmiDevPowerProfileSet(DvInd uint32, Reserved uint32, Profile PowerProfilePresetMasks) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cReserved, cReservedAllocMap := (C.uint32_t)(Reserved), cgoAllocsUnknown
	cProfile, cProfileAllocMap := (C.rsmi_power_profile_preset_masks_t)(Profile), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_profile_set(cDvInd, cReserved, cProfile)
	runtime.KeepAlive(cProfileAllocMap)
	runtime.KeepAlive(cReservedAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSupportedPowerCapGet function as declared in rsmi/rocm_smi.h:2722
func rsmiDevSupportedPowerCapGet(DvInd uint32, SensorCount *uint32, SensorInds *uint32, SensorTypes *PowerCapType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorCount, cSensorCountAllocMap := (*C.uint32_t)(unsafe.Pointer(SensorCount)), cgoAllocsUnknown
	cSensorInds, cSensorIndsAllocMap := (*C.uint32_t)(unsafe.Pointer(SensorInds)), cgoAllocsUnknown
	cSensorTypes, cSensorTypesAllocMap := (*C.rsmi_power_cap_type_t)(unsafe.Pointer(SensorTypes)), cgoAllocsUnknown
	__ret := C.rsmi_dev_supported_power_cap_get(cDvInd, cSensorCount, cSensorInds, cSensorTypes)
	runtime.KeepAlive(cSensorTypesAllocMap)
	runtime.KeepAlive(cSensorIndsAllocMap)
	runtime.KeepAlive(cSensorCountAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMemoryTotalGet function as declared in rsmi/rocm_smi.h:2759
func rsmiDevMemoryTotalGet(DvInd uint32, MemType MemoryType, Total *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cMemType, cMemTypeAllocMap := (C.rsmi_memory_type_t)(MemType), cgoAllocsUnknown
	cTotal, cTotalAllocMap := (*C.uint64_t)(unsafe.Pointer(Total)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_total_get(cDvInd, cMemType, cTotal)
	runtime.KeepAlive(cTotalAllocMap)
	runtime.KeepAlive(cMemTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevCacheInfoGet function as declared in rsmi/rocm_smi.h:2775
func rsmiDevCacheInfoGet(DvInd uint32, Info *GpuCacheInfo) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cInfo, cInfoAllocMap := (*C.rsmi_gpu_cache_info_t)(unsafe.Pointer(Info)), cgoAllocsUnknown
	__ret := C.rsmi_dev_cache_info_get(cDvInd, cInfo)
	runtime.KeepAlive(cInfoAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMemoryUsageGet function as declared in rsmi/rocm_smi.h:2803
func rsmiDevMemoryUsageGet(DvInd uint32, MemType MemoryType, Used *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cMemType, cMemTypeAllocMap := (C.rsmi_memory_type_t)(MemType), cgoAllocsUnknown
	cUsed, cUsedAllocMap := (*C.uint64_t)(unsafe.Pointer(Used)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_usage_get(cDvInd, cMemType, cUsed)
	runtime.KeepAlive(cUsedAllocMap)
	runtime.KeepAlive(cMemTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMemoryBusyPercentGet function as declared in rsmi/rocm_smi.h:2828
func rsmiDevMemoryBusyPercentGet(DvInd uint32, BusyPercent *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBusyPercent, cBusyPercentAllocMap := (*C.uint32_t)(unsafe.Pointer(BusyPercent)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_busy_percent_get(cDvInd, cBusyPercent)
	runtime.KeepAlive(cBusyPercentAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMemoryReservedPagesGet function as declared in rsmi/rocm_smi.h:2865
func rsmiDevMemoryReservedPagesGet(DvInd uint32, NumPages *uint32, Records *RetiredPageRecord) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cNumPages, cNumPagesAllocMap := (*C.uint32_t)(unsafe.Pointer(NumPages)), cgoAllocsUnknown
	cRecords, cRecordsAllocMap := (*C.rsmi_retired_page_record_t)(unsafe.Pointer(Records)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_reserved_pages_get(cDvInd, cNumPages, cRecords)
	runtime.KeepAlive(cRecordsAllocMap)
	runtime.KeepAlive(cNumPagesAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevFanRpmsGet function as declared in rsmi/rocm_smi.h:2900
func rsmiDevFanRpmsGet(DvInd uint32, SensorInd uint32, Speed *int64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cSpeed, cSpeedAllocMap := (*C.int64_t)(unsafe.Pointer(Speed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_rpms_get(cDvInd, cSensorInd, cSpeed)
	runtime.KeepAlive(cSpeedAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevFanSpeedGet function as declared in rsmi/rocm_smi.h:2929
func rsmiDevFanSpeedGet(DvInd uint32, SensorInd uint32, Speed *int64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cSpeed, cSpeedAllocMap := (*C.int64_t)(unsafe.Pointer(Speed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_get(cDvInd, cSensorInd, cSpeed)
	runtime.KeepAlive(cSpeedAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevFanSpeedMaxGet function as declared in rsmi/rocm_smi.h:2956
func rsmiDevFanSpeedMaxGet(DvInd uint32, SensorInd uint32, MaxSpeed *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cMaxSpeed, cMaxSpeedAllocMap := (*C.uint64_t)(unsafe.Pointer(MaxSpeed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_max_get(cDvInd, cSensorInd, cMaxSpeed)
	runtime.KeepAlive(cMaxSpeedAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevNpmInfoGet function as declared in rsmi/rocm_smi.h:2958
func rsmiDevNpmInfoGet(DvInd uint32, NodeHandle uint64, NpmInfo *NpmInfo) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cNodeHandle, cNodeHandleAllocMap := (C.uintptr_t)(NodeHandle), cgoAllocsUnknown
	cNpmInfo, cNpmInfoAllocMap := (*C.rsmi_npm_info_t)(unsafe.Pointer(NpmInfo)), cgoAllocsUnknown
	__ret := C.rsmi_dev_npm_info_get(cDvInd, cNodeHandle, cNpmInfo)
	runtime.KeepAlive(cNpmInfoAllocMap)
	runtime.KeepAlive(cNodeHandleAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevBaseboardPowerGet function as declared in rsmi/rocm_smi.h:2961
func rsmiDevBaseboardPowerGet(DvInd uint32, Power *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPower, cPowerAllocMap := (*C.uint64_t)(unsafe.Pointer(Power)), cgoAllocsUnknown
	__ret := C.rsmi_dev_baseboard_power_get(cDvInd, cPower)
	runtime.KeepAlive(cPowerAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevTempMetricGet function as declared in rsmi/rocm_smi.h:2993
func rsmiDevTempMetricGet(DvInd uint32, SensorType uint32, Metric TemperatureMetric, Temperature *int64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorType, cSensorTypeAllocMap := (C.uint32_t)(SensorType), cgoAllocsUnknown
	cMetric, cMetricAllocMap := (C.rsmi_temperature_metric_t)(Metric), cgoAllocsUnknown
	cTemperature, cTemperatureAllocMap := (*C.int64_t)(unsafe.Pointer(Temperature)), cgoAllocsUnknown
	__ret := C.rsmi_dev_temp_metric_get(cDvInd, cSensorType, cMetric, cTemperature)
	runtime.KeepAlive(cTemperatureAllocMap)
	runtime.KeepAlive(cMetricAllocMap)
	runtime.KeepAlive(cSensorTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevVoltMetricGet function as declared in rsmi/rocm_smi.h:3026
func rsmiDevVoltMetricGet(DvInd uint32, SensorType VoltageType, Metric VoltageMetric, Voltage *int64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorType, cSensorTypeAllocMap := (C.rsmi_voltage_type_t)(SensorType), cgoAllocsUnknown
	cMetric, cMetricAllocMap := (C.rsmi_voltage_metric_t)(Metric), cgoAllocsUnknown
	cVoltage, cVoltageAllocMap := (*C.int64_t)(unsafe.Pointer(Voltage)), cgoAllocsUnknown
	__ret := C.rsmi_dev_volt_metric_get(cDvInd, cSensorType, cMetric, cVoltage)
	runtime.KeepAlive(cVoltageAllocMap)
	runtime.KeepAlive(cMetricAllocMap)
	runtime.KeepAlive(cSensorTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevFanReset function as declared in rsmi/rocm_smi.h:3050
func rsmiDevFanReset(DvInd uint32, SensorInd uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_reset(cDvInd, cSensorInd)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevFanSpeedSet function as declared in rsmi/rocm_smi.h:3074
func rsmiDevFanSpeedSet(DvInd uint32, SensorInd uint32, Speed uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cSpeed, cSpeedAllocMap := (C.uint64_t)(Speed), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_set(cDvInd, cSensorInd, cSpeed)
	runtime.KeepAlive(cSpeedAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevBusyPercentGet function as declared in rsmi/rocm_smi.h:3107
func rsmiDevBusyPercentGet(DvInd uint32, BusyPercent *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBusyPercent, cBusyPercentAllocMap := (*C.uint32_t)(unsafe.Pointer(BusyPercent)), cgoAllocsUnknown
	__ret := C.rsmi_dev_busy_percent_get(cDvInd, cBusyPercent)
	runtime.KeepAlive(cBusyPercentAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiUtilizationCountGet function as declared in rsmi/rocm_smi.h:3138
func rsmiUtilizationCountGet(DvInd uint32, UtilizationCounters *UtilizationCounter, Count uint32, Timestamp *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cUtilizationCounters, cUtilizationCountersAllocMap := (*C.rsmi_utilization_counter_t)(unsafe.Pointer(UtilizationCounters)), cgoAllocsUnknown
	cCount, cCountAllocMap := (C.uint32_t)(Count), cgoAllocsUnknown
	cTimestamp, cTimestampAllocMap := (*C.uint64_t)(unsafe.Pointer(Timestamp)), cgoAllocsUnknown
	__ret := C.rsmi_utilization_count_get(cDvInd, cUtilizationCounters, cCount, cTimestamp)
	runtime.KeepAlive(cTimestampAllocMap)
	runtime.KeepAlive(cCountAllocMap)
	runtime.KeepAlive(cUtilizationCountersAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevActivityMetricGet function as declared in rsmi/rocm_smi.h:3166
func rsmiDevActivityMetricGet(DvInd uint32, ActivityMetricType ActivityMetric, ActivityMetricCounter *ActivityMetricCounter) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cActivityMetricType, cActivityMetricTypeAllocMap := (C.rsmi_activity_metric_t)(ActivityMetricType), cgoAllocsUnknown
	cActivityMetricCounter, cActivityMetricCounterAllocMap := (*C.rsmi_activity_metric_counter_t)(unsafe.Pointer(ActivityMetricCounter)), cgoAllocsUnknown
	__ret := C.rsmi_dev_activity_metric_get(cDvInd, cActivityMetricType, cActivityMetricCounter)
	runtime.KeepAlive(cActivityMetricCounterAllocMap)
	runtime.KeepAlive(cActivityMetricTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevActivityAvgMmGet function as declared in rsmi/rocm_smi.h:3190
func rsmiDevActivityAvgMmGet(DvInd uint32, AvgActivity *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cAvgActivity, cAvgActivityAllocMap := (*C.uint16_t)(unsafe.Pointer(AvgActivity)), cgoAllocsUnknown
	__ret := C.rsmi_dev_activity_avg_mm_get(cDvInd, cAvgActivity)
	runtime.KeepAlive(cAvgActivityAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPerfLevelGet function as declared in rsmi/rocm_smi.h:3215
func rsmiDevPerfLevelGet(DvInd uint32, Perf *DevPerfLevel) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPerf, cPerfAllocMap := (*C.rsmi_dev_perf_level_t)(unsafe.Pointer(Perf)), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_get(cDvInd, cPerf)
	runtime.KeepAlive(cPerfAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiPerfDeterminismModeSet function as declared in rsmi/rocm_smi.h:3238
func rsmiPerfDeterminismModeSet(DvInd uint32, Clkvalue uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cClkvalue, cClkvalueAllocMap := (C.uint64_t)(Clkvalue), cgoAllocsUnknown
	__ret := C.rsmi_perf_determinism_mode_set(cDvInd, cClkvalue)
	runtime.KeepAlive(cClkvalueAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevOverdriveLevelGet function as declared in rsmi/rocm_smi.h:3263
func rsmiDevOverdriveLevelGet(DvInd uint32, Od *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cOd, cOdAllocMap := (*C.uint32_t)(unsafe.Pointer(Od)), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_get(cDvInd, cOd)
	runtime.KeepAlive(cOdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMemOverdriveLevelGet function as declared in rsmi/rocm_smi.h:3288
func rsmiDevMemOverdriveLevelGet(DvInd uint32, Od *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cOd, cOdAllocMap := (*C.uint32_t)(unsafe.Pointer(Od)), cgoAllocsUnknown
	__ret := C.rsmi_dev_mem_overdrive_level_get(cDvInd, cOd)
	runtime.KeepAlive(cOdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevGpuClkFreqGet function as declared in rsmi/rocm_smi.h:3322
func rsmiDevGpuClkFreqGet(DvInd uint32, ClkType ClkType, F *Frequencies) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cClkType, cClkTypeAllocMap := (C.rsmi_clk_type_t)(ClkType), cgoAllocsUnknown
	cF, cFAllocMap := (*C.rsmi_frequencies_t)(unsafe.Pointer(F)), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_clk_freq_get(cDvInd, cClkType, cF)
	runtime.KeepAlive(cFAllocMap)
	runtime.KeepAlive(cClkTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevGpuReset function as declared in rsmi/rocm_smi.h:3338
func rsmiDevGpuReset(DvInd uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_reset(cDvInd)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevOdVoltInfoGet function as declared in rsmi/rocm_smi.h:3362
func rsmiDevOdVoltInfoGet(DvInd uint32, Odv *OdVoltFreqData) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cOdv, cOdvAllocMap := (*C.rsmi_od_volt_freq_data_t)(unsafe.Pointer(Odv)), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_volt_info_get(cDvInd, cOdv)
	runtime.KeepAlive(cOdvAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevGpuPartitionMetricsInfoGet function as declared in rsmi/rocm_smi.h:3384
func rsmiDevGpuPartitionMetricsInfoGet(DvInd uint32, PgpuMetrics *GpuMetrics) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPgpuMetrics, cPgpuMetricsAllocMap := (*C.rsmi_gpu_metrics_t)(unsafe.Pointer(PgpuMetrics)), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_partition_metrics_info_get(cDvInd, cPgpuMetrics)
	runtime.KeepAlive(cPgpuMetricsAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevGpuMetricsInfoGet function as declared in rsmi/rocm_smi.h:3407
func rsmiDevGpuMetricsInfoGet(DvInd uint32, PgpuMetrics *GpuMetrics) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPgpuMetrics, cPgpuMetricsAllocMap := (*C.rsmi_gpu_metrics_t)(unsafe.Pointer(PgpuMetrics)), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_metrics_info_get(cDvInd, cPgpuMetrics)
	runtime.KeepAlive(cPgpuMetricsAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPmMetricsInfoGet function as declared in rsmi/rocm_smi.h:3438
func rsmiDevPmMetricsInfoGet(DvInd uint32, PmMetrics **NameValue, NumOfMetrics *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPmMetrics, cPmMetricsAllocMap := (**C.rsmi_name_value_t)(unsafe.Pointer(PmMetrics)), cgoAllocsUnknown
	cNumOfMetrics, cNumOfMetricsAllocMap := (*C.uint32_t)(unsafe.Pointer(NumOfMetrics)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pm_metrics_info_get(cDvInd, cPmMetrics, cNumOfMetrics)
	runtime.KeepAlive(cNumOfMetricsAllocMap)
	runtime.KeepAlive(cPmMetricsAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevRegTableInfoGet function as declared in rsmi/rocm_smi.h:3472
func rsmiDevRegTableInfoGet(DvInd uint32, RegType RegType, RegMetrics **NameValue, NumOfMetrics *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cRegType, cRegTypeAllocMap := (C.rsmi_reg_type_t)(RegType), cgoAllocsUnknown
	cRegMetrics, cRegMetricsAllocMap := (**C.rsmi_name_value_t)(unsafe.Pointer(RegMetrics)), cgoAllocsUnknown
	cNumOfMetrics, cNumOfMetricsAllocMap := (*C.uint32_t)(unsafe.Pointer(NumOfMetrics)), cgoAllocsUnknown
	__ret := C.rsmi_dev_reg_table_info_get(cDvInd, cRegType, cRegMetrics, cNumOfMetrics)
	runtime.KeepAlive(cNumOfMetricsAllocMap)
	runtime.KeepAlive(cRegMetricsAllocMap)
	runtime.KeepAlive(cRegTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevClkRangeSet function as declared in rsmi/rocm_smi.h:3498
func rsmiDevClkRangeSet(DvInd uint32, Minclkvalue uint64, Maxclkvalue uint64, ClkType ClkType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cMinclkvalue, cMinclkvalueAllocMap := (C.uint64_t)(Minclkvalue), cgoAllocsUnknown
	cMaxclkvalue, cMaxclkvalueAllocMap := (C.uint64_t)(Maxclkvalue), cgoAllocsUnknown
	cClkType, cClkTypeAllocMap := (C.rsmi_clk_type_t)(ClkType), cgoAllocsUnknown
	__ret := C.rsmi_dev_clk_range_set(cDvInd, cMinclkvalue, cMaxclkvalue, cClkType)
	runtime.KeepAlive(cClkTypeAllocMap)
	runtime.KeepAlive(cMaxclkvalueAllocMap)
	runtime.KeepAlive(cMinclkvalueAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevClkExtremumSet function as declared in rsmi/rocm_smi.h:3522
func rsmiDevClkExtremumSet(DvInd uint32, Level FreqInd, Clkvalue uint64, ClkType ClkType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cLevel, cLevelAllocMap := (C.rsmi_freq_ind_t)(Level), cgoAllocsUnknown
	cClkvalue, cClkvalueAllocMap := (C.uint64_t)(Clkvalue), cgoAllocsUnknown
	cClkType, cClkTypeAllocMap := (C.rsmi_clk_type_t)(ClkType), cgoAllocsUnknown
	__ret := C.rsmi_dev_clk_extremum_set(cDvInd, cLevel, cClkvalue, cClkType)
	runtime.KeepAlive(cClkTypeAllocMap)
	runtime.KeepAlive(cClkvalueAllocMap)
	runtime.KeepAlive(cLevelAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevOdClkInfoSet function as declared in rsmi/rocm_smi.h:3547
func rsmiDevOdClkInfoSet(DvInd uint32, Level FreqInd, Clkvalue uint64, ClkType ClkType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cLevel, cLevelAllocMap := (C.rsmi_freq_ind_t)(Level), cgoAllocsUnknown
	cClkvalue, cClkvalueAllocMap := (C.uint64_t)(Clkvalue), cgoAllocsUnknown
	cClkType, cClkTypeAllocMap := (C.rsmi_clk_type_t)(ClkType), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_clk_info_set(cDvInd, cLevel, cClkvalue, cClkType)
	runtime.KeepAlive(cClkTypeAllocMap)
	runtime.KeepAlive(cClkvalueAllocMap)
	runtime.KeepAlive(cLevelAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevOdVoltInfoSet function as declared in rsmi/rocm_smi.h:3571
func rsmiDevOdVoltInfoSet(DvInd uint32, Vpoint uint32, Clkvalue uint64, Voltvalue uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cVpoint, cVpointAllocMap := (C.uint32_t)(Vpoint), cgoAllocsUnknown
	cClkvalue, cClkvalueAllocMap := (C.uint64_t)(Clkvalue), cgoAllocsUnknown
	cVoltvalue, cVoltvalueAllocMap := (C.uint64_t)(Voltvalue), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_volt_info_set(cDvInd, cVpoint, cClkvalue, cVoltvalue)
	runtime.KeepAlive(cVoltvalueAllocMap)
	runtime.KeepAlive(cClkvalueAllocMap)
	runtime.KeepAlive(cVpointAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevOdVoltCurveRegionsGet function as declared in rsmi/rocm_smi.h:3612
func rsmiDevOdVoltCurveRegionsGet(DvInd uint32, NumRegions *uint32, Buffer *FreqVoltRegion) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cNumRegions, cNumRegionsAllocMap := (*C.uint32_t)(unsafe.Pointer(NumRegions)), cgoAllocsUnknown
	cBuffer, cBufferAllocMap := (*C.rsmi_freq_volt_region_t)(unsafe.Pointer(Buffer)), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_volt_curve_regions_get(cDvInd, cNumRegions, cBuffer)
	runtime.KeepAlive(cBufferAllocMap)
	runtime.KeepAlive(cNumRegionsAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPowerProfilePresetsGet function as declared in rsmi/rocm_smi.h:3650
func rsmiDevPowerProfilePresetsGet(DvInd uint32, SensorInd uint32, Status *PowerProfileStatus) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSensorInd, cSensorIndAllocMap := (C.uint32_t)(SensorInd), cgoAllocsUnknown
	cStatus, cStatusAllocMap := (*C.rsmi_power_profile_status_t)(unsafe.Pointer(Status)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_profile_presets_get(cDvInd, cSensorInd, cStatus)
	runtime.KeepAlive(cStatusAllocMap)
	runtime.KeepAlive(cSensorIndAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPerfLevelSet function as declared in rsmi/rocm_smi.h:3682
func rsmiDevPerfLevelSet(DvInd uint32, PerfLvl DevPerfLevel) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPerfLvl, cPerfLvlAllocMap := (C.rsmi_dev_perf_level_t)(PerfLvl), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_set(cDvInd, cPerfLvl)
	runtime.KeepAlive(cPerfLvlAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPerfLevelSetV1 function as declared in rsmi/rocm_smi.h:3702
func rsmiDevPerfLevelSetV1(DvInd uint32, PerfLvl DevPerfLevel) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPerfLvl, cPerfLvlAllocMap := (C.rsmi_dev_perf_level_t)(PerfLvl), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_set_v1(cDvInd, cPerfLvl)
	runtime.KeepAlive(cPerfLvlAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevOverdriveLevelSet function as declared in rsmi/rocm_smi.h:3747
func rsmiDevOverdriveLevelSet(DvInd uint32, Od uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cOd, cOdAllocMap := (C.uint32_t)(Od), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_set(cDvInd, cOd)
	runtime.KeepAlive(cOdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevOverdriveLevelSetV1 function as declared in rsmi/rocm_smi.h:3788
func rsmiDevOverdriveLevelSetV1(DvInd uint32, Od uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cOd, cOdAllocMap := (C.uint32_t)(Od), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_set_v1(cDvInd, cOd)
	runtime.KeepAlive(cOdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevGpuClkFreqSet function as declared in rsmi/rocm_smi.h:3824
func rsmiDevGpuClkFreqSet(DvInd uint32, ClkType ClkType, FreqBitmask uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cClkType, cClkTypeAllocMap := (C.rsmi_clk_type_t)(ClkType), cgoAllocsUnknown
	cFreqBitmask, cFreqBitmaskAllocMap := (C.uint64_t)(FreqBitmask), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_clk_freq_set(cDvInd, cClkType, cFreqBitmask)
	runtime.KeepAlive(cFreqBitmaskAllocMap)
	runtime.KeepAlive(cClkTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSocPstateGet function as declared in rsmi/rocm_smi.h:3842
func rsmiDevSocPstateGet(DvInd uint32, Policy *DpmPolicy) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPolicy, cPolicyAllocMap := (*C.rsmi_dpm_policy_t)(unsafe.Pointer(Policy)), cgoAllocsUnknown
	__ret := C.rsmi_dev_soc_pstate_get(cDvInd, cPolicy)
	runtime.KeepAlive(cPolicyAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSocPstateSet function as declared in rsmi/rocm_smi.h:3859
func rsmiDevSocPstateSet(DvInd uint32, PolicyId uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPolicyId, cPolicyIdAllocMap := (C.uint32_t)(PolicyId), cgoAllocsUnknown
	__ret := C.rsmi_dev_soc_pstate_set(cDvInd, cPolicyId)
	runtime.KeepAlive(cPolicyIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevXgmiPlpdGet function as declared in rsmi/rocm_smi.h:3877
func rsmiDevXgmiPlpdGet(DvInd uint32, XgmiPlpd *DpmPolicy) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cXgmiPlpd, cXgmiPlpdAllocMap := (*C.rsmi_dpm_policy_t)(unsafe.Pointer(XgmiPlpd)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_plpd_get(cDvInd, cXgmiPlpd)
	runtime.KeepAlive(cXgmiPlpdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevXgmiPlpdSet function as declared in rsmi/rocm_smi.h:3897
func rsmiDevXgmiPlpdSet(DvInd uint32, PlpdId uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPlpdId, cPlpdIdAllocMap := (C.uint32_t)(PlpdId), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_plpd_set(cDvInd, cPlpdId)
	runtime.KeepAlive(cPlpdIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevProcessIsolationGet function as declared in rsmi/rocm_smi.h:3914
func rsmiDevProcessIsolationGet(DvInd uint32, Pisolate *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPisolate, cPisolateAllocMap := (*C.uint32_t)(unsafe.Pointer(Pisolate)), cgoAllocsUnknown
	__ret := C.rsmi_dev_process_isolation_get(cDvInd, cPisolate)
	runtime.KeepAlive(cPisolateAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevProcessIsolationSet function as declared in rsmi/rocm_smi.h:3931
func rsmiDevProcessIsolationSet(DvInd uint32, Pisolate uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPisolate, cPisolateAllocMap := (C.uint32_t)(Pisolate), cgoAllocsUnknown
	__ret := C.rsmi_dev_process_isolation_set(cDvInd, cPisolate)
	runtime.KeepAlive(cPisolateAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevGpuRunCleanerShader function as declared in rsmi/rocm_smi.h:3946
func rsmiDevGpuRunCleanerShader(DvInd uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_run_cleaner_shader(cDvInd)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiVersionGet function as declared in rsmi/rocm_smi.h:3969
func rsmiVersionGet(Version *Version) Return {
	cVersion, cVersionAllocMap := (*C.rsmi_version_t)(unsafe.Pointer(Version)), cgoAllocsUnknown
	__ret := C.rsmi_version_get(cVersion)
	runtime.KeepAlive(cVersionAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiVersionStrGet function as declared in rsmi/rocm_smi.h:3996
func rsmiVersionStrGet(Component SwComponent, VerStr *byte, Len uint32) Return {
	cComponent, cComponentAllocMap := (C.rsmi_sw_component_t)(Component), cgoAllocsUnknown
	cVerStr, cVerStrAllocMap := (*C.char)(unsafe.Pointer(VerStr)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_version_str_get(cComponent, cVerStr, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cVerStrAllocMap)
	runtime.KeepAlive(cComponentAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevVbiosVersionGet function as declared in rsmi/rocm_smi.h:4024
func rsmiDevVbiosVersionGet(DvInd uint32, Vbios *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cVbios, cVbiosAllocMap := (*C.char)(unsafe.Pointer(Vbios)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vbios_version_get(cDvInd, cVbios, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cVbiosAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevVbiosBuildNumberGet function as declared in rsmi/rocm_smi.h:4052
func rsmiDevVbiosBuildNumberGet(DvInd uint32, VbiosBuildNumber *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cVbiosBuildNumber, cVbiosBuildNumberAllocMap := (*C.char)(unsafe.Pointer(VbiosBuildNumber)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vbios_build_number_get(cDvInd, cVbiosBuildNumber, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cVbiosBuildNumberAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevFirmwareVersionGet function as declared in rsmi/rocm_smi.h:4079
func rsmiDevFirmwareVersionGet(DvInd uint32, Block FwBlock, FwVersion *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBlock, cBlockAllocMap := (C.rsmi_fw_block_t)(Block), cgoAllocsUnknown
	cFwVersion, cFwVersionAllocMap := (*C.uint64_t)(unsafe.Pointer(FwVersion)), cgoAllocsUnknown
	__ret := C.rsmi_dev_firmware_version_get(cDvInd, cBlock, cFwVersion)
	runtime.KeepAlive(cFwVersionAllocMap)
	runtime.KeepAlive(cBlockAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevTargetGraphicsVersionGet function as declared in rsmi/rocm_smi.h:4102
func rsmiDevTargetGraphicsVersionGet(DvInd uint32, GfxVersion *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cGfxVersion, cGfxVersionAllocMap := (*C.uint64_t)(unsafe.Pointer(GfxVersion)), cgoAllocsUnknown
	__ret := C.rsmi_dev_target_graphics_version_get(cDvInd, cGfxVersion)
	runtime.KeepAlive(cGfxVersionAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevEccCountGet function as declared in rsmi/rocm_smi.h:4138
func rsmiDevEccCountGet(DvInd uint32, Block GpuBlock, Ec *ErrorCount) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBlock, cBlockAllocMap := (C.rsmi_gpu_block_t)(Block), cgoAllocsUnknown
	cEc, cEcAllocMap := (*C.rsmi_error_count_t)(unsafe.Pointer(Ec)), cgoAllocsUnknown
	__ret := C.rsmi_dev_ecc_count_get(cDvInd, cBlock, cEc)
	runtime.KeepAlive(cEcAllocMap)
	runtime.KeepAlive(cBlockAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevEccEnabledGet function as declared in rsmi/rocm_smi.h:4168
func rsmiDevEccEnabledGet(DvInd uint32, EnabledBlocks *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cEnabledBlocks, cEnabledBlocksAllocMap := (*C.uint64_t)(unsafe.Pointer(EnabledBlocks)), cgoAllocsUnknown
	__ret := C.rsmi_dev_ecc_enabled_get(cDvInd, cEnabledBlocks)
	runtime.KeepAlive(cEnabledBlocksAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevEccStatusGet function as declared in rsmi/rocm_smi.h:4195
func rsmiDevEccStatusGet(DvInd uint32, Block GpuBlock, State *RasErrState) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cBlock, cBlockAllocMap := (C.rsmi_gpu_block_t)(Block), cgoAllocsUnknown
	cState, cStateAllocMap := (*C.rsmi_ras_err_state_t)(unsafe.Pointer(State)), cgoAllocsUnknown
	__ret := C.rsmi_dev_ecc_status_get(cDvInd, cBlock, cState)
	runtime.KeepAlive(cStateAllocMap)
	runtime.KeepAlive(cBlockAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiRasFeatureInfoGet function as declared in rsmi/rocm_smi.h:4219
func rsmiRasFeatureInfoGet(DvInd uint32, RasFeature *RasFeatureInfo) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cRasFeature, cRasFeatureAllocMap := (*C.rsmi_ras_feature_info_t)(unsafe.Pointer(RasFeature)), cgoAllocsUnknown
	__ret := C.rsmi_ras_feature_info_get(cDvInd, cRasFeature)
	runtime.KeepAlive(cRasFeatureAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevCounterGroupSupported function as declared in rsmi/rocm_smi.h:4360
func rsmiDevCounterGroupSupported(DvInd uint32, Group EventGroup) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cGroup, cGroupAllocMap := (C.rsmi_event_group_t)(Group), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_group_supported(cDvInd, cGroup)
	runtime.KeepAlive(cGroupAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevCounterCreate function as declared in rsmi/rocm_smi.h:4390
func rsmiDevCounterCreate(DvInd uint32, Type EventType, EvntHandle *EventHandle) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cType, cTypeAllocMap := (C.rsmi_event_type_t)(Type), cgoAllocsUnknown
	cEvntHandle, cEvntHandleAllocMap := (*C.rsmi_event_handle_t)(unsafe.Pointer(EvntHandle)), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_create(cDvInd, cType, cEvntHandle)
	runtime.KeepAlive(cEvntHandleAllocMap)
	runtime.KeepAlive(cTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevCounterDestroy function as declared in rsmi/rocm_smi.h:4406
func rsmiDevCounterDestroy(EvntHandle EventHandle) Return {
	cEvntHandle, cEvntHandleAllocMap := (C.rsmi_event_handle_t)(EvntHandle), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_destroy(cEvntHandle)
	runtime.KeepAlive(cEvntHandleAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiCounterControl function as declared in rsmi/rocm_smi.h:4425
func rsmiCounterControl(EvtHandle EventHandle, Cmd CounterCommand, CmdArgs unsafe.Pointer) Return {
	cEvtHandle, cEvtHandleAllocMap := (C.rsmi_event_handle_t)(EvtHandle), cgoAllocsUnknown
	cCmd, cCmdAllocMap := (C.rsmi_counter_command_t)(Cmd), cgoAllocsUnknown
	cCmdArgs, cCmdArgsAllocMap := CmdArgs, cgoAllocsUnknown
	__ret := C.rsmi_counter_control(cEvtHandle, cCmd, cCmdArgs)
	runtime.KeepAlive(cCmdArgsAllocMap)
	runtime.KeepAlive(cCmdAllocMap)
	runtime.KeepAlive(cEvtHandleAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiCounterRead function as declared in rsmi/rocm_smi.h:4445
func rsmiCounterRead(EvtHandle EventHandle, Value *CounterValue) Return {
	cEvtHandle, cEvtHandleAllocMap := (C.rsmi_event_handle_t)(EvtHandle), cgoAllocsUnknown
	cValue, cValueAllocMap := (*C.rsmi_counter_value_t)(unsafe.Pointer(Value)), cgoAllocsUnknown
	__ret := C.rsmi_counter_read(cEvtHandle, cValue)
	runtime.KeepAlive(cValueAllocMap)
	runtime.KeepAlive(cEvtHandleAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiCounterAvailableCountersGet function as declared in rsmi/rocm_smi.h:4466
func rsmiCounterAvailableCountersGet(DvInd uint32, Grp EventGroup, Available *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cGrp, cGrpAllocMap := (C.rsmi_event_group_t)(Grp), cgoAllocsUnknown
	cAvailable, cAvailableAllocMap := (*C.uint32_t)(unsafe.Pointer(Available)), cgoAllocsUnknown
	__ret := C.rsmi_counter_available_counters_get(cDvInd, cGrp, cAvailable)
	runtime.KeepAlive(cAvailableAllocMap)
	runtime.KeepAlive(cGrpAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiComputeProcessInfoGet function as declared in rsmi/rocm_smi.h:4508
func rsmiComputeProcessInfoGet(Procs *ProcessInfo, NumItems *uint32) Return {
	cProcs, cProcsAllocMap := (*C.rsmi_process_info_t)(unsafe.Pointer(Procs)), cgoAllocsUnknown
	cNumItems, cNumItemsAllocMap := (*C.uint32_t)(unsafe.Pointer(NumItems)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_info_get(cProcs, cNumItems)
	runtime.KeepAlive(cNumItemsAllocMap)
	runtime.KeepAlive(cProcsAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiComputeProcessInfoByPidGet function as declared in rsmi/rocm_smi.h:4531
func rsmiComputeProcessInfoByPidGet(Pid uint32, Proc *ProcessInfo) Return {
	cPid, cPidAllocMap := (C.uint32_t)(Pid), cgoAllocsUnknown
	cProc, cProcAllocMap := (*C.rsmi_process_info_t)(unsafe.Pointer(Proc)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_info_by_pid_get(cPid, cProc)
	runtime.KeepAlive(cProcAllocMap)
	runtime.KeepAlive(cPidAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiComputeProcessGpusGet function as declared in rsmi/rocm_smi.h:4567
func rsmiComputeProcessGpusGet(Pid uint32, DvIndices *uint32, NumDevices *uint32) Return {
	cPid, cPidAllocMap := (C.uint32_t)(Pid), cgoAllocsUnknown
	cDvIndices, cDvIndicesAllocMap := (*C.uint32_t)(unsafe.Pointer(DvIndices)), cgoAllocsUnknown
	cNumDevices, cNumDevicesAllocMap := (*C.uint32_t)(unsafe.Pointer(NumDevices)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_gpus_get(cPid, cDvIndices, cNumDevices)
	runtime.KeepAlive(cNumDevicesAllocMap)
	runtime.KeepAlive(cDvIndicesAllocMap)
	runtime.KeepAlive(cPidAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiComputeProcessInfoByDeviceGet function as declared in rsmi/rocm_smi.h:4589
func rsmiComputeProcessInfoByDeviceGet(Pid uint32, DvInd uint32, Proc *ProcessInfo) Return {
	cPid, cPidAllocMap := (C.uint32_t)(Pid), cgoAllocsUnknown
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cProc, cProcAllocMap := (*C.rsmi_process_info_t)(unsafe.Pointer(Proc)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_info_by_device_get(cPid, cDvInd, cProc)
	runtime.KeepAlive(cProcAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	runtime.KeepAlive(cPidAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevXgmiErrorStatus function as declared in rsmi/rocm_smi.h:4623
func rsmiDevXgmiErrorStatus(DvInd uint32, Status *XgmiStatus) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cStatus, cStatusAllocMap := (*C.rsmi_xgmi_status_t)(unsafe.Pointer(Status)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_error_status(cDvInd, cStatus)
	runtime.KeepAlive(cStatusAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevXgmiErrorReset function as declared in rsmi/rocm_smi.h:4637
func rsmiDevXgmiErrorReset(DvInd uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_error_reset(cDvInd)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevXgmiHiveIdGet function as declared in rsmi/rocm_smi.h:4657
func rsmiDevXgmiHiveIdGet(DvInd uint32, HiveId *uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cHiveId, cHiveIdAllocMap := (*C.uint64_t)(unsafe.Pointer(HiveId)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_hive_id_get(cDvInd, cHiveId)
	runtime.KeepAlive(cHiveIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiTopoGetNumaNodeNumber function as declared in rsmi/rocm_smi.h:4684
func rsmiTopoGetNumaNodeNumber(DvInd uint32, NumaNode *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cNumaNode, cNumaNodeAllocMap := (*C.uint32_t)(unsafe.Pointer(NumaNode)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_numa_node_number(cDvInd, cNumaNode)
	runtime.KeepAlive(cNumaNodeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiTopoGetLinkWeight function as declared in rsmi/rocm_smi.h:4706
func rsmiTopoGetLinkWeight(DvIndSrc uint32, DvIndDst uint32, Weight *uint64) Return {
	cDvIndSrc, cDvIndSrcAllocMap := (C.uint32_t)(DvIndSrc), cgoAllocsUnknown
	cDvIndDst, cDvIndDstAllocMap := (C.uint32_t)(DvIndDst), cgoAllocsUnknown
	cWeight, cWeightAllocMap := (*C.uint64_t)(unsafe.Pointer(Weight)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_link_weight(cDvIndSrc, cDvIndDst, cWeight)
	runtime.KeepAlive(cWeightAllocMap)
	runtime.KeepAlive(cDvIndDstAllocMap)
	runtime.KeepAlive(cDvIndSrcAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiMinmaxBandwidthGet function as declared in rsmi/rocm_smi.h:4730
func rsmiMinmaxBandwidthGet(DvIndSrc uint32, DvIndDst uint32, MinBandwidth *uint64, MaxBandwidth *uint64) Return {
	cDvIndSrc, cDvIndSrcAllocMap := (C.uint32_t)(DvIndSrc), cgoAllocsUnknown
	cDvIndDst, cDvIndDstAllocMap := (C.uint32_t)(DvIndDst), cgoAllocsUnknown
	cMinBandwidth, cMinBandwidthAllocMap := (*C.uint64_t)(unsafe.Pointer(MinBandwidth)), cgoAllocsUnknown
	cMaxBandwidth, cMaxBandwidthAllocMap := (*C.uint64_t)(unsafe.Pointer(MaxBandwidth)), cgoAllocsUnknown
	__ret := C.rsmi_minmax_bandwidth_get(cDvIndSrc, cDvIndDst, cMinBandwidth, cMaxBandwidth)
	runtime.KeepAlive(cMaxBandwidthAllocMap)
	runtime.KeepAlive(cMinBandwidthAllocMap)
	runtime.KeepAlive(cDvIndDstAllocMap)
	runtime.KeepAlive(cDvIndSrcAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiTopoGetLinkType function as declared in rsmi/rocm_smi.h:4765
func rsmiTopoGetLinkType(DvIndSrc uint32, DvIndDst uint32, Hops *uint64, Type *IoLinkType) Return {
	cDvIndSrc, cDvIndSrcAllocMap := (C.uint32_t)(DvIndSrc), cgoAllocsUnknown
	cDvIndDst, cDvIndDstAllocMap := (C.uint32_t)(DvIndDst), cgoAllocsUnknown
	cHops, cHopsAllocMap := (*C.uint64_t)(unsafe.Pointer(Hops)), cgoAllocsUnknown
	cType, cTypeAllocMap := (*C.RSMI_IO_LINK_TYPE)(unsafe.Pointer(Type)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_link_type(cDvIndSrc, cDvIndDst, cHops, cType)
	runtime.KeepAlive(cTypeAllocMap)
	runtime.KeepAlive(cHopsAllocMap)
	runtime.KeepAlive(cDvIndDstAllocMap)
	runtime.KeepAlive(cDvIndSrcAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiIsP2PAccessible function as declared in rsmi/rocm_smi.h:4788
func rsmiIsP2PAccessible(DvIndSrc uint32, DvIndDst uint32, Accessible *bool) Return {
	cDvIndSrc, cDvIndSrcAllocMap := (C.uint32_t)(DvIndSrc), cgoAllocsUnknown
	cDvIndDst, cDvIndDstAllocMap := (C.uint32_t)(DvIndDst), cgoAllocsUnknown
	cAccessible, cAccessibleAllocMap := (*C._Bool)(unsafe.Pointer(Accessible)), cgoAllocsUnknown
	__ret := C.rsmi_is_P2P_accessible(cDvIndSrc, cDvIndDst, cAccessible)
	runtime.KeepAlive(cAccessibleAllocMap)
	runtime.KeepAlive(cDvIndDstAllocMap)
	runtime.KeepAlive(cDvIndSrcAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiTopoGetP2pStatus function as declared in rsmi/rocm_smi.h:4817
func rsmiTopoGetP2pStatus(DvIndSrc uint32, DvIndDst uint32, Type *IoLinkType, Cap *P2pCapability) Return {
	cDvIndSrc, cDvIndSrcAllocMap := (C.uint32_t)(DvIndSrc), cgoAllocsUnknown
	cDvIndDst, cDvIndDstAllocMap := (C.uint32_t)(DvIndDst), cgoAllocsUnknown
	cType, cTypeAllocMap := (*C.RSMI_IO_LINK_TYPE)(unsafe.Pointer(Type)), cgoAllocsUnknown
	cCap, cCapAllocMap := (*C.rsmi_p2p_capability_t)(unsafe.Pointer(Cap)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_p2p_status(cDvIndSrc, cDvIndDst, cType, cCap)
	runtime.KeepAlive(cCapAllocMap)
	runtime.KeepAlive(cTypeAllocMap)
	runtime.KeepAlive(cDvIndDstAllocMap)
	runtime.KeepAlive(cDvIndSrcAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevComputePartitionGet function as declared in rsmi/rocm_smi.h:4857
func rsmiDevComputePartitionGet(DvInd uint32, ComputePartition *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cComputePartition, cComputePartitionAllocMap := (*C.char)(unsafe.Pointer(ComputePartition)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_get(cDvInd, cComputePartition, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cComputePartitionAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevComputePartitionSet function as declared in rsmi/rocm_smi.h:4884
func rsmiDevComputePartitionSet(DvInd uint32, ComputePartition ComputePartitionType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cComputePartition, cComputePartitionAllocMap := (C.rsmi_compute_partition_type_t)(ComputePartition), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_set(cDvInd, cComputePartition)
	runtime.KeepAlive(cComputePartitionAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevPartitionIdGet function as declared in rsmi/rocm_smi.h:4909
func rsmiDevPartitionIdGet(DvInd uint32, PartitionId *uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cPartitionId, cPartitionIdAllocMap := (*C.uint32_t)(unsafe.Pointer(PartitionId)), cgoAllocsUnknown
	__ret := C.rsmi_dev_partition_id_get(cDvInd, cPartitionId)
	runtime.KeepAlive(cPartitionIdAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevComputePartitionCapabilitiesGet function as declared in rsmi/rocm_smi.h:4941
func rsmiDevComputePartitionCapabilitiesGet(DvInd uint32, ComputePartitionCaps *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cComputePartitionCaps, cComputePartitionCapsAllocMap := (*C.char)(unsafe.Pointer(ComputePartitionCaps)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_capabilities_get(cDvInd, cComputePartitionCaps, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cComputePartitionCapsAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevComputePartitionSupportedXcpConfigsGet function as declared in rsmi/rocm_smi.h:4975
func rsmiDevComputePartitionSupportedXcpConfigsGet(DvInd uint32, SupportedConfigs *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSupportedConfigs, cSupportedConfigsAllocMap := (*C.char)(unsafe.Pointer(SupportedConfigs)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_supported_xcp_configs_get(cDvInd, cSupportedConfigs, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cSupportedConfigsAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevComputePartitionSupportedNpsConfigsGet function as declared in rsmi/rocm_smi.h:5009
func rsmiDevComputePartitionSupportedNpsConfigsGet(DvInd uint32, SupportedConfigs *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSupportedConfigs, cSupportedConfigsAllocMap := (*C.char)(unsafe.Pointer(SupportedConfigs)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_supported_nps_configs_get(cDvInd, cSupportedConfigs, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cSupportedConfigsAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevCurrentComputeXcpConfigGet function as declared in rsmi/rocm_smi.h:5043
func rsmiDevCurrentComputeXcpConfigGet(DvInd uint32, CurrentXcpConfig *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cCurrentXcpConfig, cCurrentXcpConfigAllocMap := (*C.char)(unsafe.Pointer(CurrentXcpConfig)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_current_compute_xcp_config_get(cDvInd, cCurrentXcpConfig, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cCurrentXcpConfigAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevComputePartitionXcpConfigSet function as declared in rsmi/rocm_smi.h:5070
func rsmiDevComputePartitionXcpConfigSet(DvInd uint32, XcpConfig ComputePartitionType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cXcpConfig, cXcpConfigAllocMap := (C.rsmi_compute_partition_type_t)(XcpConfig), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_xcp_config_set(cDvInd, cXcpConfig)
	runtime.KeepAlive(cXcpConfigAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevComputePartitionResourceProfileGet function as declared in rsmi/rocm_smi.h:5095
func rsmiDevComputePartitionResourceProfileGet(DvInd uint32, Type *AcceleratorPartitionResourceType, Profile *AcceleratorPartitionResourceProfile) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cType, cTypeAllocMap := (*C.rsmi_accelerator_partition_resource_type_t)(unsafe.Pointer(Type)), cgoAllocsUnknown
	cProfile, cProfileAllocMap := (*C.rsmi_accelerator_partition_resource_profile_t)(unsafe.Pointer(Profile)), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_resource_profile_get(cDvInd, cType, cProfile)
	runtime.KeepAlive(cProfileAllocMap)
	runtime.KeepAlive(cTypeAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMemoryPartitionGet function as declared in rsmi/rocm_smi.h:5136
func rsmiDevMemoryPartitionGet(DvInd uint32, MemoryPartition *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cMemoryPartition, cMemoryPartitionAllocMap := (*C.char)(unsafe.Pointer(MemoryPartition)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_partition_get(cDvInd, cMemoryPartition, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cMemoryPartitionAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMemoryPartitionCapabilitiesGet function as declared in rsmi/rocm_smi.h:5168
func rsmiDevMemoryPartitionCapabilitiesGet(DvInd uint32, MemoryPartitionCaps *byte, Len uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cMemoryPartitionCaps, cMemoryPartitionCapsAllocMap := (*C.char)(unsafe.Pointer(MemoryPartitionCaps)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_partition_capabilities_get(cDvInd, cMemoryPartitionCaps, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cMemoryPartitionCapsAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMemoryPartitionSet function as declared in rsmi/rocm_smi.h:5194
func rsmiDevMemoryPartitionSet(DvInd uint32, MemoryPartition MemoryPartitionType) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cMemoryPartition, cMemoryPartitionAllocMap := (C.rsmi_memory_partition_type_t)(MemoryPartition), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_partition_set(cDvInd, cMemoryPartition)
	runtime.KeepAlive(cMemoryPartitionAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSupportedFuncIteratorOpen function as declared in rsmi/rocm_smi.h:5331
func rsmiDevSupportedFuncIteratorOpen(DvInd uint32, Handle *FuncIdIterHandle) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cHandle, cHandleAllocMap := (*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(Handle)), cgoAllocsUnknown
	__ret := C.rsmi_dev_supported_func_iterator_open(cDvInd, cHandle)
	runtime.KeepAlive(cHandleAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSupportedVariantIteratorOpen function as declared in rsmi/rocm_smi.h:5358
func rsmiDevSupportedVariantIteratorOpen(ObjH FuncIdIterHandle, VarIter *FuncIdIterHandle) Return {
	cObjH, cObjHAllocMap := *(*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(&ObjH)), cgoAllocsUnknown
	cVarIter, cVarIterAllocMap := (*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(VarIter)), cgoAllocsUnknown
	__ret := C.rsmi_dev_supported_variant_iterator_open(cObjH, cVarIter)
	runtime.KeepAlive(cVarIterAllocMap)
	runtime.KeepAlive(cObjHAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiFuncIterNext function as declared in rsmi/rocm_smi.h:5379
func rsmiFuncIterNext(Handle FuncIdIterHandle) Return {
	cHandle, cHandleAllocMap := *(*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(&Handle)), cgoAllocsUnknown
	__ret := C.rsmi_func_iter_next(cHandle)
	runtime.KeepAlive(cHandleAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevSupportedFuncIteratorClose function as declared in rsmi/rocm_smi.h:5392
func rsmiDevSupportedFuncIteratorClose(Handle *FuncIdIterHandle) Return {
	cHandle, cHandleAllocMap := (*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(Handle)), cgoAllocsUnknown
	__ret := C.rsmi_dev_supported_func_iterator_close(cHandle)
	runtime.KeepAlive(cHandleAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiFuncIterValueGet function as declared in rsmi/rocm_smi.h:5412
func rsmiFuncIterValueGet(Handle FuncIdIterHandle, Value *FuncIdValue) Return {
	cHandle, cHandleAllocMap := *(*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(&Handle)), cgoAllocsUnknown
	cValue, cValueAllocMap := (*C.rsmi_func_id_value_t)(unsafe.Pointer(Value)), cgoAllocsUnknown
	__ret := C.rsmi_func_iter_value_get(cHandle, cValue)
	runtime.KeepAlive(cValueAllocMap)
	runtime.KeepAlive(cHandleAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiEventNotificationInit function as declared in rsmi/rocm_smi.h:5437
func rsmiEventNotificationInit(DvInd uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_init(cDvInd)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiEventNotificationMaskSet function as declared in rsmi/rocm_smi.h:5465
func rsmiEventNotificationMaskSet(DvInd uint32, Mask uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cMask, cMaskAllocMap := (C.uint64_t)(Mask), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_mask_set(cDvInd, cMask)
	runtime.KeepAlive(cMaskAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiEventNotificationStop function as declared in rsmi/rocm_smi.h:5528
func rsmiEventNotificationStop(DvInd uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_stop(cDvInd)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMetricsHeaderInfoGet function as declared in rsmi/rocm_smi.h:5555
func rsmiDevMetricsHeaderInfoGet(DvInd uint32, HeaderValue *MetricsTableHeader) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cHeaderValue, cHeaderValueAllocMap := (*C.metrics_table_header_t)(unsafe.Pointer(HeaderValue)), cgoAllocsUnknown
	__ret := C.rsmi_dev_metrics_header_info_get(cDvInd, cHeaderValue)
	runtime.KeepAlive(cHeaderValueAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMetricsXcdCounterGet function as declared in rsmi/rocm_smi.h:5574
func rsmiDevMetricsXcdCounterGet(DvInd uint32, XcdCounterValue *uint16) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cXcdCounterValue, cXcdCounterValueAllocMap := (*C.uint16_t)(unsafe.Pointer(XcdCounterValue)), cgoAllocsUnknown
	__ret := C.rsmi_dev_metrics_xcd_counter_get(cDvInd, cXcdCounterValue)
	runtime.KeepAlive(cXcdCounterValueAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiGetGpuPtlState function as declared in rsmi/rocm_smi.h:5590
func rsmiGetGpuPtlState(DvInd uint32, Enabled *bool) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cEnabled, cEnabledAllocMap := (*C._Bool)(unsafe.Pointer(Enabled)), cgoAllocsUnknown
	__ret := C.rsmi_get_gpu_ptl_state(cDvInd, cEnabled)
	runtime.KeepAlive(cEnabledAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiSetGpuPtlState function as declared in rsmi/rocm_smi.h:5610
func rsmiSetGpuPtlState(DvInd uint32, Enabled bool) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cEnabled, cEnabledAllocMap := (C._Bool)(Enabled), cgoAllocsUnknown
	__ret := C.rsmi_set_gpu_ptl_state(cDvInd, cEnabled)
	runtime.KeepAlive(cEnabledAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiGetGpuPtlFormats function as declared in rsmi/rocm_smi.h:5627
func rsmiGetGpuPtlFormats(DvInd uint32, Format *byte, Len uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cFormat, cFormatAllocMap := (*C.char)(unsafe.Pointer(Format)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.size_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_get_gpu_ptl_formats(cDvInd, cFormat, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cFormatAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiSetGpuPtlFormats function as declared in rsmi/rocm_smi.h:5642
func rsmiSetGpuPtlFormats(DvInd uint32, Format string) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cFormat, cFormatAllocMap := unpackPCharString(Format)
	__ret := C.rsmi_set_gpu_ptl_formats(cDvInd, cFormat)
	runtime.KeepAlive(cFormatAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiReadSupportedPtlFormats function as declared in rsmi/rocm_smi.h:5659
func rsmiReadSupportedPtlFormats(DvInd uint32, Supported *byte, Length uint64) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	cSupported, cSupportedAllocMap := (*C.char)(unsafe.Pointer(Supported)), cgoAllocsUnknown
	cLength, cLengthAllocMap := (C.size_t)(Length), cgoAllocsUnknown
	__ret := C.rsmi_read_supported_ptl_formats(cDvInd, cSupported, cLength)
	runtime.KeepAlive(cLengthAllocMap)
	runtime.KeepAlive(cSupportedAllocMap)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevMetricsLogGet function as declared in rsmi/rocm_smi.h:5672
func rsmiDevMetricsLogGet(DvInd uint32) Return {
	cDvInd, cDvIndAllocMap := (C.uint32_t)(DvInd), cgoAllocsUnknown
	__ret := C.rsmi_dev_metrics_log_get(cDvInd)
	runtime.KeepAlive(cDvIndAllocMap)
	__v := (Return)(__ret)
	return __v
}

// rsmiDevAmdgpuDriverReload function as declared in rsmi/rocm_smi.h:5723
func rsmiDevAmdgpuDriverReload() Return {
	__ret := C.rsmi_dev_amdgpu_driver_reload()
	__v := (Return)(__ret)
	return __v
}
