// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	v1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/core/v1"
)

// InstanceVolumeApplyConfiguration represents a declarative configuration of the InstanceVolume type for use
// with apply.
//
// InstanceVolume defines the volume to mount in the Instance,
// which can be either ephemeral or persistent.
type InstanceVolumeApplyConfiguration struct {
	// Ephemeral is the ephemeral volume to mount in the Instance.
	Ephemeral *InstanceEphemeralVolumeApplyConfiguration `json:"ephemeral,omitempty"`
	// Persistent is the reference to the InstancePersistentVolume to mount in the Instance.
	Persistent *v1.LocalObjectReferenceApplyConfiguration `json:"persistent,omitempty"`
}

// InstanceVolumeApplyConfiguration constructs a declarative configuration of the InstanceVolume type for use with
// apply.
func InstanceVolume() *InstanceVolumeApplyConfiguration {
	return &InstanceVolumeApplyConfiguration{}
}

// WithEphemeral sets the Ephemeral field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ephemeral field is set to the value of the last call.
func (b *InstanceVolumeApplyConfiguration) WithEphemeral(value *InstanceEphemeralVolumeApplyConfiguration) *InstanceVolumeApplyConfiguration {
	b.Ephemeral = value
	return b
}

// WithPersistent sets the Persistent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Persistent field is set to the value of the last call.
func (b *InstanceVolumeApplyConfiguration) WithPersistent(value *v1.LocalObjectReferenceApplyConfiguration) *InstanceVolumeApplyConfiguration {
	b.Persistent = value
	return b
}
