// Code generated by api. DO NOT EDIT.

package v1alpha1

// KVCachePoolSpecApplyConfiguration represents a declarative configuration of the KVCachePoolSpec type for use
// with apply.
//
// KVCachePoolSpec defines the desired spec of KVCachePool.
type KVCachePoolSpecApplyConfiguration struct {
	// Backends names the KVCacheBackend this pool draws from. It holds NAMES rather than a typed
	// reference so this package needs no compile-time dependency on that type.
	//
	// Exactly one entry is admitted, and the rule is the webhook's rather than the schema's so the
	// refusal can carry its reason: quota lands on a single master's per-tenant ledger, and one
	// master cannot account for bytes held in another backend. A schema bound would refuse the same
	// object with a message that explains nothing.
	//
	// It is immutable, webhook-enforced. Moving a pool to another backend would strand every tenant
	// quota on the old master's ledger with nothing left to delete them with.
	//
	// The reverse is NOT exclusive: one backend may be referenced by several pools, which is why the
	// ledger and the rendered policy converge per MASTER rather than per pool.
	Backends []string `json:"backends,omitempty"`
	// Quota is the ceiling this pool declares over its backend.
	Quota *KVCachePoolQuotaApplyConfiguration `json:"quota,omitempty"`
}

// KVCachePoolSpecApplyConfiguration constructs a declarative configuration of the KVCachePoolSpec type for use with
// apply.
func KVCachePoolSpec() *KVCachePoolSpecApplyConfiguration {
	return &KVCachePoolSpecApplyConfiguration{}
}

// WithBackends adds the given value to the Backends field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Backends field.
func (b *KVCachePoolSpecApplyConfiguration) WithBackends(values ...string) *KVCachePoolSpecApplyConfiguration {
	for i := range values {
		b.Backends = append(b.Backends, values[i])
	}
	return b
}

// WithQuota sets the Quota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Quota field is set to the value of the last call.
func (b *KVCachePoolSpecApplyConfiguration) WithQuota(value *KVCachePoolQuotaApplyConfiguration) *KVCachePoolSpecApplyConfiguration {
	b.Quota = value
	return b
}
