// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	v1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/api/v1"
	corev1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/core/v1"
)

// KVCacheBackendStatusApplyConfiguration represents a declarative configuration of the KVCacheBackendStatus type for use
// with apply.
//
// KVCacheBackendStatus defines the observed state of KVCacheBackend.
type KVCacheBackendStatusApplyConfiguration struct {
	// Phase summarizes the conditions: Provisioning, Ready, Degraded, Error, Deleting. It is
	// derived from the leader's own health document rather than from its Pod phase — a Running
	// Pod whose leader reports its service not ready is Provisioning, not Ready.
	Phase *string `json:"phase,omitempty"`
	// PhaseMessage carries the reason for the phase.
	PhaseMessage *string `json:"phaseMessage,omitempty"`
	// Conditions is the finer view, one condition per axis: LeaderAvailable, MembersMounted,
	// CapacityObserved, Deletable. Every one is derived from an observed document.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Endpoints are this backend's addresses, one entry per named role — the same shape the
	// external branch takes as input. A managed backend fills both from its own Service; an
	// external one echoes what was declared.
	Endpoints []KVCacheBackendEndpointApplyConfiguration `json:"endpoints,omitempty"`
	// Capacity is what the leader reports it has and has allocated.
	Capacity *KVCacheBackendCapacityApplyConfiguration `json:"capacity,omitempty"`
	// Members is one entry per observed store member.
	Members []KVCacheBackendMemberStatusApplyConfiguration `json:"members,omitempty"`
	// UsedBy names the objects that consume this backend. A non-empty UsedBy is what the
	// finalizer refuses deletion on, so the field is the enforcement input and not a display.
	//
	// It is a TypedLocalObjectReference and not a core ObjectReference: five of that type's seven
	// fields mean nothing here, all of them are optional — so an entirely empty entry would
	// validate against a field a finalizer enforces on — and upstream tells new APIs not to embed
	// it. "Local" here means only that there is no namespace field, which is right: a backend is
	// cluster-scoped and so is everything that claims one.
	UsedBy []corev1.TypedLocalObjectReferenceApplyConfiguration `json:"usedBy,omitempty"`
}

// KVCacheBackendStatusApplyConfiguration constructs a declarative configuration of the KVCacheBackendStatus type for use with
// apply.
func KVCacheBackendStatus() *KVCacheBackendStatusApplyConfiguration {
	return &KVCacheBackendStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *KVCacheBackendStatusApplyConfiguration) WithPhase(value string) *KVCacheBackendStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithPhaseMessage sets the PhaseMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PhaseMessage field is set to the value of the last call.
func (b *KVCacheBackendStatusApplyConfiguration) WithPhaseMessage(value string) *KVCacheBackendStatusApplyConfiguration {
	b.PhaseMessage = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *KVCacheBackendStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *KVCacheBackendStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *KVCacheBackendStatusApplyConfiguration) WithEndpoints(values ...*KVCacheBackendEndpointApplyConfiguration) *KVCacheBackendStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEndpoints")
		}
		b.Endpoints = append(b.Endpoints, *values[i])
	}
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *KVCacheBackendStatusApplyConfiguration) WithCapacity(value *KVCacheBackendCapacityApplyConfiguration) *KVCacheBackendStatusApplyConfiguration {
	b.Capacity = value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *KVCacheBackendStatusApplyConfiguration) WithMembers(values ...*KVCacheBackendMemberStatusApplyConfiguration) *KVCacheBackendStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}

// WithUsedBy adds the given value to the UsedBy field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UsedBy field.
func (b *KVCacheBackendStatusApplyConfiguration) WithUsedBy(values ...*corev1.TypedLocalObjectReferenceApplyConfiguration) *KVCacheBackendStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUsedBy")
		}
		b.UsedBy = append(b.UsedBy, *values[i])
	}
	return b
}
