// Code generated by api. DO NOT EDIT.

package v1alpha1

// KVCacheBackendLeaderApplyConfiguration represents a declarative configuration of the KVCacheBackendLeader type for use
// with apply.
//
// KVCacheBackendLeader is the leader process: how many of it, how it places new writes, and the
// escape hatch for flags this API does not enumerate.
type KVCacheBackendLeaderApplyConfiguration struct {
	// Replicas is how many leader processes run. One, and only one, in this scope: electing a
	// leader among several needs a backend store this scope does not enter, and the webhook
	// refuses anything else while naming that follow-on rather than silently running one anyway.
	//
	// REQUIRED: the ceiling is duplicated in the schema on purpose, because the two layers catch
	// different absences. The webhook's message explains; this one still holds when the webhook is
	// not installed, which is when a second leader would be rendered rather than refused. Raising
	// it belongs with the field that configures the election, and widening a maximum is not a
	// breaking change.
	Replicas *int32 `json:"replicas,omitempty"`
	// AllocationStrategy is how the leader picks which member takes a new write. Random spreads
	// them; FreeRatioFirst biases toward the emptier member.
	//
	// The enum is deliberately the two that any pooled store would have, rather than every value
	// the current artifact's flag accepts: the others it accepts are specific to one medium or
	// one locality model, are reachable through ExtraArgs for anyone who needs them, and would
	// otherwise fix this API to one implementation's vocabulary. Widening the enum later is not
	// a breaking change.
	AllocationStrategy *string `json:"allocationStrategy,omitempty"`
	// MultiTenancy turns on the leader's per-tenant quota ledger and the tenant-scoped shard index
	// behind it. Off, every request falls into one default tenant and the index degrades to a plain
	// key hash, so two callers using different tenant names read each other's cache.
	//
	// It is a FIELD rather than an extraArgs entry because another API validates against it: a
	// KVCachePool is refused when its backend has no ledger to write quota into. A webhook reading
	// an unschema'd string — "true", "1", "True" — would be judging a value domain that belongs to
	// whoever typed it.
	//
	// A plain bool, not a pointer, because unset and false mean the same thing here: no ledger.
	// Unset renders NO flag rather than an explicit false, so a backend that never asked for this
	// runs the command line it ran before the field existed.
	MultiTenancy *bool `json:"multiTenancy,omitempty"`
	// ExtraArgs passes flags this API does not enumerate straight through to the leader, after
	// the derived ones. A key that collides with a flag rendered from a field above is refused
	// at admission, because two sources for one flag make the rendered command ambiguous.
	ExtraArgs map[string]string `json:"extraArgs,omitempty"`
	// Offload turns on writing evicted keys to the members' local disk tier. It is the leader's
	// half of a pair: the other half is members[].localDisk, which says where on each node those
	// bytes go, and admission refuses either half alone because the store degrades on both
	// mismatches without reporting either.
	Offload *KVCacheBackendLeaderOffloadApplyConfiguration `json:"offload,omitempty"`
}

// KVCacheBackendLeaderApplyConfiguration constructs a declarative configuration of the KVCacheBackendLeader type for use with
// apply.
func KVCacheBackendLeader() *KVCacheBackendLeaderApplyConfiguration {
	return &KVCacheBackendLeaderApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithReplicas(value int32) *KVCacheBackendLeaderApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithAllocationStrategy sets the AllocationStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocationStrategy field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithAllocationStrategy(value string) *KVCacheBackendLeaderApplyConfiguration {
	b.AllocationStrategy = &value
	return b
}

// WithMultiTenancy sets the MultiTenancy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MultiTenancy field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithMultiTenancy(value bool) *KVCacheBackendLeaderApplyConfiguration {
	b.MultiTenancy = &value
	return b
}

// WithExtraArgs puts the entries into the ExtraArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraArgs field,
// overwriting an existing map entries in ExtraArgs field with the same key.
func (b *KVCacheBackendLeaderApplyConfiguration) WithExtraArgs(entries map[string]string) *KVCacheBackendLeaderApplyConfiguration {
	if b.ExtraArgs == nil && len(entries) > 0 {
		b.ExtraArgs = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraArgs[k] = v
	}
	return b
}

// WithOffload sets the Offload field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Offload field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithOffload(value *KVCacheBackendLeaderOffloadApplyConfiguration) *KVCacheBackendLeaderApplyConfiguration {
	b.Offload = value
	return b
}
