// Code generated by api. DO NOT EDIT.

package v1alpha1

// KVCachePoolDomainApplyConfiguration represents a declarative configuration of the KVCachePoolDomain type for use
// with apply.
//
// KVCachePoolDomain is one reuse identity registered against this pool: what it is, who declared it,
// and what the master reports about it.
type KVCachePoolDomainApplyConfiguration struct {
	// Name is the reuse identity, and it is the storage layer's tenant_id.
	Name *string `json:"name,omitempty"`
	// Binding is the object that declared this domain. It is the only place a domain can be
	// declared, which is what keeps naming one a privileged act.
	Binding *KVCachePoolBindingReferenceApplyConfiguration `json:"binding,omitempty"`
	// BlockSize and Dtype are echoed from the Binding that registered the domain, so a reader of
	// the registry does not have to fetch every Binding to learn what a domain's blocks are.
	//
	// Both are REQUIRED, unlike the observed figures below, and the difference is where they come
	// from: these are copied from a Binding that already requires them, so an entry missing one
	// could only be a writer bug. Leaving them optional would let the registry answer "this domain's
	// blocks are of unknown shape", which is not a state that exists.
	//
	// Dtype is spelled to match its JSON name exactly. DType would not, and the openapi generator
	// records every such mismatch as a checked-in API rule violation — a list worth keeping for the
	// names that genuinely cannot match.
	BlockSize *int32  `json:"blockSize,omitempty"`
	Dtype     *string `json:"dtype,omitempty"`
	// Blocks and HitRate are OBSERVED, never declared, and they are ABSENT when the scrape does not
	// carry this domain. A fabricated zero hit rate on a warm cache is worse than no number, and
	// zero blocks is a different fact from "not in the scrape", which is why Blocks is a pointer.
	Blocks *int64 `json:"blocks,omitempty"`
	// HitRate is a ratio held as a STRING with a pattern, never a float, matching the shape the
	// measured surface itself uses.
	//
	// The pattern is safe here in a way an enum on an echoed vendor value would not be: this ratio is
	// COMPUTED by this operator, so its spelling is ours to guarantee. It does oblige whoever writes
	// it to format to this shape, because a value that fails the pattern fails the WHOLE status
	// write — every other field frozen at its last value — and not this one field.
	HitRate *string `json:"hitRate,omitempty"`
}

// KVCachePoolDomainApplyConfiguration constructs a declarative configuration of the KVCachePoolDomain type for use with
// apply.
func KVCachePoolDomain() *KVCachePoolDomainApplyConfiguration {
	return &KVCachePoolDomainApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *KVCachePoolDomainApplyConfiguration) WithName(value string) *KVCachePoolDomainApplyConfiguration {
	b.Name = &value
	return b
}

// WithBinding sets the Binding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Binding field is set to the value of the last call.
func (b *KVCachePoolDomainApplyConfiguration) WithBinding(value *KVCachePoolBindingReferenceApplyConfiguration) *KVCachePoolDomainApplyConfiguration {
	b.Binding = value
	return b
}

// WithBlockSize sets the BlockSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BlockSize field is set to the value of the last call.
func (b *KVCachePoolDomainApplyConfiguration) WithBlockSize(value int32) *KVCachePoolDomainApplyConfiguration {
	b.BlockSize = &value
	return b
}

// WithDtype sets the Dtype field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dtype field is set to the value of the last call.
func (b *KVCachePoolDomainApplyConfiguration) WithDtype(value string) *KVCachePoolDomainApplyConfiguration {
	b.Dtype = &value
	return b
}

// WithBlocks sets the Blocks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Blocks field is set to the value of the last call.
func (b *KVCachePoolDomainApplyConfiguration) WithBlocks(value int64) *KVCachePoolDomainApplyConfiguration {
	b.Blocks = &value
	return b
}

// WithHitRate sets the HitRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HitRate field is set to the value of the last call.
func (b *KVCachePoolDomainApplyConfiguration) WithHitRate(value string) *KVCachePoolDomainApplyConfiguration {
	b.HitRate = &value
	return b
}
