// Code generated by api. DO NOT EDIT.

package v1alpha1

// KVCacheBackendMemberTransportApplyConfiguration represents a declarative configuration of the KVCacheBackendMemberTransport type for use
// with apply.
//
// KVCacheBackendMemberTransport is a member group's override of the backend's data plane.
//
// It carries the protocol only. FabricInterfaceCount stays alongside it on the member so a group
// can select its own resource quantity and RDMA allocation mode even when it inherits the backend
// protocol.
type KVCacheBackendMemberTransportApplyConfiguration struct {
	// Protocol is the transport this group's members are ASKED to use, with the same values and
	// the same Auto-resolves-to-TCP rule as the backend's spec.transport.protocol, which this
	// field replaces for this group when set — including the residual risk that field records for
	// the respelling, which applies to a stored value here the same way.
	Protocol *string `json:"protocol,omitempty"`
}

// KVCacheBackendMemberTransportApplyConfiguration constructs a declarative configuration of the KVCacheBackendMemberTransport type for use with
// apply.
func KVCacheBackendMemberTransport() *KVCacheBackendMemberTransportApplyConfiguration {
	return &KVCacheBackendMemberTransportApplyConfiguration{}
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *KVCacheBackendMemberTransportApplyConfiguration) WithProtocol(value string) *KVCacheBackendMemberTransportApplyConfiguration {
	b.Protocol = &value
	return b
}
