// Code generated by api. DO NOT EDIT.

package v1alpha1

// KVCacheBackendExternalApplyConfiguration represents a declarative configuration of the KVCacheBackendExternal type for use
// with apply.
//
// KVCacheBackendExternal is a backend this operator does not run.
//
// TWO OF THESE MAY NAME THE SAME BACKEND, AND NOTHING HERE NOTICES. The same leader is reachable
// under more than one spelling, and this operator compares no addresses across objects, deliberately:
// every identity it could compare is either editable or needs the leader reachable at admission.
// Keeping two objects off one leader is YOURS, and three things go wrong when they are not, none of
// them a refusal on any object:
//
// - The quota of a shared reuse domain flips and never settles. Uniqueness is enforced only
// between Bindings whose pools name the SAME backend object, so two Bindings reaching one leader
// through two objects are both admitted on one domain name, and each pool's reconciler writes
// its own quotaCeiling back over the other's on every pass.
// - An undersized quota shows up as a LOW HIT RATE and nothing else. Exceeding it does not refuse
// the write: the store frees room by dropping that tenant's own older objects and retries,
// irreversibly, without any counter moving.
// - Two Bindings claiming one domain.name with a different blockSize or dtype CORRUPT each other's
// blocks — the only one of the three that produces wrong answers rather than slow ones. The
// reuse identity an engine is handed is the domain NAME alone, so two differently-shaped caches
// land under one identity: the writes succeed, the reads succeed, and the tensors are wrong.
type KVCacheBackendExternalApplyConfiguration struct {
	// Endpoints are the addresses of a backend somebody else runs, one entry per named role. Both
	// roles are required: this operator reads the Admin address and publishes the Client one, so an
	// external backend that named only one leaves either the scrape or every engine with nothing to
	// point at. It is a list rather than a single address so that a multi-leader backend needs no
	// API change to describe.
	Endpoints []KVCacheBackendEndpointApplyConfiguration `json:"endpoints,omitempty"`
}

// KVCacheBackendExternalApplyConfiguration constructs a declarative configuration of the KVCacheBackendExternal type for use with
// apply.
func KVCacheBackendExternal() *KVCacheBackendExternalApplyConfiguration {
	return &KVCacheBackendExternalApplyConfiguration{}
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *KVCacheBackendExternalApplyConfiguration) WithEndpoints(values ...*KVCacheBackendEndpointApplyConfiguration) *KVCacheBackendExternalApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEndpoints")
		}
		b.Endpoints = append(b.Endpoints, *values[i])
	}
	return b
}
