// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// KVCacheBackendMemberLocalDiskApplyConfiguration represents a declarative configuration of the KVCacheBackendMemberLocalDisk type for use
// with apply.
//
// KVCacheBackendMemberLocalDisk is the local SSD tier this member group's nodes contribute.
//
// It is the member's half of a pair; the leader's half is leader.offload, and admission refuses
// either half alone. Set on its own, the leader never enqueues an offload task and the disk stays
// empty while the member reports its capacity, which is a tier that reads as present and is not.
type KVCacheBackendMemberLocalDiskApplyConfiguration struct {
	// Path is the directory on each selected node that holds this tier, mounted into the member
	// container from the host at the same location. It is REQUIRED and has no default: choosing a
	// host directory on somebody else's nodes is not a default this operator may pick, because the
	// wrong one fills a filesystem that nothing in Kubernetes accounts for.
	//
	// - Declaring a tier REQUIRES a shell in the group's image. An init container surveys this
	// directory before the member starts, so that reusing a path is something an administrator is
	// told rather than discovers through a key that reads back as somebody else's. It runs
	// `sh -c`, and an image without a shell keeps the member from starting at all.
	// - Creating this directory and giving it the right owner is YOURS, not this operator's, and a
	// member whose container cannot write it fails at start. The omission is deliberate: an init
	// container that chowns has to name a uid, while members[].image can put a different vendor's
	// build on each group, and a chmod 0777 instead opens the directory to every process on the
	// node. An operator whose uid holds for a whole backend has what would settle it.
	Path *string `json:"path,omitempty"`
	// Capacity caps what this tier stores, in bytes. Left unset, the store's own ceiling applies and
	// nothing is rendered, so a ceiling that moves upstream is a change to investigate rather than
	// one this API silently restated.
	//
	// - It is also the figure EVICTION measures against, which is why Eviction below is not usable
	// without it: the store's watermark quota defaults to zero, which that path reads as "no
	// quota" and returns from having evicted nothing. One value is rendered into both ceilings.
	// - A set capacity must hold one BUCKET, the unit this tier is written in: the store stops
	// taking offload work as soon as one more bucket would not fit, so a smaller tier never
	// receives a key. The bucket size is this operator's to choose, so the floor moves with it.
	// - It is NOT counted into the Pod's resource requests, unlike CapacityPerMember. The tier is a
	// host directory, outside the kubelet's ephemeral-storage accounting entirely, so a request
	// against it would reserve a figure nothing polices and would then keep the member off the
	// very node that has the disk. Watching that filesystem is the operator's.
	Capacity *resource.Quantity `json:"capacity,omitempty"`
	// KeyLimit caps how many keys this tier holds. It is Capacity's other HALF rather than an
	// alternative to it: the store bounds the tier by bytes AND by key count, stops taking offload
	// work when either would be exceeded, and applies its own ceiling to whichever this object
	// leaves out. Left unset or zero, nothing is rendered, on the same rule as Capacity. It carries
	// the same bucket floor and for the same reason — the store checks against one whole bucket's
	// worth of keys, so a limit below that is a tier that can never receive one.
	KeyLimit *int64 `json:"keyLimit,omitempty"`
	// Eviction is what this tier does once it is full. Left unset, nothing is rendered and the
	// store's own behavior applies, so a default that moves upstream is a change to investigate
	// rather than one this API silently restated.
	Eviction *KVCacheBackendMemberLocalDiskEvictionApplyConfiguration `json:"eviction,omitempty"`
	// CleanAfterDelete asks this operator to empty Path when the backend is deleted, on every node
	// this group's NodeSelector picks AT THAT MOMENT. It DEFAULTS TO FALSE, and left alone the
	// directory keeps whatever it holds.
	//
	// It is a switch rather than a default because what is on that disk is the administrator's, and
	// deleting it is not a decision this operator may take on their behalf. That is also why it is
	// reachable where preparing the directory is not: removing content needs no uid, creating does.
	//
	// - "At that moment" is the whole of the promise. Nothing stores the selector's history and the
	// members are gone by the time cleanup runs, so narrowing NodeSelector or removing the
	// LocalDisk block before deleting the backend leaves the dropped nodes holding their content
	// with nothing reported about them. Delete the backend first and edit afterwards.
	// - WHAT IS REMOVED IS THE CONTENT, NOT THE DIRECTORY, which was made by whoever prepared the
	// node, may be a mount point, and carries an owner this operator did not choose.
	// - The cleanup runs the image THIS GROUP runs, on the nodes it selects, with the backend's
	// imagePullSecrets, so it does not wait on a pull the members already did.
	// - A node this operator cannot reach in time keeps its content, and deletion is not held open
	// for it: a finalizer waiting on a node that is gone leaves an object nobody can delete. The
	// node gets a warning Event naming what was left.
	// - A node where another KVCacheBackend declares an overlapping path is SKIPPED, with the same
	// kind of Event. Nothing refuses two backends naming one directory, and emptying it for this
	// one would take the other one's live data with it.
	CleanAfterDelete *bool `json:"cleanAfterDelete,omitempty"`
}

// KVCacheBackendMemberLocalDiskApplyConfiguration constructs a declarative configuration of the KVCacheBackendMemberLocalDisk type for use with
// apply.
func KVCacheBackendMemberLocalDisk() *KVCacheBackendMemberLocalDiskApplyConfiguration {
	return &KVCacheBackendMemberLocalDiskApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *KVCacheBackendMemberLocalDiskApplyConfiguration) WithPath(value string) *KVCacheBackendMemberLocalDiskApplyConfiguration {
	b.Path = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *KVCacheBackendMemberLocalDiskApplyConfiguration) WithCapacity(value resource.Quantity) *KVCacheBackendMemberLocalDiskApplyConfiguration {
	b.Capacity = &value
	return b
}

// WithKeyLimit sets the KeyLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyLimit field is set to the value of the last call.
func (b *KVCacheBackendMemberLocalDiskApplyConfiguration) WithKeyLimit(value int64) *KVCacheBackendMemberLocalDiskApplyConfiguration {
	b.KeyLimit = &value
	return b
}

// WithEviction sets the Eviction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Eviction field is set to the value of the last call.
func (b *KVCacheBackendMemberLocalDiskApplyConfiguration) WithEviction(value *KVCacheBackendMemberLocalDiskEvictionApplyConfiguration) *KVCacheBackendMemberLocalDiskApplyConfiguration {
	b.Eviction = value
	return b
}

// WithCleanAfterDelete sets the CleanAfterDelete field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CleanAfterDelete field is set to the value of the last call.
func (b *KVCacheBackendMemberLocalDiskApplyConfiguration) WithCleanAfterDelete(value bool) *KVCacheBackendMemberLocalDiskApplyConfiguration {
	b.CleanAfterDelete = &value
	return b
}
