// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// KVCacheBackendCapacityApplyConfiguration represents a declarative configuration of the KVCacheBackendCapacity type for use
// with apply.
//
// KVCacheBackendCapacity is the backend's capacity AS THE LEADER REPORTS IT. Both figures are
// pointers and stay absent when the scrape failed: a zero here would read as an empty cache, and a
// retained previous value would read as a current one.
type KVCacheBackendCapacityApplyConfiguration struct {
	Total *resource.Quantity `json:"total,omitempty"`
	Used  *resource.Quantity `json:"used,omitempty"`
}

// KVCacheBackendCapacityApplyConfiguration constructs a declarative configuration of the KVCacheBackendCapacity type for use with
// apply.
func KVCacheBackendCapacity() *KVCacheBackendCapacityApplyConfiguration {
	return &KVCacheBackendCapacityApplyConfiguration{}
}

// WithTotal sets the Total field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Total field is set to the value of the last call.
func (b *KVCacheBackendCapacityApplyConfiguration) WithTotal(value resource.Quantity) *KVCacheBackendCapacityApplyConfiguration {
	b.Total = &value
	return b
}

// WithUsed sets the Used field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Used field is set to the value of the last call.
func (b *KVCacheBackendCapacityApplyConfiguration) WithUsed(value resource.Quantity) *KVCacheBackendCapacityApplyConfiguration {
	b.Used = &value
	return b
}
