// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	workerv1alpha1 "gpustack.ai/gpustack/api/worker/v1alpha1"
)

// KVCacheBackendLeaderApplyConfiguration represents a declarative configuration of the KVCacheBackendLeader type for use
// with apply.
//
// KVCacheBackendLeader is the leader process: how many of it, how it places new writes, and the
// escape hatch for flags this API does not enumerate.
type KVCacheBackendLeaderApplyConfiguration struct {
	// Replicas is how many leader processes run. More than one requires HighAvailability: electing
	// a leader among several needs a leadership record, and the webhook refuses the pair without
	// one rather than silently running two leaders against the same members.
	//
	// Exactly one of them serves at a time. The rest are standbys -- they hold no data, answer no
	// request, and exist to take over. Raising this adds no capacity, which members do; the ceiling
	// is here to catch the reading that it does.
	//
	// REQUIRED: the ceiling is duplicated in the schema on purpose, because the two layers catch
	// different absences. The webhook's message explains; this one still holds when the webhook is
	// not installed, which is when a second leader would be rendered rather than refused. Raise
	// both together, and widening a maximum is not a breaking change.
	Replicas *int32 `json:"replicas,omitempty"`
	// HighAvailability elects the leader through a Kubernetes Lease, and it is what allows Replicas
	// above 1. Unset, the leader runs as a single process exactly as before: no election flag is
	// rendered, no extra object is created, and the command line is the one it ran before this
	// field existed.
	//
	// It carries no settings. The Lease is named after this backend, so there is no connection
	// target for anyone to supply, and the API access the election needs is rendered beside the
	// workload rather than asked for here.
	//
	// LIMITED: with MultiTenancy on, each replica seeds its tenant quota policy once at ITS OWN
	// start, so a standby that took over after a quota was raised applies the older, lower ceiling
	// for up to one KVCachePool reconcile interval -- and an over-quota write in this store is not
	// refused, it EVICTS that tenant's own older objects, irreversibly and without moving any
	// counter. The quota itself is not lost: the pool reconciler is the authority and writes back
	// the difference on its next pass, so what the window costs is hit rate.
	HighAvailability *workerv1alpha1.KVCacheBackendLeaderHighAvailability `json:"highAvailability,omitempty"`
	// AllocationStrategy is how the leader picks which member takes a new write. Random spreads
	// them; FreeRatioFirst biases toward the emptier member.
	//
	// The enum is deliberately the two that any pooled store would have, rather than every value
	// the current artifact's flag accepts: the others it accepts are specific to one medium or
	// one locality model, are reachable through ExtraArgs for anyone who needs them, and would
	// otherwise fix this API to one implementation's vocabulary. Widening the enum later is not
	// a breaking change.
	AllocationStrategy *string `json:"allocationStrategy,omitempty"`
	// MultiTenancy turns on the leader's per-tenant quota ledger and the tenant-scoped shard index
	// behind it. Off, every request falls into one default tenant and the index degrades to a plain
	// key hash, so two callers using different tenant names read each other's cache.
	//
	// It is a FIELD rather than an extraArgs entry because another API validates against it: a
	// KVCachePool is refused when its backend has no ledger to write quota into. A webhook reading
	// an unschema'd string — "true", "1", "True" — would be judging a value domain that belongs to
	// whoever typed it.
	//
	// A plain bool, not a pointer, because unset and false mean the same thing here: no ledger.
	// Unset renders NO flag rather than an explicit false, so a backend that never asked for this
	// runs the command line it ran before the field existed.
	MultiTenancy *bool `json:"multiTenancy,omitempty"`
	// ExtraArgs passes flags this API does not enumerate straight through to the leader, after
	// the derived ones. A key that collides with a flag rendered from a field above is refused
	// at admission, because two sources for one flag make the rendered command ambiguous.
	//
	// EVERY VALUE HERE IS WORLD-READABLE, on three paths and not one. It is stored verbatim on THIS
	// object, which is cluster-scoped, so reading it needs no access to any workload; it is then
	// rendered into the leader container's argv as -key=value, which exposes it again to anyone who
	// can read the Pod or the Deployment carrying it. It stays readable for the life of the object.
	// A credential does not belong here. This operator renders no flag that carries one, so this
	// field is the only way one arrives.
	ExtraArgs map[string]string `json:"extraArgs,omitempty"`
	// Offload turns on writing evicted keys to the members' local disk tier. It is the leader's
	// half of a pair: the other half is members[].localDisk, which says where on each node those
	// bytes go, and admission refuses either half alone because the store degrades on both
	// mismatches without reporting either.
	Offload *KVCacheBackendLeaderOffloadApplyConfiguration `json:"offload,omitempty"`
}

// KVCacheBackendLeaderApplyConfiguration constructs a declarative configuration of the KVCacheBackendLeader type for use with
// apply.
func KVCacheBackendLeader() *KVCacheBackendLeaderApplyConfiguration {
	return &KVCacheBackendLeaderApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithReplicas(value int32) *KVCacheBackendLeaderApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithHighAvailability sets the HighAvailability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HighAvailability field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithHighAvailability(value workerv1alpha1.KVCacheBackendLeaderHighAvailability) *KVCacheBackendLeaderApplyConfiguration {
	b.HighAvailability = &value
	return b
}

// WithAllocationStrategy sets the AllocationStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocationStrategy field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithAllocationStrategy(value string) *KVCacheBackendLeaderApplyConfiguration {
	b.AllocationStrategy = &value
	return b
}

// WithMultiTenancy sets the MultiTenancy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MultiTenancy field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithMultiTenancy(value bool) *KVCacheBackendLeaderApplyConfiguration {
	b.MultiTenancy = &value
	return b
}

// WithExtraArgs puts the entries into the ExtraArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraArgs field,
// overwriting an existing map entries in ExtraArgs field with the same key.
func (b *KVCacheBackendLeaderApplyConfiguration) WithExtraArgs(entries map[string]string) *KVCacheBackendLeaderApplyConfiguration {
	if b.ExtraArgs == nil && len(entries) > 0 {
		b.ExtraArgs = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraArgs[k] = v
	}
	return b
}

// WithOffload sets the Offload field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Offload field is set to the value of the last call.
func (b *KVCacheBackendLeaderApplyConfiguration) WithOffload(value *KVCacheBackendLeaderOffloadApplyConfiguration) *KVCacheBackendLeaderApplyConfiguration {
	b.Offload = value
	return b
}
