// Code generated by api. DO NOT EDIT.

package v1alpha1

// ModelArtifactSourceApplyConfiguration represents a declarative configuration of the ModelArtifactSource type for use
// with apply.
//
// ModelArtifactSource is a tagged union: exactly one member is set, webhook-enforced.
type ModelArtifactSourceApplyConfiguration struct {
	// HuggingFace is a Hugging Face model repository at one revision.
	HuggingFace *ModelArtifactHubSourceApplyConfiguration `json:"huggingFace,omitempty"`
	// ModelScope is RESERVED AND REFUSED by admission in this version. Its shape is fixed so that
	// opening it is a webhook change rather than a schema change, and the refusal names what opening
	// it needs: branch resolution cross-checked against git, a listing that re-lists per directory at
	// the API's silent truncation point, errors classified by the envelope code, and an engine runner
	// whose ModelScope SDK accepts a commit as the revision.
	ModelScope *ModelArtifactHubSourceApplyConfiguration `json:"modelScope,omitempty"`
	// PersistentVolumeClaim is a directory inside a claim in this namespace. The operator never
	// reads the claim's content, so the artifact has no revision and no digest, and what the
	// directory holds, and any change to it, is the user's.
	PersistentVolumeClaim *ModelArtifactPersistentVolumeClaimSourceApplyConfiguration `json:"persistentVolumeClaim,omitempty"`
}

// ModelArtifactSourceApplyConfiguration constructs a declarative configuration of the ModelArtifactSource type for use with
// apply.
func ModelArtifactSource() *ModelArtifactSourceApplyConfiguration {
	return &ModelArtifactSourceApplyConfiguration{}
}

// WithHuggingFace sets the HuggingFace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HuggingFace field is set to the value of the last call.
func (b *ModelArtifactSourceApplyConfiguration) WithHuggingFace(value *ModelArtifactHubSourceApplyConfiguration) *ModelArtifactSourceApplyConfiguration {
	b.HuggingFace = value
	return b
}

// WithModelScope sets the ModelScope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelScope field is set to the value of the last call.
func (b *ModelArtifactSourceApplyConfiguration) WithModelScope(value *ModelArtifactHubSourceApplyConfiguration) *ModelArtifactSourceApplyConfiguration {
	b.ModelScope = value
	return b
}

// WithPersistentVolumeClaim sets the PersistentVolumeClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentVolumeClaim field is set to the value of the last call.
func (b *ModelArtifactSourceApplyConfiguration) WithPersistentVolumeClaim(value *ModelArtifactPersistentVolumeClaimSourceApplyConfiguration) *ModelArtifactSourceApplyConfiguration {
	b.PersistentVolumeClaim = value
	return b
}
