// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// ModelStoreBindingQuotaApplyConfiguration represents a declarative configuration of the ModelStoreBindingQuota type for use
// with apply.
//
// ModelStoreBindingQuota is the namespace's byte budget, measured in filesystem usage.
type ModelStoreBindingQuotaApplyConfiguration struct {
	// Bytes is what the namespace's prefetches may occupy in total. The measure is the content's
	// own size, per digest and per node holding it, so a tree two namespaces share counts fully
	// against each of them — conservative, and impossible to game by warming what another tenant
	// already warmed. An increase passes admission; a decrease is refused.
	Bytes *resource.Quantity `json:"bytes,omitempty"`
}

// ModelStoreBindingQuotaApplyConfiguration constructs a declarative configuration of the ModelStoreBindingQuota type for use with
// apply.
func ModelStoreBindingQuota() *ModelStoreBindingQuotaApplyConfiguration {
	return &ModelStoreBindingQuotaApplyConfiguration{}
}

// WithBytes sets the Bytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bytes field is set to the value of the last call.
func (b *ModelStoreBindingQuotaApplyConfiguration) WithBytes(value resource.Quantity) *ModelStoreBindingQuotaApplyConfiguration {
	b.Bytes = &value
	return b
}
