// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	v1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/api/v1"
)

// ModelArtifactStatusApplyConfiguration represents a declarative configuration of the ModelArtifactStatus type for use
// with apply.
//
// ModelArtifactStatus defines the observed state of ModelArtifact.
type ModelArtifactStatusApplyConfiguration struct {
	// ObservedGeneration is the generation the status was written for.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Resolved is what the source was resolved to. It is written once and never changes afterwards:
	// a later revalidation moves only LastValidatedTime and the conditions. It is absent until the
	// first resolution succeeds.
	Resolved *ModelArtifactResolvedApplyConfiguration `json:"resolved,omitempty"`
	// Nodes is where the content is: how many nodes hold it ready, are downloading it or failed to,
	// and how far the downloading ones are. It counts the content, the manifest digest, so artifacts
	// with the same digest see the same nodes; it holds numbers only. Absent for a claim source and
	// before the first resolution.
	Nodes *ModelArtifactNodesApplyConfiguration `json:"nodes,omitempty"`
	// Conditions: Resolved says whether the source is bound to its immutable identity and the most
	// recent access check passed; Degraded says a resolution or revalidation is failing, including
	// one that has not yet revoked access.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ModelArtifactStatusApplyConfiguration constructs a declarative configuration of the ModelArtifactStatus type for use with
// apply.
func ModelArtifactStatus() *ModelArtifactStatusApplyConfiguration {
	return &ModelArtifactStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ModelArtifactStatusApplyConfiguration) WithObservedGeneration(value int64) *ModelArtifactStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithResolved sets the Resolved field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resolved field is set to the value of the last call.
func (b *ModelArtifactStatusApplyConfiguration) WithResolved(value *ModelArtifactResolvedApplyConfiguration) *ModelArtifactStatusApplyConfiguration {
	b.Resolved = value
	return b
}

// WithNodes sets the Nodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Nodes field is set to the value of the last call.
func (b *ModelArtifactStatusApplyConfiguration) WithNodes(value *ModelArtifactNodesApplyConfiguration) *ModelArtifactStatusApplyConfiguration {
	b.Nodes = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ModelArtifactStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ModelArtifactStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
