// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ModelPrefetchRetentionApplyConfiguration represents a declarative configuration of the ModelPrefetchRetention type for use
// with apply.
//
// ModelPrefetchRetention decides what happens to the content after it has landed.
type ModelPrefetchRetentionApplyConfiguration struct {
	// Pinned keeps the content on every target node against the node cache's collection: a pinned
	// digest is never an eviction candidate, though it still counts toward usage. It requires the
	// Binding to allow pinning, and admission refuses it otherwise.
	Pinned *bool `json:"pinned,omitempty"`
	// TTLAfterLastUse unpins a node's copy once nothing mounted it for this long. It is enforced
	// at the hour granularity the node's report already carries: retention does not need finer
	// precision, and finer recording would multiply the node's writes for a decision that cannot
	// tell the difference.
	TTLAfterLastUse *v1.Duration `json:"ttlAfterLastUse,omitempty"`
}

// ModelPrefetchRetentionApplyConfiguration constructs a declarative configuration of the ModelPrefetchRetention type for use with
// apply.
func ModelPrefetchRetention() *ModelPrefetchRetentionApplyConfiguration {
	return &ModelPrefetchRetentionApplyConfiguration{}
}

// WithPinned sets the Pinned field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pinned field is set to the value of the last call.
func (b *ModelPrefetchRetentionApplyConfiguration) WithPinned(value bool) *ModelPrefetchRetentionApplyConfiguration {
	b.Pinned = &value
	return b
}

// WithTTLAfterLastUse sets the TTLAfterLastUse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLAfterLastUse field is set to the value of the last call.
func (b *ModelPrefetchRetentionApplyConfiguration) WithTTLAfterLastUse(value v1.Duration) *ModelPrefetchRetentionApplyConfiguration {
	b.TTLAfterLastUse = &value
	return b
}
