// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// ModelDeploymentRoleResourcesApplyConfiguration represents a declarative configuration of the ModelDeploymentRoleResources type for use
// with apply.
//
// ModelDeploymentRoleResources is what one Pod of a role asks of an accelerator.
//
// It deliberately mirrors the accelerator fields of InstanceResources — the same names, the same
// meanings — rather than inventing a second vocabulary for one request, and it deliberately omits
// that type's CPU, RAM and LocalStorage, which are derived here rather than declared.
type ModelDeploymentRoleResourcesApplyConfiguration struct {
	// Accelerator is how many accelerator cards ONE POD asks for.
	//
	// - Left unset on an acceleratable InstanceType it DEFAULTS TO ONE at admission, on create and
	// on update alike, the same way an Instance's does. The value is written into the stored
	// object rather than applied at render time, so what was admitted is what can be read back.
	// - AN EXPLICIT ZERO IS KEPT, because it is a value the user wrote, and on an acceleratable
	// InstanceType it asks for nothing that pool's queue accounts in. It is accepted while it is
	// the only role using that type, and refused when another role shares the type: replicas
	// asking for nothing the queue accounts in are admitted and run while that queue charges
	// them nothing, spending from the pool their siblings on that type are charged for.
	// - A Pod meant to run without an accelerator belongs on an InstanceType that is not
	// acceleratable, where CPU is what the queue accounts in.
	Accelerator *resource.Quantity `json:"accelerator,omitempty"`
	// AcceleratorSlicedMemoryPercentage is the per-accelerator VRAM budget requested on a sliced
	// InstanceType, as a percentage in [0,100]. 0 disables slicing, making the request an exclusive
	// whole-accelerator one. It is ignored by an InstanceType offering no slicing.
	AcceleratorSlicedMemoryPercentage *int32 `json:"acceleratorSlicedMemoryPercentage,omitempty"`
	// AcceleratorSlicedCoresPercentage is the per-accelerator compute budget requested on a sliced
	// InstanceType, as a percentage in [0,100], independent of the memory percentage.
	AcceleratorSlicedCoresPercentage *int32 `json:"acceleratorSlicedCoresPercentage,omitempty"`
	// AcceleratorPartitionedProfile is the hardware partition profile requested on a
	// partition-offering InstanceType, e.g. "3g.40gb". A non-empty value is mutually exclusive with
	// the two slice percentages: hardware partitioning and software slicing cannot both apply to one
	// accelerator. It is ignored by an InstanceType offering no partition.
	AcceleratorPartitionedProfile *string `json:"acceleratorPartitionedProfile,omitempty"`
}

// ModelDeploymentRoleResourcesApplyConfiguration constructs a declarative configuration of the ModelDeploymentRoleResources type for use with
// apply.
func ModelDeploymentRoleResources() *ModelDeploymentRoleResourcesApplyConfiguration {
	return &ModelDeploymentRoleResourcesApplyConfiguration{}
}

// WithAccelerator sets the Accelerator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Accelerator field is set to the value of the last call.
func (b *ModelDeploymentRoleResourcesApplyConfiguration) WithAccelerator(value resource.Quantity) *ModelDeploymentRoleResourcesApplyConfiguration {
	b.Accelerator = &value
	return b
}

// WithAcceleratorSlicedMemoryPercentage sets the AcceleratorSlicedMemoryPercentage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AcceleratorSlicedMemoryPercentage field is set to the value of the last call.
func (b *ModelDeploymentRoleResourcesApplyConfiguration) WithAcceleratorSlicedMemoryPercentage(value int32) *ModelDeploymentRoleResourcesApplyConfiguration {
	b.AcceleratorSlicedMemoryPercentage = &value
	return b
}

// WithAcceleratorSlicedCoresPercentage sets the AcceleratorSlicedCoresPercentage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AcceleratorSlicedCoresPercentage field is set to the value of the last call.
func (b *ModelDeploymentRoleResourcesApplyConfiguration) WithAcceleratorSlicedCoresPercentage(value int32) *ModelDeploymentRoleResourcesApplyConfiguration {
	b.AcceleratorSlicedCoresPercentage = &value
	return b
}

// WithAcceleratorPartitionedProfile sets the AcceleratorPartitionedProfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AcceleratorPartitionedProfile field is set to the value of the last call.
func (b *ModelDeploymentRoleResourcesApplyConfiguration) WithAcceleratorPartitionedProfile(value string) *ModelDeploymentRoleResourcesApplyConfiguration {
	b.AcceleratorPartitionedProfile = &value
	return b
}
