// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	v1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/api/v1"
)

// ModelDeploymentStatusApplyConfiguration represents a declarative configuration of the ModelDeploymentStatus type for use
// with apply.
//
// ModelDeploymentStatus defines the observed state of ModelDeployment.
//
// It is REBUILT FROM OBSERVED STATE ON EVERY RECONCILE, so a stale field cannot survive a
// disagreement with the Pods.
type ModelDeploymentStatusApplyConfiguration struct {
	// Phase summarizes the conditions: Starting, Ready, Degraded, Deleting. Ready means every role's
	// ready count equals its desired count; Degraded means at least one replica is ready and at
	// least one is not.
	Phase *string `json:"phase,omitempty"`
	// PhaseMessage carries the reason for the phase.
	PhaseMessage *string `json:"phaseMessage,omitempty"`
	// Conditions is the finer view, one condition per axis: DomainRegistered, QuotaReserved,
	// CacheAttached. The three are independent — "quota reserved but cache not attached" is a real
	// and actionable state — which is what a single phase string cannot carry.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Endpoint is the one address every replica serves behind, in the form
	// http://<name>.<namespace>.svc:<port>. It is absent until the Service has an address.
	Endpoint *string `json:"endpoint,omitempty"`
	// Roles is one entry per declared role.
	Roles []ModelDeploymentRoleStatusApplyConfiguration `json:"roles,omitempty"`
	// KVCache is the reuse domain this deployment actually attached to, read from the Binding. It
	// exists so an operator can tell a cache-sharing misconfiguration from a cache that is merely
	// cold by reading this object alone.
	//
	// A POINTER because omitempty does not omit a zero-valued struct: held by value it would
	// serialize as an empty object on every pass where the Binding could not be resolved, which a
	// reader cannot tell from a domain whose every field happens to be empty.
	KVCache *ModelDeploymentKVCacheStatusApplyConfiguration `json:"kvCache,omitempty"`
}

// ModelDeploymentStatusApplyConfiguration constructs a declarative configuration of the ModelDeploymentStatus type for use with
// apply.
func ModelDeploymentStatus() *ModelDeploymentStatusApplyConfiguration {
	return &ModelDeploymentStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ModelDeploymentStatusApplyConfiguration) WithPhase(value string) *ModelDeploymentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithPhaseMessage sets the PhaseMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PhaseMessage field is set to the value of the last call.
func (b *ModelDeploymentStatusApplyConfiguration) WithPhaseMessage(value string) *ModelDeploymentStatusApplyConfiguration {
	b.PhaseMessage = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ModelDeploymentStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ModelDeploymentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *ModelDeploymentStatusApplyConfiguration) WithEndpoint(value string) *ModelDeploymentStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *ModelDeploymentStatusApplyConfiguration) WithRoles(values ...*ModelDeploymentRoleStatusApplyConfiguration) *ModelDeploymentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoles")
		}
		b.Roles = append(b.Roles, *values[i])
	}
	return b
}

// WithKVCache sets the KVCache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KVCache field is set to the value of the last call.
func (b *ModelDeploymentStatusApplyConfiguration) WithKVCache(value *ModelDeploymentKVCacheStatusApplyConfiguration) *ModelDeploymentStatusApplyConfiguration {
	b.KVCache = value
	return b
}
