// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	workerv1alpha1 "gpustack.ai/gpustack/api/worker/v1alpha1"
)

// ModelDeploymentRouterRoleStatusApplyConfiguration represents a declarative configuration of the ModelDeploymentRouterRoleStatus type for use
// with apply.
//
// ModelDeploymentRouterRoleStatus is one role as a router sees it.
type ModelDeploymentRouterRoleStatusApplyConfiguration struct {
	// Name is the role's name, matching spec.roles[].name.
	Name *string `json:"name,omitempty"`
	// Kind is the role's effective kind, which is what tells a prefiller from a decoder. It is the
	// resolved value rather than the field, because a role naming no kind is a server and a consumer
	// matching on the empty string would find nothing.
	Kind *workerv1alpha1.ModelDeploymentRoleKind `json:"kind,omitempty"`
	// Selector is the label selector matching exactly this role's Pods that answer the API -- one
	// member per replica, its leader, which at size one is the replica's only Pod -- published
	// VERBATIM so that a router is configured from observed strings rather than from a documented
	// convention.
	//
	// The unit it names is the Pod, not the replica: a replica may span several Pods, and a member
	// other than the leader serves no API even though the role runs it, so it stays outside what
	// this selector matches.
	//
	// A router given a selector survives scaling; a router given a list of addresses does not, and
	// would have to be reconfigured and restarted every time a role grew or shrank.
	Selector map[string]string `json:"selector,omitempty"`
	// Endpoint is this role's own address, which stays reachable whether or not a router fronts the
	// deployment, so that one half of a pair can be addressed directly while debugging.
	Endpoint *string `json:"endpoint,omitempty"`
	// KVEvents is where this role publishes its cache events, absent on a role configured not to
	// publish.
	KVEvents *ModelDeploymentRouterKVEventsApplyConfiguration `json:"kvEvents,omitempty"`
}

// ModelDeploymentRouterRoleStatusApplyConfiguration constructs a declarative configuration of the ModelDeploymentRouterRoleStatus type for use with
// apply.
func ModelDeploymentRouterRoleStatus() *ModelDeploymentRouterRoleStatusApplyConfiguration {
	return &ModelDeploymentRouterRoleStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModelDeploymentRouterRoleStatusApplyConfiguration) WithName(value string) *ModelDeploymentRouterRoleStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ModelDeploymentRouterRoleStatusApplyConfiguration) WithKind(value workerv1alpha1.ModelDeploymentRoleKind) *ModelDeploymentRouterRoleStatusApplyConfiguration {
	b.Kind = &value
	return b
}

// WithSelector puts the entries into the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Selector field,
// overwriting an existing map entries in Selector field with the same key.
func (b *ModelDeploymentRouterRoleStatusApplyConfiguration) WithSelector(entries map[string]string) *ModelDeploymentRouterRoleStatusApplyConfiguration {
	if b.Selector == nil && len(entries) > 0 {
		b.Selector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Selector[k] = v
	}
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *ModelDeploymentRouterRoleStatusApplyConfiguration) WithEndpoint(value string) *ModelDeploymentRouterRoleStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithKVEvents sets the KVEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KVEvents field is set to the value of the last call.
func (b *ModelDeploymentRouterRoleStatusApplyConfiguration) WithKVEvents(value *ModelDeploymentRouterKVEventsApplyConfiguration) *ModelDeploymentRouterRoleStatusApplyConfiguration {
	b.KVEvents = value
	return b
}
