// Code generated by api. DO NOT EDIT.

package v1alpha1

// ModelDeploymentModelApplyConfiguration represents a declarative configuration of the ModelDeploymentModel type for use
// with apply.
//
// ModelDeploymentModel names the model the engine serves.
//
// It provisions nothing. Weights arrive through the role template's volumes or through the engine's
// own hub client; a weight-provisioning block here would be the first step towards the
// general-purpose serving CR this deliberately is not.
type ModelDeploymentModelApplyConfiguration struct {
	// Name is the identifier the engine serves, e.g. "Qwen/Qwen2.5-72B-Instruct".
	Name *string `json:"name,omitempty"`
}

// ModelDeploymentModelApplyConfiguration constructs a declarative configuration of the ModelDeploymentModel type for use with
// apply.
func ModelDeploymentModel() *ModelDeploymentModelApplyConfiguration {
	return &ModelDeploymentModelApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModelDeploymentModelApplyConfiguration) WithName(value string) *ModelDeploymentModelApplyConfiguration {
	b.Name = &value
	return b
}
