// Code generated by api. DO NOT EDIT.

package v1alpha1

// ModelPrefetchArtifactReferenceApplyConfiguration represents a declarative configuration of the ModelPrefetchArtifactReference type for use
// with apply.
//
// ModelPrefetchArtifactReference names an artifact in the prefetch's own namespace.
type ModelPrefetchArtifactReferenceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// ModelPrefetchArtifactReferenceApplyConfiguration constructs a declarative configuration of the ModelPrefetchArtifactReference type for use with
// apply.
func ModelPrefetchArtifactReference() *ModelPrefetchArtifactReferenceApplyConfiguration {
	return &ModelPrefetchArtifactReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModelPrefetchArtifactReferenceApplyConfiguration) WithName(value string) *ModelPrefetchArtifactReferenceApplyConfiguration {
	b.Name = &value
	return b
}
