// Code generated by api. DO NOT EDIT.

package v1alpha1

// ModelDeploymentSpecApplyConfiguration represents a declarative configuration of the ModelDeploymentSpec type for use
// with apply.
//
// ModelDeploymentSpec defines the desired state of ModelDeployment.
type ModelDeploymentSpecApplyConfiguration struct {
	// Model names what the engine serves.
	Model *ModelDeploymentModelApplyConfiguration `json:"model,omitempty"`
	// Engine selects the inference engine, which decides which argument keys the operator owns and
	// which carrier the transfer configuration arrives on. Ownership is per (engine, key): a key one
	// engine owns is an ordinary user argument on another.
	//
	// It does NOT decide the connector, which follows the role's hardware instead: the connector is a
	// property of the accelerator backend, so an Ascend pool and an NVIDIA pool running this engine
	// get different ones.
	Engine *string `json:"engine,omitempty"`
	// EngineVersion is the engine's own version, e.g. "0.25.1" for vllm or "0.5.18" for sglang.
	//
	// - It is free-form and UNVALIDATED, by decision: the user guarantees that the version and the
	// driver each role's hardware installed are aligned. A gate would need the runner's release
	// matrix compiled into the operator, and the failure it would prevent is already legible as
	// an ImagePullBackOff on a tag that does not exist.
	// - It is per deployment rather than per role, which is what lets one version assemble a
	// DIFFERENT image for each role: the backend half of the tag comes from the role's own
	// InstanceType, so a prefill role on NVIDIA and a decode role on Ascend need no extra field.
	// Published version sets are measured to overlap across backends, though not across ALL of
	// them, so a per-role override may yet be needed.
	// - The lower bound is not decoration: `required` makes the key present, not the value
	// non-empty, and an empty version assembles a malformed tag naming something never typed.
	EngineVersion *string `json:"engineVersion,omitempty"`
	// KVCache attaches the deployment to a KV cache pool.
	KVCache *ModelDeploymentKVCacheApplyConfiguration `json:"kvCache,omitempty"`
	// Roles are the engine roles this deployment runs. A single-role deployment names one; a
	// prefill/decode deployment names several, which is why this is a LIST FROM THE FIRST VERSION.
	//
	// The UPPER bound lives in the validating webhook and not in this schema: it tracks Kueue's cap
	// on Workload.spec.podSets, so the refusal can name whose limit it is, and following that number
	// is a webhook edit rather than a schema change every stored object must survive. The figure is
	// not restated here, because the one that binds is in the Kueue the cluster runs.
	Roles []ModelDeploymentRoleApplyConfiguration `json:"roles,omitempty"`
}

// ModelDeploymentSpecApplyConfiguration constructs a declarative configuration of the ModelDeploymentSpec type for use with
// apply.
func ModelDeploymentSpec() *ModelDeploymentSpecApplyConfiguration {
	return &ModelDeploymentSpecApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *ModelDeploymentSpecApplyConfiguration) WithModel(value *ModelDeploymentModelApplyConfiguration) *ModelDeploymentSpecApplyConfiguration {
	b.Model = value
	return b
}

// WithEngine sets the Engine field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Engine field is set to the value of the last call.
func (b *ModelDeploymentSpecApplyConfiguration) WithEngine(value string) *ModelDeploymentSpecApplyConfiguration {
	b.Engine = &value
	return b
}

// WithEngineVersion sets the EngineVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EngineVersion field is set to the value of the last call.
func (b *ModelDeploymentSpecApplyConfiguration) WithEngineVersion(value string) *ModelDeploymentSpecApplyConfiguration {
	b.EngineVersion = &value
	return b
}

// WithKVCache sets the KVCache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KVCache field is set to the value of the last call.
func (b *ModelDeploymentSpecApplyConfiguration) WithKVCache(value *ModelDeploymentKVCacheApplyConfiguration) *ModelDeploymentSpecApplyConfiguration {
	b.KVCache = value
	return b
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *ModelDeploymentSpecApplyConfiguration) WithRoles(values ...*ModelDeploymentRoleApplyConfiguration) *ModelDeploymentSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoles")
		}
		b.Roles = append(b.Roles, *values[i])
	}
	return b
}
