// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	v1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/api/v1"
)

// NodeModelStoreStatusApplyConfiguration represents a declarative configuration of the NodeModelStoreStatus type for use
// with apply.
//
// NodeModelStoreStatus is what the plugin reports about its node, rebuilt from the node's disk and
// mounts whenever the plugin starts. It is written only when something in it changes, so a node
// whose content is not changing writes nothing.
type NodeModelStoreStatusApplyConfiguration struct {
	// ObservedGeneration is the spec generation the plugin applies.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Capacity is the cache filesystem's size and usage.
	Capacity *NodeModelStoreCapacityApplyConfiguration `json:"capacity,omitempty"`
	// Models is the content on the node, keyed by digest. When more is on disk than fits, the
	// referenced entries are kept first and then the most recently used, and the Ready condition's
	// message counts the omission.
	Models []NodeModelStoreModelApplyConfiguration `json:"models,omitempty"`
	// Conditions: Ready says the plugin serves and applies spec's generation; CapacityLow says usage
	// is above the high watermark with nothing the plugin may remove.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// NodeModelStoreStatusApplyConfiguration constructs a declarative configuration of the NodeModelStoreStatus type for use with
// apply.
func NodeModelStoreStatus() *NodeModelStoreStatusApplyConfiguration {
	return &NodeModelStoreStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *NodeModelStoreStatusApplyConfiguration) WithObservedGeneration(value int64) *NodeModelStoreStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *NodeModelStoreStatusApplyConfiguration) WithCapacity(value *NodeModelStoreCapacityApplyConfiguration) *NodeModelStoreStatusApplyConfiguration {
	b.Capacity = value
	return b
}

// WithModels adds the given value to the Models field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Models field.
func (b *NodeModelStoreStatusApplyConfiguration) WithModels(values ...*NodeModelStoreModelApplyConfiguration) *NodeModelStoreStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithModels")
		}
		b.Models = append(b.Models, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *NodeModelStoreStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *NodeModelStoreStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
