// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1

import (
	internalinterfaces "gpustack.ai/gpustack/pkg/kubeclients/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// FlowSchemas returns a FlowSchemaInformer.
	FlowSchemas() FlowSchemaInformer
	// PriorityLevelConfigurations returns a PriorityLevelConfigurationInformer.
	PriorityLevelConfigurations() PriorityLevelConfigurationInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// FlowSchemas returns a FlowSchemaInformer.
func (v *version) FlowSchemas() FlowSchemaInformer {
	return &flowSchemaInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// PriorityLevelConfigurations returns a PriorityLevelConfigurationInformer.
func (v *version) PriorityLevelConfigurations() PriorityLevelConfigurationInformer {
	return &priorityLevelConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
