package ascend

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"gpustack.ai/gpustack/pkg/device"
)

// rankTableCapability names the host ranktable in a preflight row, in HCCL's own vocabulary: the
// error this rules out calls it a ranktable, whatever the file is named.
const rankTableCapability = "hccl-ranktable"

// hcclRootInfoPath is the file HCCL reads a ranktable from, and the path ascend-docker-runtime mounts
// into every container whenever the host carries it.
//
// It is a HOST path and must be joined onto the host root before it is read -- see NewPreflighter.
// Unjoined it names this container's own /etc, which carries no such file, so the check would take
// its absent-is-ok branch on every node and never fire.
//
// The path is fixed at both ends and cannot be redirected. The runtime hard-codes it
// (ascend-common/cdi/mount/legacy_config.go:49, and addUBMount in the legacy hook), and so does
// libhccl_v2 -- every HCCL_*, RANK_* and ASCEND_* string in that library was enumerated on the 950
// host and none selects a ranktable path. RANK_TABLE_FILE is not among them: it feeds the ranktable
// init path a caller opts into, not this file.
const hcclRootInfoPath = "/etc/hccl_rootinfo.json"

// rankTableVersion950 is the ranktable format A5 accepts, and it is the only one it accepts.
//
// The format is bound to the chip generation rather than chosen: 1.0 serves A2 (910/910B/310P), 1.2
// serves A3 (910C), and 2.0 serves A5. What changed is UB addressing -- 1.0 is a flat
// server/device/rank list keyed by IP, while 2.0 carries a per-rank level_list and a rank address
// type that may be a UB EID instead of an IP (ascend-operator/pkg/ranktable/v2dot0/ranktable.go:27,
// beside Version1 and Version1Dot2 at ranktable/common/common.go:37-38).
const rankTableVersion950 = "2.0"

// checkRankTable establishes whether a ranktable on this host would stop HCCL coming up on an A5
// node, by reading the version out of the file the vendor runtime mounts into every container.
//
// The failure is measured rather than reasoned. On the 950 lab host a container that brings HCCL up
// fine breaks the moment this file is added to it, and nothing else about the container changes:
//
//	Config_Error_Ranktable(EI0014): Value 1.0 for ranktable variable version is invalid.
//	Expected value: 2.0.
//
// Only collectives are affected -- single-card allocations never build a communicator and are
// untouched -- which is why this is a row rather than a refusal. The node serves; it just cannot
// serve anything that communicates.
//
// The operator cannot prevent the mount. It injects one env and leaves injection to
// ascend-docker-runtime, whose addUBMount adds this file on presence alone: an os.Stat with no
// version check, which is the defect underneath. What the row can do is stop the failure being
// anonymous, and that is the whole of its value -- EI0014 names a ranktable version and nothing that
// would lead an operator to a file some tool wrote weeks earlier.
//
// AN ABSENT FILE IS OK, inverting how checkDockerRuntime treats a file it cannot read, and the
// inversion is deliberate. The vendor documents this one as optional and generated by
// mindcluster-tools; both 910B2 lab hosts carry none; and a container without it was measured to
// bring HCCL up through rootInfo negotiation instead. A node with no ranktable is the healthy node,
// so reporting absence as unavailable would fire on every correct host.
//
// ABSENCE ONLY MEANS THAT WHERE THE HOST'S OWN /etc WAS OBSERVED, which is why the directory is
// established before the missing file is believed. A pass whose host root is not mounted reaches
// the same os.ErrNotExist for the opposite reason -- the joined path resolves to nothing at all --
// and the runner does not stop there: it downgrades such a pass to a dry run and carries on, so
// this branch is reached on a node this code never looked at. Reporting ok there would clear a host
// whose ranktable was never read.
//
// A file that cannot be read or parsed is reported unavailable rather than waved through: the
// runtime mounts it whatever this code could make of it, so failing to read it is not being safe
// from it. The reason carries the version that was found, because an operator needs to know which
// generation wrote the file, not merely that it was refused.
//
// The row names neither an accelerator nor a mode: the ranktable is one node-level fact, and the
// caller attaches it to each accelerator and each mode it is a precondition for.
func checkRankTable(path string) device.PreflightCheck {
	c := device.PreflightCheck{
		Capability: rankTableCapability,
		State:      device.PreflightStateUnavailable,
		Depth:      device.PreflightDepthDeclared,
	}

	content, err := os.ReadFile(path)
	switch {
	case errors.Is(err, os.ErrNotExist):
		if dir := filepath.Dir(path); !isDir(dir) {
			c.Reason = fmt.Sprintf("%s was never looked for: %s is not a readable directory, so the "+
				"host's own %s is not visible to this command and a missing file here says nothing "+
				"about the host. Mount the host root before reading this row",
				hcclRootInfoPath, dir, filepath.Dir(hcclRootInfoPath))
			return c
		}
		c.State = device.PreflightStateOK
		c.Detail = fmt.Sprintf("%s is absent, so the vendor runtime mounts no ranktable and HCCL "+
			"negotiates its communicator through rootInfo", hcclRootInfoPath)
		return c
	case err != nil:
		c.Reason = fmt.Sprintf("%s could not be read, so whether it would break HCCL on this node is "+
			"unknown -- the vendor runtime mounts it whenever it exists, whatever this could make of "+
			"it: %v", hcclRootInfoPath, err)
		return c
	}

	var table struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(content, &table); err != nil {
		c.Reason = fmt.Sprintf("%s is not readable as JSON, so the ranktable generation it carries is "+
			"unknown while the vendor runtime mounts it regardless: %v", hcclRootInfoPath, err)
		return c
	}

	if table.Version == "" {
		c.Reason = fmt.Sprintf("%s carries no version entry, so the ranktable generation it carries "+
			"is unknown while the vendor runtime mounts it regardless", hcclRootInfoPath)
		return c
	}

	if table.Version != rankTableVersion950 {
		c.Reason = fmt.Sprintf("%s is a version %s ranktable and A5 accepts only %s, so the vendor "+
			"runtime mounting it into every container makes multi-card HCCL fail to initialise with "+
			"Config_Error_Ranktable (EI0014); single-card allocations are unaffected. Remove the file "+
			"or replace it with a %s table -- no environment variable disables the check",
			hcclRootInfoPath, table.Version, rankTableVersion950, rankTableVersion950)
		return c
	}

	c.State = device.PreflightStateOK
	c.Detail = fmt.Sprintf("%s is a version %s ranktable, the generation A5 accepts",
		hcclRootInfoPath, rankTableVersion950)
	return c
}

// isDir reports whether path is a directory this process can stat. Anything else -- absent,
// unreadable, or a file where a directory was expected -- is false, because every one of them means
// the same thing to the only caller: the host directory it wanted to look in was not there to look
// in.
func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}
