// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	workerv1alpha1 "gpustack.ai/gpustack/api/worker/v1alpha1"
	applyconfigurationworkerv1alpha1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/worker/v1alpha1"
	scheme "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModelArtifactsGetter has a method to return a ModelArtifactInterface.
// A group's client should implement this interface.
type ModelArtifactsGetter interface {
	ModelArtifacts(namespace string) ModelArtifactInterface
}

// ModelArtifactInterface has methods to work with ModelArtifact resources.
type ModelArtifactInterface interface {
	Create(ctx context.Context, modelArtifact *workerv1alpha1.ModelArtifact, opts v1.CreateOptions) (*workerv1alpha1.ModelArtifact, error)
	Update(ctx context.Context, modelArtifact *workerv1alpha1.ModelArtifact, opts v1.UpdateOptions) (*workerv1alpha1.ModelArtifact, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, modelArtifact *workerv1alpha1.ModelArtifact, opts v1.UpdateOptions) (*workerv1alpha1.ModelArtifact, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workerv1alpha1.ModelArtifact, error)
	List(ctx context.Context, opts v1.ListOptions) (*workerv1alpha1.ModelArtifactList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workerv1alpha1.ModelArtifact, err error)
	Apply(ctx context.Context, modelArtifact *applyconfigurationworkerv1alpha1.ModelArtifactApplyConfiguration, opts v1.ApplyOptions) (result *workerv1alpha1.ModelArtifact, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, modelArtifact *applyconfigurationworkerv1alpha1.ModelArtifactApplyConfiguration, opts v1.ApplyOptions) (result *workerv1alpha1.ModelArtifact, err error)
	ModelArtifactExpansion
}

// modelArtifacts implements ModelArtifactInterface
type modelArtifacts struct {
	*gentype.ClientWithListAndApply[*workerv1alpha1.ModelArtifact, *workerv1alpha1.ModelArtifactList, *applyconfigurationworkerv1alpha1.ModelArtifactApplyConfiguration]
}

// newModelArtifacts returns a ModelArtifacts
func newModelArtifacts(c *WorkerV1alpha1Client, namespace string) *modelArtifacts {
	return &modelArtifacts{
		gentype.NewClientWithListAndApply[*workerv1alpha1.ModelArtifact, *workerv1alpha1.ModelArtifactList, *applyconfigurationworkerv1alpha1.ModelArtifactApplyConfiguration](
			"modelartifacts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workerv1alpha1.ModelArtifact { return &workerv1alpha1.ModelArtifact{} },
			func() *workerv1alpha1.ModelArtifactList { return &workerv1alpha1.ModelArtifactList{} },
			gentype.PrefersProtobuf[*workerv1alpha1.ModelArtifact](),
		),
	}
}
