// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	networkingv1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/networking/v1"
	typednetworkingv1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/networking/v1"
	v1 "k8s.io/api/networking/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPAddresses implements IPAddressInterface
type fakeIPAddresses struct {
	*gentype.FakeClientWithListAndApply[*v1.IPAddress, *v1.IPAddressList, *networkingv1.IPAddressApplyConfiguration]
	Fake *FakeNetworkingV1
}

func newFakeIPAddresses(fake *FakeNetworkingV1) typednetworkingv1.IPAddressInterface {
	return &fakeIPAddresses{
		gentype.NewFakeClientWithListAndApply[*v1.IPAddress, *v1.IPAddressList, *networkingv1.IPAddressApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("ipaddresses"),
			v1.SchemeGroupVersion.WithKind("IPAddress"),
			func() *v1.IPAddress { return &v1.IPAddress{} },
			func() *v1.IPAddressList { return &v1.IPAddressList{} },
			func(dst, src *v1.IPAddressList) { dst.ListMeta = src.ListMeta },
			func(list *v1.IPAddressList) []*v1.IPAddress { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.IPAddressList, items []*v1.IPAddress) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
