// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiserverv1alpha1 "gpustack.ai/gpustack/api/server/v1alpha1"
	internalinterfaces "gpustack.ai/gpustack/pkg/kubeclients/informers/internalinterfaces"
	kubernetes "gpustack.ai/gpustack/pkg/kubeclients/kubernetes"
	serverv1alpha1 "gpustack.ai/gpustack/pkg/kubeclients/listers/server/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterBindingInformer provides access to a shared informer and lister for
// ClusterBindings.
type ClusterBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() serverv1alpha1.ClusterBindingLister
}

type clusterBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterBindingInformer constructs a new informer for ClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterBindingInformer(client kubernetes.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterBindingInformer constructs a new informer for ClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterBindingInformer(client kubernetes.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ServerV1alpha1().ClusterBindings(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ServerV1alpha1().ClusterBindings(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ServerV1alpha1().ClusterBindings(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ServerV1alpha1().ClusterBindings(namespace).Watch(ctx, options)
			},
		}, client),
		&apiserverv1alpha1.ClusterBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterBindingInformer) defaultInformer(client kubernetes.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiserverv1alpha1.ClusterBinding{}, f.defaultInformer)
}

func (f *clusterBindingInformer) Lister() serverv1alpha1.ClusterBindingLister {
	return serverv1alpha1.NewClusterBindingLister(f.Informer().GetIndexer())
}
