// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package fake

import (
	v1alpha1 "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/typed/nfd/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNfdV1alpha1 struct {
	*testing.Fake
}

func (c *FakeNfdV1alpha1) NodeFeatures(namespace string) v1alpha1.NodeFeatureInterface {
	return newFakeNodeFeatures(c, namespace)
}

func (c *FakeNfdV1alpha1) NodeFeatureGroups(namespace string) v1alpha1.NodeFeatureGroupInterface {
	return newFakeNodeFeatureGroups(c, namespace)
}

func (c *FakeNfdV1alpha1) NodeFeatureRules() v1alpha1.NodeFeatureRuleInterface {
	return newFakeNodeFeatureRules(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNfdV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
