// Code generated by api. DO NOT EDIT.

package v1alpha1

import (
	serverv1alpha1 "gpustack.ai/gpustack/api/server/v1alpha1"
)

// ClusterSpecApplyConfiguration represents a declarative configuration of the ClusterSpec type for use
// with apply.
//
// ClusterSpec defines the desired spec of Cluster.
type ClusterSpecApplyConfiguration struct {
	// Type is the type of the Cluster.
	Type *serverv1alpha1.ClusterType `json:"type,omitempty"`
	// DisplayName is the display name of the cluster.
	DisplayName *string `json:"displayName,omitempty"`
	// Description is the description of the cluster.
	Description *string `json:"description,omitempty"`
}

// ClusterSpecApplyConfiguration constructs a declarative configuration of the ClusterSpec type for use with
// apply.
func ClusterSpec() *ClusterSpecApplyConfiguration {
	return &ClusterSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithType(value serverv1alpha1.ClusterType) *ClusterSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithDisplayName(value string) *ClusterSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithDescription(value string) *ClusterSpecApplyConfiguration {
	b.Description = &value
	return b
}
