// Code generated by api. DO NOT EDIT.

package v1alpha1

// ClusterReferenceApplyConfiguration represents a declarative configuration of the ClusterReference type for use
// with apply.
//
// ClusterReference is the reference of the cluster.
type ClusterReferenceApplyConfiguration struct {
	// Namespace is the namespace of the cluster.
	Namespace *string `json:"namespace,omitempty"`
	// Name is the name of the cluster.
	Name *string `json:"name,omitempty"`
}

// ClusterReferenceApplyConfiguration constructs a declarative configuration of the ClusterReference type for use with
// apply.
func ClusterReference() *ClusterReferenceApplyConfiguration {
	return &ClusterReferenceApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ClusterReferenceApplyConfiguration) WithNamespace(value string) *ClusterReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterReferenceApplyConfiguration) WithName(value string) *ClusterReferenceApplyConfiguration {
	b.Name = &value
	return b
}
