// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1

import (
	context "context"

	workerv1 "gpustack.ai/gpustack/api/worker/v1"
	applyconfigurationworkerv1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/worker/v1"
	scheme "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InstanceImagePullSecretsGetter has a method to return a InstanceImagePullSecretInterface.
// A group's client should implement this interface.
type InstanceImagePullSecretsGetter interface {
	InstanceImagePullSecrets(namespace string) InstanceImagePullSecretInterface
}

// InstanceImagePullSecretInterface has methods to work with InstanceImagePullSecret resources.
type InstanceImagePullSecretInterface interface {
	Create(ctx context.Context, instanceImagePullSecret *workerv1.InstanceImagePullSecret, opts metav1.CreateOptions) (*workerv1.InstanceImagePullSecret, error)
	Update(ctx context.Context, instanceImagePullSecret *workerv1.InstanceImagePullSecret, opts metav1.UpdateOptions) (*workerv1.InstanceImagePullSecret, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*workerv1.InstanceImagePullSecret, error)
	List(ctx context.Context, opts metav1.ListOptions) (*workerv1.InstanceImagePullSecretList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *workerv1.InstanceImagePullSecret, err error)
	Apply(ctx context.Context, instanceImagePullSecret *applyconfigurationworkerv1.InstanceImagePullSecretApplyConfiguration, opts metav1.ApplyOptions) (result *workerv1.InstanceImagePullSecret, err error)
	InstanceImagePullSecretExpansion
}

// instanceImagePullSecrets implements InstanceImagePullSecretInterface
type instanceImagePullSecrets struct {
	*gentype.ClientWithListAndApply[*workerv1.InstanceImagePullSecret, *workerv1.InstanceImagePullSecretList, *applyconfigurationworkerv1.InstanceImagePullSecretApplyConfiguration]
}

// newInstanceImagePullSecrets returns a InstanceImagePullSecrets
func newInstanceImagePullSecrets(c *WorkerV1Client, namespace string) *instanceImagePullSecrets {
	return &instanceImagePullSecrets{
		gentype.NewClientWithListAndApply[*workerv1.InstanceImagePullSecret, *workerv1.InstanceImagePullSecretList, *applyconfigurationworkerv1.InstanceImagePullSecretApplyConfiguration](
			"instanceimagepullsecrets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workerv1.InstanceImagePullSecret { return &workerv1.InstanceImagePullSecret{} },
			func() *workerv1.InstanceImagePullSecretList { return &workerv1.InstanceImagePullSecretList{} },
			gentype.PrefersProtobuf[*workerv1.InstanceImagePullSecret](),
		),
	}
}
