// SPDX-FileCopyrightText: 2026 GPUStack, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gpustack", DO NOT EDIT.

// Code generated by api. DO NOT EDIT.

package v1

import (
	context "context"

	workerv1 "gpustack.ai/gpustack/api/worker/v1"
	applyconfigurationworkerv1 "gpustack.ai/gpustack/pkg/kubeclients/applyconfiguration/worker/v1"
	scheme "gpustack.ai/gpustack/pkg/kubeclients/kubernetes/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KVCacheBackendsGetter has a method to return a KVCacheBackendInterface.
// A group's client should implement this interface.
type KVCacheBackendsGetter interface {
	KVCacheBackends() KVCacheBackendInterface
}

// KVCacheBackendInterface has methods to work with KVCacheBackend resources.
type KVCacheBackendInterface interface {
	Create(ctx context.Context, kVCacheBackend *workerv1.KVCacheBackend, opts metav1.CreateOptions) (*workerv1.KVCacheBackend, error)
	Update(ctx context.Context, kVCacheBackend *workerv1.KVCacheBackend, opts metav1.UpdateOptions) (*workerv1.KVCacheBackend, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*workerv1.KVCacheBackend, error)
	List(ctx context.Context, opts metav1.ListOptions) (*workerv1.KVCacheBackendList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *workerv1.KVCacheBackend, err error)
	Apply(ctx context.Context, kVCacheBackend *applyconfigurationworkerv1.KVCacheBackendApplyConfiguration, opts metav1.ApplyOptions) (result *workerv1.KVCacheBackend, err error)
	KVCacheBackendExpansion
}

// kVCacheBackends implements KVCacheBackendInterface
type kVCacheBackends struct {
	*gentype.ClientWithListAndApply[*workerv1.KVCacheBackend, *workerv1.KVCacheBackendList, *applyconfigurationworkerv1.KVCacheBackendApplyConfiguration]
}

// newKVCacheBackends returns a KVCacheBackends
func newKVCacheBackends(c *WorkerV1Client) *kVCacheBackends {
	return &kVCacheBackends{
		gentype.NewClientWithListAndApply[*workerv1.KVCacheBackend, *workerv1.KVCacheBackendList, *applyconfigurationworkerv1.KVCacheBackendApplyConfiguration](
			"kvcachebackends",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *workerv1.KVCacheBackend { return &workerv1.KVCacheBackend{} },
			func() *workerv1.KVCacheBackendList { return &workerv1.KVCacheBackendList{} },
			gentype.PrefersProtobuf[*workerv1.KVCacheBackend](),
		),
	}
}
