// Code generated by api. DO NOT EDIT.

package v1beta1

// ParentReferenceApplyConfiguration represents a declarative configuration of the ParentReference type for use
// with apply.
//
// ParentReference describes a reference to a parent object.
type ParentReferenceApplyConfiguration struct {
	// Group is the group of the object being referenced.
	Group *string `json:"group,omitempty"`
	// Resource is the resource of the object being referenced.
	Resource *string `json:"resource,omitempty"`
	// Namespace is the namespace of the object being referenced.
	Namespace *string `json:"namespace,omitempty"`
	// Name is the name of the object being referenced.
	Name *string `json:"name,omitempty"`
}

// ParentReferenceApplyConfiguration constructs a declarative configuration of the ParentReference type for use with
// apply.
func ParentReference() *ParentReferenceApplyConfiguration {
	return &ParentReferenceApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ParentReferenceApplyConfiguration) WithGroup(value string) *ParentReferenceApplyConfiguration {
	b.Group = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ParentReferenceApplyConfiguration) WithResource(value string) *ParentReferenceApplyConfiguration {
	b.Resource = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ParentReferenceApplyConfiguration) WithNamespace(value string) *ParentReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ParentReferenceApplyConfiguration) WithName(value string) *ParentReferenceApplyConfiguration {
	b.Name = &value
	return b
}
